import {it,vi} from 'vitest';
import {writeFileSync} from 'node:fs';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {beginPlaytest,finishPlaytestTask,perform} from '../../src/world/playtestHelpers';
import {activeCharacter,activeTask,canPromote} from '../../src/world/simulation';
import {professionById} from '../../src/content/professions';
import {resolveTaskTemplate} from '../../src/content/scenarios';
import {availableWork} from '../../src/world/workLoop';
it('records repeat-play strategies without modifying saves',()=>{const rows=[];for(const role of ['frontend','qa','designer','product'])for(const style of ['shared','limited']){let c=beginPlaytest(role),error='',maxStress=0,minMoney=activeCharacter(c).stats.money,maxOvertime=0;for(let d=0;d<40;d++){try{if(c.phase==='ended')break;if(c.life?.reviewDue)c=perform(c,{type:'performance',accept:true});for(const e of c.schedule.filter(e=>e.type!=='task'&&e.status==='pending'))c=perform(c,{type:'event',id:e.id,choiceId:e.type==='sync'?'plan':e.type==='incident'?'rollback':e.type==='company'?'quality':e.type==='career'?'reflect':'skip'});if(!activeTask(c)||activeTask(c)!.rewarded){const q=c.life!.queue.find(q=>q.status!=='done'&&!q.delegatedTo&&availableWork(activeCharacter(c)).includes(q.id));if(q)c=perform(c,{type:'priority',id:q.id,explained:true});c=perform(c,{type:'take-task'});}if(activeTask(c)&&!activeTask(c)!.rewarded)c=finishPlaytestTask(c,style);if(c.phase==='reward')c=perform(c,{type:'reward-close'});const ch=activeCharacter(c);for(const id of professionById[role].careers.find(n=>n.id===ch.careerNodeId)!.next)if(canPromote(ch,id))c=perform(c,{type:'promote',nodeId:id});maxStress=Math.max(maxStress,activeCharacter(c).stats.stress);minMoney=Math.min(minMoney,activeCharacter(c).stats.money);maxOvertime=Math.max(maxOvertime,Math.max(0,c.time-1080));c=perform(c,{type:'end-day'});for(const id of ['cook','read'] as const)c=perform(c,{type:'evening',id});c=perform(c,{type:'sleep'});}catch(e){error=String(e);break;}}const ch=activeCharacter(c),tasks=c.tasks.filter(t=>t.rewarded);const structural=(task:typeof tasks[number])=>JSON.stringify(resolveTaskTemplate(task).steps.map(s=>{const actions=s.actionFlow?.actions??[];return {type:s.type,artifactKinds:actions.map(a=>a.artifact?.kind??null),edges:actions.map(a=>(a.next??[]).map(id=>actions.findIndex(x=>x.id===id))),dependencies:actions.map(a=>[!!a.requiresReply,!!a.delegates]),choices:s.options?.length??0};}));rows.push({role,style,completed:tasks.length,calendarDay:c.life!.calendarDay,playedDays:c.life!.characterPlayedDays,minMoney,maxOvertime,warningStage:c.life!.reviewStage,reviewDue:c.life!.reviewDue,graphShapes:new Set(tasks.map(structural)).size,familyCounts:Object.fromEntries([...new Set(tasks.map(t=>t.sceneFamily??'starter'))].map(f=>[f,tasks.filter(t=>(t.sceneFamily??'starter')===f).length])),grade:ch.careerNodeId,money:ch.stats.money,maxStress,phase:c.phase,error,families:[...new Set(tasks.map(t=>t.sceneFamily??'starter'))],templates:[...new Set(tasks.map(t=>t.templateId))].length,encounters:c.company!.projects.flatMap(p=>p.problems).reduce((n,p)=>n+(p.story?.encounters.length??0),0)});}writeFileSync('docs/interest-audit-v0.57.4-runs.json',JSON.stringify(rows,null,2));console.log(JSON.stringify(rows));},120000);
