import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {emptyCampaign,activeCharacter,activeTask,makeSchedule} from './simulation';
import {resolveTaskTemplate} from '../content/scenarios';
import {migrateLegacy} from './store';
function start(){let c=transition(emptyCampaign(),{type:'new',name:'Experiment',avatarId:'1',professionId:'qa',seed:1427}).campaign;delete activeCharacter(c).firstDay;activeCharacter(c).completedWork=['one','two'];const project=c.company!.projects[0],q=c.life!.queue.find(q=>q.id==='bug')!;q.status='selected';q.explained=true;q.projectId=project.id;q.problemId=project.problems.find(p=>p.category==='payment')!.id;c.schedule=makeSchedule(c);c.schedule[0].status='completed';c=transition(c,{type:'take-task'}).campaign;return transition(c,{type:'technical-action',id:'inspect'}).campaign;}
const progress=(c:ReturnType<typeof start>)=>activeTask(c)!.progress[activeTask(c)!.currentStepId];
describe('small controlled experiments',()=>{
 it('selecting conditions reveals no result, preserves resources and survives reload',()=>{let c=start();const before=structuredClone(activeCharacter(c).stats),time=c.time;c=transition(c,{type:'artifact-condition',actionId:'trace',rowId:'request.repeat'}).campaign;expect(progress(c).artifactConditions!.trace).toBe('request.repeat');expect(progress(c).artifactReadings?.trace).toBeUndefined();expect(progress(c).observations?.trace).toBeUndefined();expect(c.time).toBe(time);expect(activeCharacter(c).stats).toEqual(before);c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(progress(c).artifactConditions!.trace).toBe('request.repeat');});
 it('both orders of experiments give evidence and do not change production',()=>{for(const order of [['request.first','request.repeat'],['request.repeat','request.first']]){let c=start();const projectBefore=structuredClone(c.company!.projects[0]);for(const rowId of order){c=transition(c,{type:'artifact-condition',actionId:'trace',rowId}).campaign;c=transition(c,{type:'artifact-inspect',actionId:'trace',rowId}).campaign;}expect(progress(c).artifactReadings!.trace).toEqual(order);expect(c.company!.projects[0]).toEqual(projectBefore);c=transition(c,{type:'artifact-compare',id:'trace'}).campaign;expect(progress(c).observations?.trace).toBeTruthy();expect(progress(c).status).toBe('completed');expect(transition(c,{type:'artifact-compare',id:'trace'}).campaign).toEqual(c);}});
 it('invalid/optional conditions are harmless and do not bypass the comparison',()=>{let c=start();for(const rowId of ['missing','reference.health'])expect(transition(c,{type:'artifact-condition',actionId:'trace',rowId}).campaign).toEqual(c);c=transition(c,{type:'artifact-inspect',actionId:'trace',rowId:'request.first'}).campaign;expect(transition(c,{type:'artifact-compare',id:'trace'}).campaign).toEqual(c);expect(resolveTaskTemplate(activeTask(c)!).steps[0].actionFlow!.actions.find(a=>a.id==='trace')!.artifact!.experiment).toBe(true);});
});
