import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {activeCharacter,activeTask,emptyCampaign,makeSchedule,candidates} from './simulation';
import {finishPlaytestTask} from './playtestHelpers';
import {advanceCalendar,archiveCareer,closeWorkDay,decision,endCareer,takeVacation} from './life';
import {buildCareerReport} from './careerReport';
import {migrateLegacy} from './store';
import {communicateExpectation,expectationPressure} from './expectations';
import {assignResponsibility,resolveResponsibilities,checkResponsibility} from './responsibility';
import type {Campaign} from './types';
function start(){const c=transition(emptyCampaign(),{type:'new',name:'Story',avatarId:'1',professionId:'frontend',seed:1427}).campaign;activeCharacter(c).firstDay!.onboardingCompleted=true;activeCharacter(c).firstDay!.currentOnboardingStep='done';activeCharacter(c).completedWork=['intro1','intro2'];return c;}
function assign(c:Campaign){const q=c.life!.queue.find(q=>q.id==='bug')!,p=c.company!.projects[0];q.status='selected';q.explained=true;q.projectId=p.id;q.problemId=p.problems.find(p=>p.category==='payment')!.id;c.phase='office';c.time=540;c.activeTaskId=null;c.schedule=makeSchedule(c);c.schedule[0].status='completed';return transition(c,{type:'take-task'}).campaign;}
describe('v0.26 evidence-based career reports',()=>{
 it('links temporary benefit, later consequence and renewed work to the original decision',()=>{let c=finishPlaytestTask(assign(start()),'limited');const id=activeTask(c)!.id;for(let i=0;i<8;i++)advanceCalendar(c);c=finishPlaytestTask(assign(c));const report=buildCareerReport(c,'quit');expect(report.stats.temporary).toBe(1);expect(report.stats.recurrences).toBe(1);expect(report.patterns.some(p=>p.key==='report.pattern.systemic')).toBe(true);const episode=report.decisions.find(d=>d.taskId===id)!;expect(episode.sources).toContain(id+':outcome:followup');expect(episode.detailKeys).toContain('report.encountered');expect(report.stats.properFixes).toBe(1);});
 it('does not invent a recurrence while a temporary consequence is pending',()=>{const c=finishPlaytestTask(assign(start()),'limited');const report=buildCareerReport(c,'quit');expect(report.stats.recurrences).toBe(0);expect(report.decisions[0].detailKeys).toContain('report.pending');});
 it('distinguishes assignment, returned result and confirmed response',()=>{const c=start();c.phase='office';expect(assignResponsibility(c,'review','oleg')).toBe(true);expect(buildCareerReport(c,'quit').decisions[0].key).toBe('report.delegation.working');while(c.life!.calendarDay<c.company!.delegations![0].dueDay)advanceCalendar(c);resolveResponsibilities(c);expect(buildCareerReport(c,'quit').decisions[0].key).toBe('report.delegation.returned');checkResponsibility(c,c.company!.delegations![0].id,'clarify');const report=buildCareerReport(c,'quit');expect(report.stats.delegationsChecked).toBe(1);expect(report.decisions[0].detailKeys).toEqual(['responsibility.result.verified','responsibility.response.clarify']);});
 it('records the actual mentoring outcome, including a bounded result',()=>{let c=finishPlaytestTask(assign(start()),'limited');activeCharacter(c).careerNodeId='level-1';c=transition(c,{type:'perspective-start'}).campaign;for(const id of ['reproduce','environment','regression','mentor','teach-case','teach-limits'])c=transition(c,{type:'perspective-action',id}).campaign;const report=buildCareerReport(c,'quit');expect(report.stats.mentoring).toBe(1);expect(report.decisions.find(d=>d.key==='report.mentoring')!.detailKeys).toContain('mastery.mentorLimited');});
 it('records communicated delays and overdue obligations with player attribution',()=>{const c=start();c.phase='office';const q=c.life!.queue.find(q=>q.id==='feature')!;q.expectation={state:'waiting',dueDay:2};communicateExpectation(c,'feature','blocker');c.life!.calendarDay=12;expectationPressure(c);const report=buildCareerReport(c,'quit');expect(report.stats.communicated).toBe(1);expect(report.stats.overdue).toBeGreaterThan(0);expect(report.decisions.some(d=>d.detailKeys?.includes('expect.reaction.escalated'))).toBe(true);});
 it('describes many months of vacations and one real main task without moral judgment',()=>{let c=finishPlaytestTask(assign(start()));c.phase='home';for(let i=0;i<16;i++){c.life!.montage=null;takeVacation(c,14,{bug:'ignore',feature:'ignore',debt:'ignore'});}const report=buildCareerReport(c,'quit');expect(report.stats.calendarDays).toBeGreaterThan(300);expect(report.stats.completedTasks).toBe(1);expect(report.stats.vacations).toBe(16);expect(report.stats.unagreed).toBeGreaterThan(0);expect(report.timeline.find(l=>l.key==='report.vacationPath')!.values!.tasks).toBe(1);expect(report.patterns.some(l=>l.key==='report.pattern.absence')).toBe(true);});
 it('explains dismissal from recorded issues and a sequence of warnings',()=>{let c=start();for(let round=0;round<4;round++){c.life!.calendarDay+=5;for(let i=0;i<4;i++)decision(c,'riskyDeploys');closeWorkDay(c);c=transition(c,{type:'performance',accept:true}).campaign;}expect(c.life!.ended).toBe('fired');const report=c.meta!.careers[0].report!;expect(report.reason.find(l=>l.key==='report.reviewChain')!.values!.count).toBe(4);expect(report.reason.some(l=>l.key==='report.issue.riskyDeploys')).toBe(true);expect(report.timeline.at(-1)!.values!.day).toBe(c.life!.calendarDay);});
 it('keeps the report immutable after new hero, later consequences and reload',()=>{let c=finishPlaytestTask(assign(start()),'limited');endCareer(c,'quit');const old=c.meta!.careers[0],saved=JSON.stringify(old.report);c=transition(c,{type:'next-career'}).campaign;c=transition(c,{type:'new',name:'Next',avatarId:'2',professionId:'qa',seed:88}).campaign;c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(JSON.stringify(c.meta!.careers[0].report)).toBe(saved);expect(c.activeCharacterId).not.toBe(old.characterId);});
 it('archives only once and leaves old report-less archives intact',()=>{const c=start();archiveCareer(c,'quit');const report=JSON.stringify(c.meta!.careers[0]);archiveCareer(c,'fired');expect(c.meta!.careers).toHaveLength(1);expect(JSON.stringify(c.meta!.careers[0])).toBe(report);delete c.meta!.careers[0].report;expect(migrateLegacy(JSON.parse(JSON.stringify(c))).meta!.careers[0].report).toBeUndefined();});
 it('keeps the old hero’s contribution connected to a successor in the same world',()=>{let c=finishPlaytestTask(assign(start()),'limited');const oldId=c.activeCharacterId,oldTask=activeTask(c)!.id;activeCharacter(c).careerNodeId='level-3';c.phase='office';c.schedule.forEach(e=>e.status='completed');const successor=candidates(c).find(n=>n.profession==='frontend')!;c=transition(c,{type:'hire',id:successor.id}).campaign;expect(c.activeCharacterId).toBe(successor.id);expect(c.characters.find(n=>n.id===oldId)!.employed).toBe(true);const report=JSON.stringify(c.meta!.careers[0].report);activeCharacter(c).completedWork=['intro1','intro2'];activeCharacter(c).firstDay!.onboardingCompleted=true;activeCharacter(c).firstDay!.currentOnboardingStep='done';c=assign(c);expect(activeTask(c)!.encounter!.originTaskId).toBe(oldTask);expect(activeTask(c)!.encounter!.previousActorId).toBe(oldId);c=finishPlaytestTask(c);c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(JSON.stringify(c.meta!.careers[0].report)).toBe(report);});
 it('counts one overdue obligation once across several daily reactions',()=>{const c=start();c.phase='office';for(const q of c.life!.queue)q.expectation={state:'waiting',dueDay:2};c.life!.calendarDay=7;expectationPressure(c);const first=buildCareerReport(c,'quit').stats.overdue;c.life!.calendarDay++;expectationPressure(c);expect(buildCareerReport(c,'quit').stats.overdue).toBe(first);});
 it('reports the applied debt delta instead of a nominal reward clipped at zero',()=>{let c=assign(start());c.company!.projects[0].techDebt=0;c=finishPlaytestTask(c);const report=buildCareerReport(c,'quit');expect(c.company!.projects[0].problems.find(p=>p.category==='payment')!.story!.encounters[0].debtImpact).toBe(0);expect(report.stats.properFixes).toBe(1);});
});
