import {it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {emptyCampaign,activeCharacter} from './simulation';
import {transition} from './engine';
import {professionById} from '../content/professions';
import {conferenceOffer,attendConference,conferenceBlock} from './conferences';
function campaign(){const c=transition(emptyCampaign(),{type:'new',name:'Senior',avatarId:'1',professionId:'frontend',seed:1427}).campaign;const ch=activeCharacter(c);ch.careerNodeId=professionById.frontend.careers[2].id;ch.firstDay=undefined;c.phase='office';c.schedule=[];c.time=600;return c;}
it('offers only Senior+ and keeps a 45-day interval after a choice',()=>{const c=campaign(),ch=activeCharacter(c);expect(conferenceOffer(c)).not.toBeNull();ch.careerNodeId=professionById.frontend.careers[0].id;expect(conferenceOffer(c)).toBeNull();ch.careerNodeId=professionById.frontend.careers[2].id;attendConference(c,'skip','evidence');expect(conferenceOffer(c)).toBeNull();c.life!.calendarDay+=45;expect(conferenceOffer(c)).not.toBeNull();});
it('paid attendance charges once, survives reload and never fixes production',()=>{const c=campaign(),ch=activeCharacter(c),before=ch.stats.money,project=JSON.stringify(c.company!.projects);const next=transition(c,{type:'conference',mode:'visit',topic:'handoff'}).campaign;expect(activeCharacter(next).stats.money).toBe(before-4000);expect(next.time).toBe(780);expect(JSON.stringify(next.company!.projects)).toBe(project);const restored=JSON.parse(JSON.stringify(next));expect(attendConference(restored,'visit','handoff')).toBe(false);expect(activeCharacter(restored).stats.money).toBe(before-4000);expect(activeCharacter(restored).conferences![0].topic).toBe('handoff');});
it('online is free, unaffordable trips do not create debt, and work stays open',()=>{const c=campaign(),ch=activeCharacter(c);ch.stats.money=500;expect(conferenceBlock(c,'visit')).toBe('money');expect(attendConference(c,'visit','evidence')).toBe(false);expect(ch.home?.finances?.owed??0).toBe(0);expect(attendConference(c,'online','evidence')).toBe(true);expect(ch.stats.money).toBe(500);expect(c.time).toBe(690);expect(c.phase).toBe('office');});
it('pending sync, incident and late hours explain unavailable attendance',()=>{const c=campaign();c.schedule=[{id:'sync',type:'sync',status:'pending',key:'ui.sync'}];expect(conferenceBlock(c,'online')).toBe('sync');c.schedule[0].type='incident';expect(conferenceBlock(c,'online')).toBe('incident');c.schedule=[];c.time=1050;expect(conferenceBlock(c,'online')).toBe('time');expect(attendConference(c,'skip','handoff')).toBe(true);});
