import { describe,it,expect,vi } from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import { transition } from './engine';
import { emptyCampaign,activeCharacter } from './simulation';
import { dailySalary,monthlySalary,recovery,homeState } from './economy';
import { migrateLegacy } from './store';
function ready(){const c=transition(emptyCampaign(),{type:'new',name:'Home test',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete c.characters.find(n=>n.id===c.activeCharacterId)!.firstDay;c.schedule.forEach(e=>e.status='completed');return c;}
describe('home and pay',()=>{
 it('pays once at day end, preserves payment and purchases through reload',()=>{let c=ready();const before=activeCharacter(c).stats.money;const pay=dailySalary(activeCharacter(c));c=transition(c,{type:'end-day'}).campaign;expect(activeCharacter(c).stats.money).toBe(before+pay-c.life!.livingCost);c=transition(c,{type:'end-day'}).campaign;expect(activeCharacter(c).stats.money).toBe(before+pay-c.life!.livingCost);c=transition(c,{type:'buy-home',id:'plants'}).campaign;const saved=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(homeState(activeCharacter(saved)).owned).toEqual(['plants']);expect(transition(saved,{type:'buy-home',id:'plants'}).campaign).toEqual(saved);expect(transition(saved,{type:'end-day'}).campaign).toEqual(saved);});
 it('rejects purchases during work, invalid items and unaffordable purchases',()=>{let c=ready();expect(transition(c,{type:'buy-home',id:'plants'}).campaign).toEqual(c);c=transition(c,{type:'end-day'}).campaign;activeCharacter(c).stats.money=0;expect(transition(c,{type:'buy-home',id:'bed'}).campaign).toEqual(c);expect(transition(c,{type:'buy-home',id:'bad'}).campaign).toEqual(c);});
 it('limits evening choices to one per day, upgrades help and sleeping unlocks the next day',()=>{let c=transition(ready(),{type:'end-day'}).campaign;c=transition(c,{type:'buy-home',id:'library'}).campaign;let ch=activeCharacter(c);const craft=ch.skills.craft;c=transition(c,{type:'evening',id:'read'}).campaign;expect(activeCharacter(c).skills.craft).toBe(craft+2);expect(transition(c,{type:'evening',id:'read'}).campaign).toEqual(c);c=transition(c,{type:'sleep'}).campaign;expect(c.phase).toBe('office');expect(c.company!.currentDay).toBe(2);expect(transition(c,{type:'sleep'}).campaign).toEqual(c);});
 it('migrates older saves without inventing past salary or home purchases',()=>{const c=migrateLegacy(JSON.parse(JSON.stringify(ready())));expect(homeState(activeCharacter(c)).owned).toEqual([]);expect(homeState(activeCharacter(c)).lastPay).toBe(0);});
 it('scales salary with career and clamps recovery stats',()=>{let c=ready(),ch=activeCharacter(c);const junior=monthlySalary(ch);ch.careerNodeId='level-2';expect(monthlySalary(ch)).toBeGreaterThan(junior);c=transition(c,{type:'end-day'}).campaign;ch=activeCharacter(c);ch.stats.money=100000;c=transition(c,{type:'buy-home',id:'bed'}).campaign;expect(recovery(activeCharacter(c)).energy).toBe(85);c=transition(c,{type:'sleep'}).campaign;expect(activeCharacter(c).stats.energy).toBeLessThanOrEqual(100);expect(activeCharacter(c).stats.stress).toBeGreaterThanOrEqual(0);});
});
