import { beforeEach,describe,expect,it,vi } from 'vitest';
const storage=new Map<string,string>();
vi.stubGlobal('localStorage',{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)});
const {transition}=await import('./engine');
const {activeCharacter,activeTask,candidates,emptyCampaign,generateWorld}=await import('./simulation');
const {useWorld,migrateLegacy}=await import('./store');
const {templateById,templates}=await import('../content/scenarios');
const {professions}=await import('../content/professions');
const {dictionary,translate}=await import('../content/localization');
const {setAnalyticsSink,trackGameEvent}=await import('./analytics');
import type { Campaign } from './types';
import type { Action } from './engine';
let c:Campaign;
const act=(a:Action)=>{c=transition(c,a).campaign;};
function start(role='frontend'){c=emptyCampaign();act({type:'new',name:'Test player',avatarId:'2',professionId:role,seed:1427});delete activeCharacter(c).firstDay;sync();}
function sync(){const e=c.schedule.find(e=>e.type==='sync')!;act({type:'event',id:e.id,choiceId:'plan'});if(c.company!.currentDay>=3)act({type:'priority',id:'bug',explained:true});if(c.life?.reviewDue)act({type:'performance',accept:true});act({type:'take-task'});}
function finishStep(){let task=activeTask(c)!,step=templateById[task.templateId].steps.find(s=>s.id===task.currentStepId)!;
 if(['terminal','review','console'].includes(step.type)){act({type:'run'});act({type:'finish-run',taskId:task.id,stepId:step.id});}
 if(step.type==='bug-reproduction'){act({type:'click'});act({type:'click'});}
 if(step.solution){if(Array.isArray(step.solution)){for(const id of step.solution)if(!activeTask(c)!.progress[step.id].draft.includes(id))act({type:'draft',id});}else for(const [id,value]of Object.entries(step.solution))act({type:'allocate',id,value});act({type:'submit'});}
 if(step.options)act({type:'choose',id:step.options.find(o=>o.correct!==false)!.id});
 expect(activeTask(c)!.progress[step.id].status).toBe('completed');act({type:'advance'});
}
function finishTask(){for(let i=0;i<15&&!activeTask(c)!.rewarded;i++)finishStep();expect(activeTask(c)!.rewarded).toBe(true);act({type:'reward-close'});}
function dayEvents(shortcut=false){for(const e of c.schedule.filter(e=>e.status==='pending'&&e.type!=='task')){const choices:Record<string,string>={sync:'plan',dialogue:'learn',career:'reflect',company:shortcut?'rush':'quality',incident:shortcut?'workaround':'rollback',survey:'skip'};act({type:'event',id:e.id,choiceId:choices[e.type]});}}
beforeEach(()=>{storage.clear();setAnalyticsSink(()=>{});c=emptyCampaign();});
describe('Persistent company campaign',()=>{
 it('generates a deterministic world and covers every role with valid translated scenarios',()=>{expect(generateWorld(88)).toEqual(generateWorld(88));expect(generateWorld(88).company.archetype).not.toBe(generateWorld(1427).company.archetype);expect(professions).toHaveLength(22);for(const p of professions){expect(p.scenarioIds.length).toBeGreaterThanOrEqual(2);for(const id of p.scenarioIds)expect(templateById[id]).toBeDefined();}for(const template of templates){expect(dictionary[template.titleKey]?.en).toBeTruthy();for(const s of template.steps){expect(dictionary[s.bodyKey]?.en).toBeTruthy();expect(s.type).toBeTruthy();}}});
 it('keeps failed steps active, blocks future actions and rewards only once after reload',async()=>{start();const task=activeTask(c)!;act({type:'advance'});expect(activeTask(c)!.currentStepId).toBe('files');act({type:'choose',id:'home'});expect(activeTask(c)!.attemptsByStep.files).toBe(1);expect(activeTask(c)!.taskElapsedMinutes).toBe(5);expect(activeTask(c)!.progress.files.status).toBe('active');act({type:'choose',id:'hero'});const xp=activeCharacter(c).stats.xp;act({type:'choose',id:'hero'});expect(activeCharacter(c).stats.xp).toBe(xp);useWorld.setState(c);await useWorld.persist.rehydrate();c=useWorld.getState();expect(activeTask(c)!.progress.files.status).toBe('completed');c=migrateLegacy(JSON.parse(JSON.stringify(c)));act({type:'advance'});finishTask();expect(activeTask(c)!.taskElapsedMinutes).toBe(232);const stats={...activeCharacter(c).stats};act({type:'advance'});act({type:'finish-run',taskId:task.id,stepId:'qa'});expect(activeCharacter(c).stats).toEqual(stats);});
 it('restores two-click reproduction and a pending review without charging twice',()=>{start();finishTask();dayEvents();act({type:'end-day'});act({type:'sleep'});sync();act({type:'click'});c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(activeTask(c)!.progress.reproduce.clicks).toBe(1);act({type:'advance'});expect(activeTask(c)!.currentStepId).toBe('reproduce');act({type:'click'});act({type:'advance'});for(let i=0;i<5;i++)finishStep();expect(activeTask(c)!.currentStepId).toBe('review');act({type:'run'});const minutes=c.time;c=migrateLegacy(JSON.parse(JSON.stringify(c)));act({type:'run'});expect(c.time).toBe(minutes);const task=activeTask(c)!;act({type:'finish-run',taskId:task.id,stepId:'review'});act({type:'advance'});expect(activeTask(c)!.taskElapsedMinutes).toBe(115);expect(c.phase).toBe('reward');});
 it('completes the career, hires QA, preserves consequences and lets the new hero resolve the shared problem',()=>{start();const oldId=c.activeCharacterId,companyId=c.company!.id,projectId=c.company!.projects[0].id;dayEvents(true);finishTask();dayEvents(true);act({type:'end-day'});act({type:'sleep'});sync();finishTask();dayEvents(true);activeCharacter(c).careerNodeId='level-3';expect(activeCharacter(c).careerNodeId).toBe('level-3');const debt=c.company!.techDebt,historyLength=c.company!.history.length,problemIds=c.company!.projects[0].problems.map(p=>p.id);const qa=candidates(c).find(c=>c.profession==='qa')!;act({type:'hire',id:qa.id});expect(c.company!.id).toBe(companyId);expect(c.company!.projects[0].id).toBe(projectId);expect(c.company!.techDebt).toBe(debt);expect(c.company!.projects[0].problems.map(p=>p.id)).toEqual(problemIds);expect(c.company!.history.length).toBeGreaterThan(historyLength);expect(c.characters.find(ch=>ch.id===oldId)).toMatchObject({employed:true,playable:false,careerNodeId:'level-3'});expect(activeCharacter(c).profession).toBe('qa');act({type:'sleep'});sync();expect(activeTask(c)!.templateId).toBe('qa-repeat');expect(activeTask(c)!.legacyActorId).toBe(oldId);finishTask();expect(c.company!.projects[0].problems.find(p=>p.id===activeTask(c)!.problemId)!.status).toBe('resolved');});
 it.each(['backend','mobile','qa','designer','analyst','product','delivery','sre','sysadmin','security','architect'])('allows %s to recover from a wrong plan and complete role-specific work',role=>{start(role);const task=activeTask(c)!;act({type:'submit'});expect(activeTask(c)!.progress[task.currentStepId].status).toBe('active');finishTask();expect(activeCharacter(c).completedWork).toHaveLength(1);});
 it('remains playable after an incident blocks a task and rejects invalid allocations',()=>{start('delivery');c.company!.stability=20;finishTask();dayEvents();act({type:'end-day'});act({type:'sleep'});sync();expect(activeTask(c)!.status).toBe('blocked');const before=c.time;act({type:'allocate',id:'item-0',value:999});expect(c.time).toBe(before);dayEvents();expect(activeTask(c)!.status).toBe('active');finishTask();});
 it('filters identifying text from telemetry and translates clean/adult independently',()=>{const events:unknown[]=[];setAnalyticsSink(e=>events.push(e));trackGameEvent('task_choice',{name:'PRIVATE',email:'PRIVATE',freeText:'PRIVATE',choiceId:'stable-choice'});expect(JSON.stringify(events)).not.toContain('PRIVATE');expect(JSON.stringify(events)).toContain('stable-choice');expect(translate('ui.problemReaction',{},'en','clean')).toBe('Why did it crash again?');expect(translate('ui.problemReaction',{},'en','adult')).toContain('hell');});
 it('gives an established lead review and planning work',()=>{start('backend');finishTask();dayEvents();activeCharacter(c).careerNodeId='level-3';act({type:'end-day'});for(const template of ['lead-review','lead-plan']){act({type:'sleep'});sync();dayEvents();expect(activeTask(c)!.templateId).toBe(template);finishTask();dayEvents();act({type:'end-day'});}expect(activeCharacter(c).skills.leadership).toBe(2);});
 it('migrates the old two-day save at the exact click and preserves creation phase',()=>{c=migrateLegacy({gamePhase:'task',characters:[{id:'old-player',name:'Existing player',avatarId:'5',profession:'frontend'}],activeCharacterId:'old-player',currentDay:2,time:571,currentTaskId:'FE-1451',currentStepId:'reproduce',completedTasks:['FE-1427'],completedStepIds:[],interaction:{clicks:1},taskElapsedMinutes:6,playerStats:{money:45950,energy:100,stress:0,reputation:10,xp:80}});expect(activeTask(c)!.progress.reproduce.clicks).toBe(1);expect(activeTask(c)!.taskElapsedMinutes).toBe(6);expect(activeCharacter(c).completedWork).toHaveLength(1);act({type:'click'});expect(activeTask(c)!.taskElapsedMinutes).toBe(12);expect(migrateLegacy({...emptyCampaign(),phase:'create'}).phase).toBe('create');});
});

