import { ensureLife,initLife,finishLife,selectPriority,closeWorkDay,reviewResponse,decision,archiveCareer,endCareer,advanceCalendar,montage,payWork } from './life';
import type { WorkKind } from './lifeTypes';
import { availableTopics } from '../content/contextDialogue';
import { marketItems } from '../content/marketplace';
import { homeState,recovery } from './economy';
import { homeUpgrades } from '../content/home';
import type { Campaign,Effect,Feedback,Step,Task } from './types';
import { activeCharacter,activeTask,canPromote,candidates,clamp,emptyCampaign,generateWorld,history,isLeader,makeCharacter,makeSchedule,makeTask } from './simulation';
import { templateById } from '../content/scenarios';
import { professionById } from '../content/professions';
import { trackGameEvent } from './analytics';
export type Action={type:'office-encounter'}|{type:'priority';id:WorkKind;explained:boolean}|{type:'performance';accept:boolean}|{type:'montage'}|{type:'vacation'}|{type:'montage-close'}|{type:'quit'}|{type:'next-career'}|{type:'rename';name:string}|{type:'conversation';npcId:string;topicId:string;choiceId:string}|{type:'order';itemId:string}|{type:'unpack';itemId:string}|{type:'buy-home';id:string}|{type:'evening';id:'walk'|'cook'|'read'|'games'}|{type:'new';name:string;avatarId:string;professionId:string;seed:number}|{type:'choose';id:string}|{type:'draft';id:string}|{type:'allocate';id:string;value:number}|{type:'submit'}|{type:'run'}|{type:'finish-run';taskId:string;stepId:string}|{type:'click'}|{type:'advance'}|{type:'take-task'}|{type:'event';id:string;choiceId:string}|{type:'promote';nodeId:string}|{type:'hire';id:string}|{type:'end-day'}|{type:'sleep'}|{type:'reward-close'}|{type:'survey-open'}|{type:'talk';id:string}|{type:'assign-project';id:string};
export function transition(source:Campaign,action:Action):{campaign:Campaign;feedback:Feedback[]}{const c=ensureLife(structuredClone(source)),feedback:Feedback[]=[];const emit=(name:string,payload:Parameters<typeof trackGameEvent>[1]={})=>trackGameEvent(name,payload);
 const effects=(list:Effect[])=>{const ch=activeCharacter(c);for(const e of list){let previous:number,next:number;if(e.target in ch.stats){const key=e.target as keyof typeof ch.stats;previous=ch.stats[key];next=['stress','energy'].includes(key)?clamp(previous+e.value):key==='reputation'?previous+e.value:Math.max(0,previous+e.value);ch.stats[key]=next;}else if(e.target in ch.skills){const key=e.target as keyof typeof ch.skills;previous=ch.skills[key];next=Math.max(0,previous+e.value);ch.skills[key]=next;}else{const project=c.company!.projects.find(p=>p.id===activeTask(c)?.projectId)??c.company!.projects[0];if(e.target==='processMaturity'){previous=c.company!.processMaturity;next=clamp(previous+e.value);c.company!.processMaturity=next;}else{previous=project[e.target as 'techDebt'|'stability'|'securityLevel'];next=clamp(previous+e.value);project[e.target as 'techDebt'|'stability'|'securityLevel']=next;if(e.target==='techDebt'||e.target==='stability')c.company![e.target]=clamp(c.company![e.target]+e.value);}}if(next!==previous)feedback.push({id:Date.now()+feedback.length,key:`ui.${e.target}`,value:next-previous,good:['stress','techDebt'].includes(e.target)?next<previous:next>previous});}};
 const discover=(ids:string[])=>{const ch=activeCharacter(c);for(const id of ids)if(!ch.discoveredTerms.includes(id)){ch.discoveredTerms.push(id);feedback.push({id:Date.now()+feedback.length,key:`term.${id}.title`,good:true});emit('term_discovered',{termId:id,characterId:ch.id});}};
 const tick=(minutes:number,task?:Task)=>{c.time+=minutes;if(task)task.taskElapsedMinutes+=minutes;if(minutes)feedback.push({id:Date.now()+feedback.length,key:'ui.min',value:minutes,good:true});};
 const completeStep=(task:Task,step:Step,extra:Effect[]=[],minutes=0)=>{const p=task.progress[step.id];if(p.status==='completed')return;if(!p.charged){effects(step.effects);tick(step.minutes,task);p.charged=true;}effects(extra);tick(minutes,task);p.status='completed';if(!task.completedStepIds.includes(step.id))task.completedStepIds.push(step.id);p.responseKey=p.responseKey??'ui.success';discover(step.terms??[]);};
 if(action.type==='new'){if(!professionById[action.professionId]||!['start','create'].includes(c.phase))return {campaign:source,feedback};const fresh=emptyCampaign(),world=generateWorld(action.seed>>>0),ch=makeCharacter(crypto.randomUUID(),action.name.trim().slice(0,24)||'Саша',action.avatarId,action.professionId);ch.currentProjectIds=[world.company.projects[0].id];const meta=c.meta;Object.assign(c,fresh,world,{activeCharacterId:ch.id,characters:[...world.characters,ch],phase:'office'});c.meta=meta;c.life=initLife(c);c.company!.employeeIds.push(ch.id);c.schedule=makeSchedule(c);history(c,'created','ui.newCompany');emit('game_started');emit('character_created',{characterId:ch.id});emit('profession_selected',{professionId:ch.profession});emit('day_started',{day:1});finishLife(c);return {campaign:c,feedback};}
 if(!c.company||!c.characters.some(ch=>ch.id===c.activeCharacterId))return {campaign:source,feedback};
 const ch=activeCharacter(c),task=activeTask(c),template=task?templateById[task.templateId]:undefined,step=template?.steps.find(s=>s.id===task?.currentStepId),progress=step&&task?.progress[step.id];
 if(c.phase==='ended'&&action.type!=='next-career'&&action.type!=='rename')return {campaign:source,feedback};
 if(action.type==='next-career'){if(c.phase!=='ended')return {campaign:source,feedback};const fresh=emptyCampaign();return {campaign:{...fresh,meta:c.meta,phase:'create'},feedback};}
 if(action.type==='office-encounter'){if(c.phase==='office'&&!c.schedule.some(e=>e.type==='incident'&&e.status==='pending'))c.life!.officeEncounterDay=c.company.currentDay;}
 else if(action.type==='priority'){selectPriority(c,action.id,action.explained);}
 else if(action.type==='performance'){reviewResponse(c,action.accept);}
 else if(action.type==='quit'){endCareer(c,'quit');}
 else if(action.type==='montage'||action.type==='vacation'){montage(c,action.type==='vacation');}
 else if(action.type==='montage-close'){if(c.phase!=='home'||!c.life!.montage)return {campaign:source,feedback};const stop=c.life!.montage.stop;c.life!.montage=null;c.company.currentDay++;c.life!.playedDay++;c.life!.queue=initLife(c).queue;c.phase='office';c.activeTaskId=null;c.time=540;c.dayStart={...ch.stats};c.dayWorkStart=ch.completedWork.length;c.schedule=makeSchedule(c);if(stop==='life.officeIncident'&&!c.schedule.some(e=>e.type==='incident'))c.schedule.push({id:'day-'+c.company.currentDay+'-incident',type:'incident',status:'pending',key:'ui.incident'});}
 else if(action.type==='rename'){const name=action.name.trim().slice(0,24);if(!name)return {campaign:source,feedback};ch.name=name;}
 else if(action.type==='take-task'){if(c.phase!=='office'||c.life!.reviewDue||c.company.currentDay>=3&&!c.life!.queue.some(q=>q.status==='selected')||c.schedule.some(e=>e.type==='sync'&&e.status==='pending')||!c.schedule.some(e=>e.type==='task'&&e.status==='pending')||task&&!task.rewarded)return {campaign:source,feedback};const next=makeTask(c);c.tasks.push(next);c.activeTaskId=next.id;emit('task_started',{taskId:next.id,templateId:next.templateId,professionId:ch.profession,day:c.company.currentDay});discover(['bug',...(templateById[next.templateId].steps[0].terms??[])]);}
 else if(action.type==='event'){const event=c.schedule.find(e=>e.id===action.id&&e.status==='pending');if(!event||event.type==='task')return {campaign:source,feedback};const valid:Record<string,string[]>={sync:['plan'],dialogue:['coffee','learn'],incident:['rollback','workaround'],company:['quality','rush'],career:['reflect'],survey:['yes','maybe','no','skip']};if(event.type==='survey'&&c.schedule.some(e=>e.type==='task'&&e.status==='pending'))return {campaign:source,feedback};if(!valid[event.type]?.includes(action.choiceId))return {campaign:source,feedback};event.choiceId=action.choiceId;event.status='completed';emit('event_choice',{eventId:event.id,choiceId:action.choiceId,day:c.company.currentDay});if(event.type==='sync'){effects([{target:'communication',value:1},{target:'reputation',value:1}]);tick(15);discover(['daily']);}else if(event.type==='dialogue'){effects(action.choiceId==='coffee'?[{target:'energy',value:15},{target:'stress',value:-5},{target:'money',value:-c.life!.coffeePrice}]:[{target:'xp',value:5},{target:'stress',value:2}]);tick(25);}else if(event.type==='career'){effects([{target:'communication',value:1},{target:'reputation',value:2}]);tick(20);}else if(event.type==='survey'){c.survey=action.choiceId==='skip'?'skipped':'answered';c.surveyAnswer=action.choiceId;emit(action.choiceId==='skip'?'survey_skipped':'survey_answered',{answerId:action.choiceId});}else{const shortcut=['rush','workaround'].includes(action.choiceId);effects(shortcut?[{target:'techDebt',value:12},{target:'stability',value:-5},{target:'reputation',value:1}]:[{target:'techDebt',value:-6},{target:'stability',value:10},{target:'processMaturity',value:4}]);tick(shortcut?15:40);discover(['debt',...(event.type==='incident'?['rollback']:[])]);const project=c.company.projects.find(p=>p.id===task?.projectId)??c.company.projects[0];if(shortcut){decision(c,'riskyDeploys');const problem=project.problems.find(p=>p.status!=='resolved')??project.problems[0];problem.workaround=true;problem.causedBy=ch.id;problem.status='planned';const h=history(c,'workaround','ui.temporary',{projectId:project.id,problemId:problem.id});problem.history.push(h);project.history.push(h);}if(event.type==='incident'){effects([{target:'stress',value:8}]);c.company.incidents.push({id:event.id,day:c.company.currentDay,resolved:true,projectId:project.id});if(task?.status==='blocked')task.status='active';}}history(c,event.type,event.key);}
 else if(action.type==='assign-project'){if(c.company.projects.some(p=>p.id===action.id)&&(!task||task.rewarded)){ch.currentProjectIds=[action.id];history(c,'assignment','ui.project',{projectId:action.id});}}
 else if(action.type==='promote'){if(!canPromote(ch,action.nodeId)||task&&!task.rewarded)return {campaign:source,feedback};ch.careerNodeId=action.nodeId;c.life!.roleStartedDay=c.life!.calendarDay;ch.milestones=ch.milestones.filter(m=>m!=='performance');c.life!.performanceMilestones=0;const e=history(c,'promotion',professionById[ch.profession].careers.find(n=>n.id===action.nodeId)!.titleKey);ch.careerHistory.push(e);emit('promotion',{characterId:ch.id,careerNodeId:action.nodeId,professionId:ch.profession});}
 else if(action.type==='hire'){if(!isLeader(ch)||!['office','home'].includes(c.phase)||c.schedule.some(e=>e.status==='pending'))return {campaign:source,feedback};const candidate=candidates(c).find(p=>p.id===action.id);if(!candidate)return {campaign:source,feedback};archiveCareer(c,'hired_successor');ch.playable=false;candidate.playable=true;candidate.relationships.push({characterId:ch.id,trust:15});ch.relationships.push({characterId:candidate.id,trust:15});c.characters.push(candidate);c.company.employeeIds.push(candidate.id);const oldId=ch.id;c.activeCharacterId=candidate.id;const calendar=c.life!.calendarDay;c.life=initLife(c);c.life.calendarDay=calendar;c.life.daysAtCompany=1;c.life.characterStartedDay=calendar;c.life.roleStartedDay=calendar;c.activeTaskId=null;c.candidateRound++;c.phase='home';history(c,'hired','ui.newEmployee');emit('character_hired',{characterId:candidate.id,professionId:candidate.profession});emit('active_character_changed',{characterId:candidate.id,oldCharacterId:oldId});}
 else if(action.type==='conversation'){const npc=c.characters.find(x=>x.id===action.npcId&&x.id!==ch.id&&x.employed),topic=npc&&availableTopics(c,npc).find(x=>x.id===action.topicId),choice=topic?.choices.find(x=>x.id===action.choiceId);const key=action.npcId+':'+action.topicId;if(!npc||!topic||!choice||ch.conversations?.[key])return {campaign:source,feedback};ch.conversations={...ch.conversations,[key]:choice.id};if(ch.conversationRewardDay!==c.company.currentDay){ch.conversationRewardDay=c.company.currentDay;const r=ch.relationships.find(x=>x.characterId===npc.id);if(r)r.trust=Math.min(100,r.trust+5);else ch.relationships.push({characterId:npc.id,trust:25});effects([{target:'communication',value:1}]);}emit('conversation_choice',{characterId:npc.id,topicId:topic.id,choiceId:choice.id});}
 else if(action.type==='order'){const item=marketItems.find(i=>i.id===action.itemId);if(!item||!['office','home','reward'].includes(c.phase)||ch.stats.money<item.price||homeState(ch).owned.includes(item.id)||ch.orders?.some(o=>o.itemId===item.id))return {campaign:source,feedback};ch.orders=[...(ch.orders??[]),{itemId:item.id,orderedDay:c.company.currentDay,deliveryDay:c.life!.calendarDay+1,received:false}];effects([{target:'money',value:-item.price}]);emit('market_ordered',{itemId:item.id,amount:item.price,day:c.company.currentDay});}
 else if(action.type==='unpack'){const order=ch.orders?.find(o=>o.itemId===action.itemId),item=marketItems.find(i=>i.id===action.itemId);if(c.phase!=='home'||!order||!item||order.received||order.deliveryDay>c.life!.calendarDay)return {campaign:source,feedback};order.received=true;const home=homeState(ch);ch.home={...home,owned:[...new Set([...home.owned,item.id])]};history(c,'delivery',item.titleKey);emit('market_received',{itemId:item.id,day:c.company.currentDay});}
 else if(action.type==='buy-home'){const item=homeUpgrades.find(u=>u.id===action.id);const home=homeState(ch);if(c.phase!=='home'||!item||home.owned.includes(item.id)||ch.stats.money<item.price)return {campaign:source,feedback};ch.home={...home,owned:[...home.owned,item.id]};effects([{target:'money',value:-item.price}]);history(c,'home-upgrade',item.titleKey);emit('home_upgrade_purchased',{upgradeId:item.id,characterId:ch.id});}
 else if(action.type==='evening'){const home=homeState(ch);if(c.phase!=='home'||home.eveningDay===c.company.currentDay||!['walk','cook','read','games'].includes(action.id))return {campaign:source,feedback};ch.home={...home,eveningDay:c.company.currentDay};effects(action.id==='games'?[{target:'stress',value:-12}]:action.id==='walk'?[{target:'stress',value:-10}]:action.id==='cook'?[{target:'energy',value:home.owned.includes('kitchen')?30:15}]:[{target:'craft',value:1+(home.owned.includes('library')?1:0)},{target:'energy',value:home.owned.includes('chair')?0:-5}]);tick(action.id==='games'?60:action.id==='cook'&&home.owned.includes('kitchen')?20:40);history(c,'evening','home.rest');emit('evening_choice',{choiceId:action.id,day:c.company.currentDay});}
 else if(action.type==='end-day'){if(c.phase!=='office'||c.schedule.some(e=>e.status==='pending'))return {campaign:source,feedback};c.phase='home';const home=homeState(ch);if(home.paidDay!==c.company.currentDay){const pay=payWork(c);ch.home={...home,paidDay:c.company.currentDay,lastPay:pay};history(c,'salary','home.pay',{values:{amount:pay}});emit('salary_paid',{amount:pay,characterId:ch.id,day:c.company.currentDay});}closeWorkDay(c);history(c,'day','ui.rest');emit('day_completed',{day:c.company.currentDay});}
 else if(action.type==='sleep'){if(c.phase!=='home')return {campaign:source,feedback};const rest=recovery(ch);effects([{target:'energy',value:rest.energy},{target:'stress',value:-rest.stress}]);advanceCalendar(c);c.life!.playedDay++;c.company.currentDay++;c.life!.queue=initLife(c).queue;c.phase='office';c.activeTaskId=null;c.time=540;c.dayStart={...ch.stats};c.dayWorkStart=ch.completedWork.length;c.schedule=makeSchedule(c);const drift=c.company.culture==='fast'?2:1;c.company.techDebt=clamp(c.company.techDebt+drift);c.company.projects.forEach(p=>{p.techDebt=clamp(p.techDebt+drift);if(p.techDebt>65)p.stability=clamp(p.stability-2);});emit('day_started',{day:c.company.currentDay});}
 else if(action.type==='reward-close'){if(c.phase==='reward')c.phase='office';}
 else if(action.type==='survey-open'){if(c.survey==='unseen'&&c.schedule.some(e=>e.type==='survey')){c.survey='pending';emit('survey_shown');}}
 else if(action.type==='talk'){const npc=c.characters.find(x=>x.id===action.id&&x.id!==ch.id);if(npc&&!ch.relationships.some(r=>r.characterId===npc.id&&r.trust>=10)){const relation=ch.relationships.find(r=>r.characterId===npc.id);if(relation)relation.trust+=5;else ch.relationships.push({characterId:npc.id,trust:5});effects([{target:'communication',value:1}]);tick(5);}}
 else if(task&&step&&progress&&c.phase==='office'&&task.status!=='completed'&&task.status!=='blocked'){
  const finished=progress.status==='completed';
  if(action.type==='advance'){if(!finished)return {campaign:source,feedback};const next=template!.steps[template!.steps.indexOf(step)+1];if(next){task.currentStepId=next.id;task.progress[next.id].status='active';task.status=next.type==='review'?'review':next.type==='visual-compare'&&task.templateId==='FE-1427'?'qa':'active';discover(next.terms??[]);}else if(!task.rewarded&&template!.steps.every(s=>task.completedStepIds.includes(s.id))){effects(template!.rewards);task.rewarded=true;task.status='completed';ch.completedWork.push(task.id);ch.scenarioCounts[task.templateId]=(ch.scenarioCounts[task.templateId]??0)+1;if(!ch.milestones.includes('independent'))ch.milestones.push('independent');const project=c.company.projects.find(p=>p.id===task.projectId)!,problem=project.problems.find(p=>p.id===task.problemId)!;if(!problem.contributions.includes(template!.contribution))problem.contributions.push(template!.contribution);problem.status=problem.contributions.includes('repair')&&problem.contributions.includes('validation')?'resolved':'planned';project.techDebt=clamp(project.techDebt-2);project.stability=clamp(project.stability+2);c.company.reputation=clamp(c.company.reputation+1);const h=history(c,'task',template!.titleKey,{projectId:project.id,problemId:problem.id});problem.history.push(h);project.history.push(h);if(problem.workaround&&problem.status==='resolved')problem.workaround=false;c.schedule.find(e=>e.type==='task')!.status='completed';c.phase='reward';emit('task_completed',{taskId:task.id,templateId:task.templateId,minutes:task.taskElapsedMinutes,projectId:project.id,problemId:problem.id});}}
  else if(finished)return {campaign:source,feedback};
  else if(action.type==='draft'){if(!step.items?.some(i=>i.id===action.id)||step.type==='resource-allocation')return {campaign:source,feedback};progress.draft=progress.draft.includes(action.id)?progress.draft.filter(id=>id!==action.id):[...progress.draft,action.id];}
  else if(action.type==='allocate'){if(step.type!=='resource-allocation'||!step.items?.some(i=>i.id===action.id)||!Number.isInteger(action.value))return {campaign:source,feedback};progress.allocation[action.id]=Math.max(0,Math.min(step.budget??10,action.value));}
  else if(action.type==='choose'||action.type==='submit'){
   if(step.type==='review'&&progress.run!=='done')return {campaign:source,feedback};let correct=false;let extra:Effect[]=[];let minutes=0;
   if(action.type==='choose'){const option=step.options?.find(o=>o.id===action.id);if(!option)return {campaign:source,feedback};correct=option.correct!==false;progress.choiceId=option.id;progress.responseKey=option.responseKey;extra=option.effects??[];minutes=option.minutes??0;emit('task_choice',{taskId:task.id,templateId:task.templateId,stepId:step.id,choiceId:option.id,correct});}
   else {if(!step.solution)return {campaign:source,feedback};const ordered=['planning','incident-response'].includes(step.type);if(Array.isArray(step.solution)){correct=ordered?JSON.stringify(progress.draft)===JSON.stringify(step.solution):[...progress.draft].sort().join('|')===[...step.solution].sort().join('|');}else correct=Object.entries(step.solution).every(([id,value])=>(progress.allocation[id]??0)===value);progress.responseKey=correct?'ui.correctPlan':'ui.wrongPlan';emit('task_choice',{taskId:task.id,stepId:step.id,choiceId:step.type+'-submit',correct});}
   task.attemptsByStep[step.id]=(task.attemptsByStep[step.id]??0)+1;if(correct)completeStep(task,step,extra,minutes);else{decision(c,'technicalMistakes');if(task.attemptsByStep[step.id]>1)decision(c,'repeatedMistakes');effects(step.wrongEffects);tick(step.wrongMinutes,task);}
  }else if(action.type==='run'){if(!['terminal','review','console'].includes(step.type)||progress.run!=='idle')return {campaign:source,feedback};if(!progress.charged){effects(step.effects);tick(step.minutes,task);progress.charged=true;}if(step.type==='console'){progress.run='done';completeStep(task,step);}else progress.run='running';}
  else if(action.type==='finish-run'){if(action.taskId!==task.id||action.stepId!==step.id||progress.run!=='running')return {campaign:source,feedback};progress.run='done';if(!step.options)completeStep(task,step);}
  else if(action.type==='click'){if(step.type!=='bug-reproduction'||progress.clicks>=2)return {campaign:source,feedback};progress.clicks++;tick(progress.clicks===1?Math.floor(step.minutes/2):Math.ceil(step.minutes/2),task);if(progress.clicks===2){effects(step.effects);progress.charged=true;completeStep(task,step);}}
 }
 finishLife(c);return {campaign:c,feedback};
}


