import {availableTechnicalActions} from './technicalActions';
import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition,type Action} from './engine';
import {activeCharacter,activeTask,emptyCampaign} from './simulation';
import {migrateLegacy} from './store';
import {templateById} from '../content/scenarios';
function start(role='frontend'){return transition(emptyCampaign(),{type:'new',name:'Новый коллега',avatarId:'1',professionId:role,seed:1427}).campaign;}
describe('first work day',()=>{
it.each(['frontend','qa','devops'])('introduces %s before work and resumes every scene',role=>{let c=start(role);const act=(a:Action)=>{c=transition(c,a).campaign;c=migrateLegacy(JSON.parse(JSON.stringify(c)));};expect(activeCharacter(c).firstDay!.currentOnboardingStep).toBe('arrival');act({type:'take-task'});expect(activeTask(c)).toBeUndefined();act({type:'onboarding',name:'Лена'});expect(activeCharacter(c).name).toBe('Лена');act({type:'onboarding',choice:'team'});act({type:'onboarding'});expect(activeCharacter(c).firstDay!.currentOnboardingStep).toBe('project');act({type:'onboarding'});expect(activeCharacter(c).firstDay!.currentOnboardingStep).toBe('meeting');expect(activeCharacter(c).firstDay!.introducedNpcIds.length).toBeGreaterThan(2);act({type:'onboarding',choice:'quiet'});expect(activeCharacter(c).discoveredTerms).toEqual([]);act({type:'discover-term',id:'daily',context:'Это Daily.'});expect(activeCharacter(c).termMemories!.daily.firstSeenContext).toBe('Это Daily.');act({type:'discover-term',id:'daily',context:'Другой контекст'});expect(activeCharacter(c).discoveredTerms).toEqual(['daily']);act({type:'onboarding'});act({type:'take-task'});expect(activeTask(c)).toBeDefined();const task=activeTask(c)!;expect(task.templateId).toBe(role==='frontend'?'FE-1427':role==='qa'?'qa-repeat':'devops-deploy');for(const step of templateById[task.templateId].steps){if(['terminal','review','console'].includes(step.type)){act({type:'run'});act({type:'finish-run',taskId:task.id,stepId:step.id});}if(step.solution){if(Array.isArray(step.solution))for(const id of step.solution)act({type:'draft',id});else for(const [id,value] of Object.entries(step.solution))act({type:'allocate',id,value});act({type:'submit'});}if(step.actionFlow){while(activeTask(c)!.progress[step.id].status!=='completed'){const action=availableTechnicalActions(step,activeTask(c)!.progress[step.id])[0];act({type:'technical-action',id:action.id});}}if(step.options)act({type:'choose',id:step.options.find(o=>o.correct!==false)!.id});if(step.type==='bug-reproduction'){act({type:'click'});act({type:'click'});}act({type:'advance'});}expect(c.phase).toBe('reward');act({type:'reward-close'});expect(activeCharacter(c).firstDay!.currentOnboardingStep).toBe('farewell');act({type:'end-day'});expect(c.phase).toBe('home');expect(activeCharacter(c).firstDay!.onboardingCompleted).toBe(true);act({type:'sleep'});expect(c.company!.currentDay).toBe(2);expect(c.schedule.some(e=>e.type==='career')).toBe(true);});
it('does not send existing careers back through onboarding',()=>{const c=start();delete activeCharacter(c).firstDay;c.company!.currentDay=8;const old=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(activeCharacter(old).firstDay!.onboardingCompleted).toBe(true);expect(old.company!.currentDay).toBe(8);});
});

