import type { Effect } from './types';
export type ProfessionalDecision={explanationKey?:string;decisionId:string;choiceId:string;choiceLabelKey:string;selection?:{labelKey:string;amount?:number}[];profession:string;characterId:string;companyId:string;projectId:string;day:number;minute:number;npcId:string;tags:string[];immediateEffects:Effect[];delayedEffects:Effect[];dueDay:number;resolved:boolean;context:{stability:number;techDebt:number;culture:string};};
export type WorkKind='bug'|'feature'|'debt'|'review'|'support';
export type DecisionStats={technicalMistakes:number;ignoredQa:number;ignoredReview:number;communicationFailures:number;riskyDeploys:number;deadlineFailures:number;repeatedMistakes:number};
export type Outcome='burnout'|'fired'|'quit'|'changed_role'|'changed_company'|'hired_successor'|'other';
export type CareerRecord={runTiming?:import('./runTiming').RunTiming;report?:import('./careerReport').CareerReport;experience?:import('./types').Experience[];characterId:string;name:string;profession:string;maxGrade:string;careerStartedAt:number;careerEndedAt:number;calendarDays:number;playedDays:number;companies:string[];maxSalary:number;majorEvents:string[];outcome:Outcome};
export type MetaProgress={careers:CareerRecord[];roles:Record<string,{maxGrade:number;tasks:number}>;companies:string[];terms:string[];perspectives:Record<string,string[]>};
export type WorkItem={projectId?:string;problemId?:string;expectation?:{state:'assigned'|'waiting'|'overdue'|'escalated'|'resolved';dueDay:number;communication?:'postpone'|'blocker'|'defer';extensionUsed?:boolean;escalationRecorded?:boolean;lastCommunicationDay?:number;lastReactionDay?:number;reactionKey?:string};age?:number;promisedDay?:number;delegatedTo?:string;id:WorkKind;urgency:number;minutes:number;status:'waiting'|'selected'|'done';explained?:boolean};
export type LifeState={weekendSkip?:{days:number;income:number;expenses:number};reportMaxStress?:number;drinksToday?:number;drinkDay?:number;drinkOfTheDay?:number;coffeeScene?:string;vacations?:{day:number;days:number;before:number;after:number;summary:string[]}[];routineSummary?:{from:number;to:number;unfinished:boolean};obligations?:{day:number;work:WorkKind;npcId:string;kind:'waiting'|'promise'|'incident'}[];professionalDecisions?:ProfessionalDecision[];calendarDay:number;playedDay:number;daysAtCompany:number;roleStartedDay:number;characterStartedDay:number;characterPlayedDays:number;lastMontagePlayedDay:number;maxSalary:number;queue:WorkItem[];decisions:DecisionStats;decisionHistory:{day:number;kind:keyof DecisionStats}[];reviewStage:number;reviewDue:boolean;reviewedAt:number;goodDays:number;performanceMilestones:number;ended?:Outcome;worldEvents:{id:string;day:number;until:number}[];coffeePrice?:number;livingCost:number;salaryHeld:number;montage:{days:number;income:number;expenses:number;stop:string;summary?:string[]}|null;nextEventDay:number;officeEncounterDay:number;lastExpenseCalendarDay:number;lastPaidCalendarDay:number};
