import { describe,it,expect,vi } from 'vitest';
const storage=new Map<string,string>();vi.stubGlobal('localStorage',{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)});
import { transition } from './engine';import { emptyCampaign,activeCharacter,canPromote,generateWorld } from './simulation';import { decision,closeWorkDay,finishLife,advanceCalendar,payWork,emptyDecisions,updateMeta } from './life';import { migrateLegacy,useWorld,snapshot } from './store';import { availableTopics,hasNewTopic } from '../content/contextDialogue';
const start=()=>transition(emptyCampaign(),{type:'new',name:'Test',avatarId:'1',professionId:'frontend',seed:1427}).campaign;
describe('life and career simulation',()=>{
it('keeps grades behind time, quality and performance requirements',()=>{const c=start(),ch=activeCharacter(c);ch.completedWork=['1','2','3','4'];ch.skills={craft:50,debugging:50,communication:50,leadership:50};ch.stats.reputation=50;ch.milestones=['independent'];expect(canPromote(ch,'level-1')).toBe(false);c.life!.calendarDay=91;c.life!.performanceMilestones=1;updateMeta(c);expect(canPromote(ch,'level-1')).toBe(true);c.life!.reviewStage=1;updateMeta(c);expect(canPromote(ch,'level-1')).toBe(false);});
it('simulates calendar, finances and project state, stops at an event and cannot repeat montage',()=>{let c=start();c.phase='home';c.life!.characterPlayedDays=3;const money=activeCharacter(c).stats.money,played=c.life!.playedDay,debt=c.company!.techDebt;c=transition(c,{type:'montage'}).campaign;expect(c.life!.calendarDay).toBe(15);expect(c.life!.playedDay).toBe(played);expect(c.life!.characterPlayedDays).toBe(3);expect(c.life!.worldEvents).toHaveLength(1);expect(c.company!.techDebt).toBeGreaterThan(debt);expect(activeCharacter(c).stats.money).not.toBe(money);expect(c.life!.montage!.days).toBe(14);c=transition(c,{type:'montage-close'}).campaign;expect(transition(c,{type:'montage'}).campaign).toEqual(c);expect(migrateLegacy(JSON.parse(JSON.stringify(c))).life).toEqual(c.life);});
it('preserves earned perspectives and archived failures across a new career and reset',()=>{let c=start();c.meta!.perspectives.qa=['bug'];activeCharacter(c).stats.stress=100;finishLife(c);expect(c.phase).toBe('ended');expect(c.meta!.careers[0].outcome).toBe('burnout');const archive=JSON.stringify(c.meta);c=transition(c,{type:'next-career'}).campaign;expect(JSON.stringify(c.meta)).toBe(archive);c=transition(c,{type:'new',name:'Next',avatarId:'2',professionId:'qa',seed:88}).campaign;expect(c.meta!.careers).toHaveLength(1);expect(c.meta!.perspectives.qa).toEqual(['bug']);useWorld.setState(c);useWorld.getState().reset();expect(useWorld.getState().meta!.careers).toHaveLength(2);expect(JSON.parse(storage.get('voiti-vaiti-meta')!).perspectives.qa).toEqual(['bug']);expect(snapshot(useWorld.getState()).phase).toBe('start');});
it('records concrete decisions, warns before dismissal and allows recovery',()=>{let c=start();for(let i=0;i<4;i++)decision(c,'riskyDeploys');c.life!.calendarDay=7;closeWorkDay(c);expect(c.life!.reviewDue).toBe(true);c=transition(c,{type:'performance',accept:true}).campaign;expect(c.life!.reviewStage).toBe(1);expect(c.phase).not.toBe('ended');c.life!.decisionHistory=[];for(let i=0;i<3;i++){c.life!.calendarDay++;closeWorkDay(c);}expect(c.life!.reviewStage).toBe(0);for(let round=0;round<4;round++){c.life!.calendarDay+=5;for(let i=0;i<4;i++)decision(c,'riskyDeploys');closeWorkDay(c);c=transition(c,{type:'performance',accept:true}).campaign;}expect(c.phase).toBe('ended');expect(c.meta!.careers[0].outcome).toBe('fired');});
it('defers wages during payroll trouble and pays arrears only once',()=>{const c=start(),ch=activeCharacter(c),base=ch.stats.money;c.life!.worldEvents=[{id:'payroll',day:1,until:4}];expect(payWork(c)).toBe(0);const owed=c.life!.salaryHeld;expect(owed).toBeGreaterThan(0);payWork(c);expect(c.life!.salaryHeld).toBe(owed);advanceCalendar(c);advanceCalendar(c);advanceCalendar(c);expect(ch.stats.money).toBe(base+owed);expect(c.life!.salaryHeld).toBe(0);advanceCalendar(c);expect(ch.stats.money).toBe(base+owed);});
it('generates repeatable but varied rosters and contextual topics',()=>{expect(generateWorld(5)).toEqual(generateWorld(5));expect(generateWorld(5).characters.map(x=>x.name)).not.toEqual(generateWorld(6).characters.map(x=>x.name));const c=start(),npc=c.characters.find(x=>x.id==='anya')!;c.life!.officeEncounterDay=c.company!.currentDay;expect(availableTopics(c,npc).some(x=>x.id==='context-dispute')).toBe(true);expect(hasNewTopic(c,npc)).toBe(true);activeCharacter(c).conversations=Object.fromEntries(availableTopics(c,npc).map(x=>[npc.id+':'+x.id,'respond']));expect(hasNewTopic(c,npc)).toBe(false);});
it('applies priority tradeoffs without blocking deterministic task steps',()=>{let c=start();c.company!.currentDay=3;c.life!.queue.forEach(q=>q.urgency=5);c=transition(c,{type:'priority',id:'feature',explained:false}).campaign;expect(c.life!.decisions.communicationFailures).toBe(1);closeWorkDay(c);expect(c.life!.decisions.ignoredQa).toBe(1);expect(c.life!.decisions.ignoredReview).toBe(1);expect(c.meta!.perspectives.development).toContain('feature');expect(c.life!.decisions).not.toEqual(emptyDecisions());});
});

describe('priority work integration',()=>{it('turns a chosen debt priority into real adapter work and restores the exact plan',()=>{let c=start();c.company!.currentDay=3;activeCharacter(c).completedWork=['old-1','old-2'];const act=(a:Parameters<typeof transition>[1])=>{c=transition(c,a).campaign};act({type:'event',id:c.schedule[0].id,choiceId:'plan'});act({type:'priority',id:'debt',explained:true});act({type:'take-task'});let task=c.tasks.find(t=>t.id===c.activeTaskId)!;expect(task.templateId).toBe('priority.debt');act({type:'choose',id:'focused'});act({type:'advance'});act({type:'draft',id:'original'});c=migrateLegacy(JSON.parse(JSON.stringify(c)));act({type:'draft',id:'edge'});act({type:'draft',id:'report'});act({type:'submit'});act({type:'advance'});task=c.tasks.find(t=>t.id===c.activeTaskId)!;act({type:'run'});act({type:'finish-run',taskId:task.id,stepId:'handoff'});act({type:'choose',id:'document'});act({type:'advance'});expect(c.phase).toBe('reward');expect(c.tasks.find(t=>t.id===c.activeTaskId)!.rewarded).toBe(true);const stats={...activeCharacter(c).stats};act({type:'advance'});expect(activeCharacter(c).stats).toEqual(stats);});});
