import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {emptyCampaign,activeCharacter,activeTask,makeSchedule} from './simulation';
import {resolveTaskTemplate} from '../content/scenarios';
import {migrateLegacy} from './store';
import {finishPlaytestTask} from './playtestHelpers';
function start(){let c=transition(emptyCampaign(),{type:'new',name:'Sources',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete activeCharacter(c).firstDay;activeCharacter(c).completedWork=['one','two'];activeCharacter(c).careerNodeId='level-1';const project=c.company!.projects[0],q=c.life!.queue.find(q=>q.id==='bug')!;q.status='selected';q.explained=true;q.projectId=project.id;q.problemId=project.problems.find(p=>p.category==='payment')!.id;c.schedule=makeSchedule(c);c.schedule[0].status='completed';c=transition(c,{type:'take-task'}).campaign;for(const id of ['open-artifact','experiment'])c=transition(c,{type:'technical-action',id}).campaign;return c;}
const progress=(c:ReturnType<typeof start>)=>activeTask(c)!.progress[activeTask(c)!.currentStepId];
describe('measurements with context',()=>{
 it('shows a timed spike and scope; only comparison records the metric observation',()=>{let c=start();const step=resolveTaskTemplate(activeTask(c)!).steps[0],a=step.actionFlow!.actions.find(a=>a.id==='metrics')!;expect(a.artifact!.rows[0].trend!.map(p=>p.value)).toEqual([800,800,2400,2300,2400]);c=transition(c,{type:'artifact-inspect',actionId:'metrics',rowId:'series'}).campaign;expect(progress(c).observations?.metrics).toBeUndefined();expect(transition(c,{type:'artifact-compare',id:'metrics'}).campaign).toEqual(c);c=transition(c,{type:'artifact-inspect',actionId:'metrics',rowId:'scope'}).campaign;c=transition(c,{type:'artifact-compare',id:'metrics'}).campaign;expect(progress(c).observations!.metrics).toBe('story.hypothesis.metrics.result');});
 it('either investigation path still requires both sources for the cross-check',()=>{for(const hypothesis of ['environment','metrics']){let c=start();c=transition(c,{type:'technical-action',id:hypothesis}).campaign;expect(transition(c,{type:'artifact-compare',id:'crosscheck'}).campaign).toEqual(c);c=transition(c,{type:'artifact-inspect',actionId:'crosscheck',rowId:'qa-source'}).campaign;expect(progress(c).observations?.crosscheck).toBeUndefined();c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(progress(c).artifactReadings!.crosscheck).toEqual(['qa-source']);expect(transition(c,{type:'artifact-compare',id:'crosscheck'}).campaign).toEqual(c);c=transition(c,{type:'artifact-inspect',actionId:'crosscheck',rowId:'metrics-source'}).campaign;c=transition(c,{type:'artifact-compare',id:'crosscheck'}).campaign;expect(progress(c).observations!.crosscheck).toBe('story.crosscheck.result');expect(finishPlaytestTask(c).tasks.at(-1)!.rewarded).toBe(true);}});
});
