import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {emptyCampaign,activeCharacter,activeTask,makeSchedule} from './simulation';
import {finishPlaytestTask} from './playtestHelpers';
import {resolveTaskTemplate} from '../content/scenarios';
import {prepareEncounter} from './problemStories';
import {migrateLegacy} from './store';
import {availableTechnicalActions} from './technicalActions';
import {advanceCalendar} from './life';
import type {Campaign} from './types';
function start(){const c=transition(emptyCampaign(),{type:'new',name:'Story',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete activeCharacter(c).firstDay;activeCharacter(c).completedWork=['intro1','intro2'];return c;}
function assign(c:Campaign,category="payment"){const q=c.life!.queue.find(q=>q.id==='bug')!,p=c.company!.projects[0];q.status='selected';q.explained=true;q.projectId=p.id;q.problemId=p.problems.find(p=>p.category===category)!.id;c.phase='office';c.time=540;c.activeTaskId=null;c.schedule=makeSchedule(c);c.schedule[0].status='completed';return transition(c,{type:'take-task'}).campaign;}
const problem=(c:Campaign)=>c.company!.projects[0].problems.find(p=>p.category==='payment')!;
describe('persistent work stories',()=>{
 it('keeps actors, approach, evidence, debt and limitations; a workaround returns changed',()=>{let c=finishPlaytestTask(assign(start()),'limited');const prior=activeTask(c)!.id;expect(problem(c).story!.encounters[0].debtImpact).toBe(2);expect(problem(c).story!.limitations.length).toBeGreaterThan(0);for(let i=0;i<8;i++)advanceCalendar(c);c=assign(c);expect(activeTask(c)!.sceneFamily).toBe('recurrence');expect(activeTask(c)!.encounter!.previousTaskId).toBe(prior);expect(activeTask(c)!.encounter!.contextKeys).toContain('story.environment');c=finishPlaytestTask(c);expect(problem(c).story!.encounters).toHaveLength(2);expect(problem(c).story!.encounters[0].observations.length).toBeGreaterThan(0);expect(problem(c).story!.version).toBe(2);expect(problem(c).story!.limitations).toEqual([]);});
 it('keeps a proper repair and tests a new contract version instead of reviving the old bug',()=>{let c=finishPlaytestTask(assign(start()));expect(problem(c).story!.version).toBe(2);const due=problem(c).paymentCausal!.pending[0].day;while(c.life!.calendarDay<due)advanceCalendar(c);c=assign(c);expect(activeTask(c)!.encounter!.version).toBe(2);expect(activeTask(c)!.encounter!.contextKeys).toContain('story.stable');expect(activeTask(c)!.sceneFamily).toBe('review');});
 it('changes available actions by grade, not only labels',()=>{const c=assign(start(),'interface'),base=resolveTaskTemplate(activeTask(c)!);const structures=[];for(const grade of [0,1,2,3]){activeCharacter(c).careerNodeId='level-'+grade;const task=structuredClone(activeTask(c)!);delete task.scene;prepareEncounter(c,task,base,problem(c));structures.push(resolveTaskTemplate(task).steps.map(s=>s.actionFlow?.actions.map(a=>[a.id,a.next,a.delegates,a.requiresReply])).flat());}expect(new Set(structures.map(s=>JSON.stringify(s))).size).toBe(4);});
 it('does not fabricate seven families from thirty encounters without new world facts',()=>{let c=start();const families=new Set<string>(),graphs=new Set<string>();for(let i=0;i<30;i++){activeCharacter(c).careerNodeId='level-'+Math.min(3,Math.floor(i/8));c=assign(c,'interface');const task=activeTask(c)!;families.add(task.sceneFamily!);graphs.add(JSON.stringify(resolveTaskTemplate(task).steps.map(s=>[s.id,s.actionFlow?.actions.map(a=>[a.id,a.next,a.delegates,a.requiresReply])])));c=finishPlaytestTask(c,i===0?'limited':'shared');}expect(families.size).toBeLessThanOrEqual(5);expect(graphs.size).toBeGreaterThanOrEqual(4);},30000);
 it('saves a pending colleague reply, lets another job run and resumes exact observations',()=>{let c=start();activeCharacter(c).careerNodeId='level-2';c=assign(c,'interface');expect(activeTask(c)!.sceneFamily).toBe('dependency');c=transition(c,{type:'technical-action',id:'request'}).campaign;const id=activeTask(c)!.id;c=transition(c,{type:'pause-task'}).campaign;c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(c.tasks.find(t=>t.id===id)!.paused).toBe(true);expect(c.activeTaskId).toBeNull();const q=c.life!.queue.find(q=>q.id==='feature')!;q.status='selected';q.explained=true;c=transition(c,{type:'take-task'}).campaign;expect(activeTask(c)!.id).not.toBe(id);c=finishPlaytestTask(c);c=transition(c,{type:'reward-close'}).campaign;c=transition(c,{type:'resume-task',id}).campaign;expect(activeTask(c)!.id).toBe(id);const step=resolveTaskTemplate(activeTask(c)!).steps[0],progress=activeTask(c)!.progress[step.id];expect(progress.dependency!.ready).toBe(true);expect(availableTechnicalActions(step,progress).map(a=>a.id)).toContain('reply');expect(availableTechnicalActions(step,progress).map(a=>a.id)).not.toContain('request');expect(progress.observations!.request).toBeTruthy();c=finishPlaytestTask(c);expect(activeTask(c)!.rewarded).toBe(true);});
 it('both plausible hypotheses reveal different evidence, move forward and cannot repeat for rewards',()=>{for(const hypothesis of ['environment','metrics']){let c=start();activeCharacter(c).careerNodeId='level-1';c=assign(c,'interface');for(const id of ['open-artifact','experiment',hypothesis])c=transition(c,{type:'technical-action',id}).campaign;const task=activeTask(c)!,step=resolveTaskTemplate(task).steps[0],progress=task.progress[step.id];expect(progress.observations![hypothesis]).toBe('story.hypothesis.'+hypothesis+'.result');expect(availableTechnicalActions(step,progress).map(a=>a.id)).toEqual(['crosscheck']);expect(transition(c,{type:'technical-action',id:hypothesis}).campaign).toEqual(c);c=finishPlaytestTask(c);expect(activeTask(c)!.rewarded).toBe(true);}});
});
