import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {emptyCampaign,activeCharacter,makeSchedule} from './simulation';
import {closeWorkDay,finishLife,advanceCalendar,decision,ensureLife} from './life';
import {recovery} from './economy';
import {migrateLegacy} from './store';
const start=()=>{const c=transition(emptyCampaign(),{type:'new',name:'Рома',avatarId:'1',professionId:'frontend',seed:1427}).campaign;activeCharacter(c).firstDay!.onboardingCompleted=true;activeCharacter(c).firstDay!.currentOnboardingStep='done';return c;};
describe('stress and recovery balance',()=>{
 it('A: fifteen normal days remain sustainable without drinks',()=>{const c=start(),ch=activeCharacter(c),values=[];for(let i=0;i<15;i++){c.time=1080;closeWorkDay(c);finishLife(c);ch.stats.stress=Math.max(0,ch.stats.stress-recovery(ch).stress);advanceCalendar(c);values.push(ch.stats.stress);}expect(Math.max(...values)).toBeLessThan(45);expect(c.life!.ended).toBeUndefined();console.log('A normal:',values);});
 it('B/C: sustained incidents, deadline pressure and overtime reach danger and burnout',()=>{const c=start(),values=[];for(let i=0;i<10&&!c.life!.ended;i++){c.schedule=[{id:'incident-'+i,type:'incident',status:'pending',key:'ui.incident'}];const incident=transition(c,{type:'event',id:'incident-'+i,choiceId:'rollback'}).campaign;Object.assign(c,incident);const updated=activeCharacter(c);decision(c,'deadlineFailures');c.time=1140;closeWorkDay(c);finishLife(c);values.push(updated.stats.stress);if(!c.life!.ended){updated.stats.stress=Math.max(0,updated.stats.stress-recovery(updated).stress);advanceCalendar(c);}}expect(values.slice(0,7).some(n=>n>=65)).toBe(true);expect(c.life!.ended).toBe('burnout');expect(c.meta!.careers[0].outcome).toBe('burnout');expect(values.length).toBeGreaterThan(1);console.log('B/C overload:',values);});
 it('D: coffee buys breathing space, cannot be spammed and survives reload',()=>{let c=start();activeCharacter(c).stats.stress=91;c=transition(c,{type:'drink'}).campaign;expect(activeCharacter(c).stats.stress).toBe(80);const drink=c.life!.drinkOfTheDay;c=migrateLegacy(JSON.parse(JSON.stringify(c)));c=transition(c,{type:'drink'}).campaign;expect(activeCharacter(c).stats.stress).toBe(76);for(let i=0;i<5;i++)c=transition(c,{type:'drink'}).campaign;expect(activeCharacter(c).stats.stress).toBe(76);expect(c.life!.drinkOfTheDay).toBe(drink);expect(c.life!.coffeeScene).toBe('recovery.third');advanceCalendar(c);expect(c.life!.drinksToday).toBe(0);});
 it('E: leave restores stress, advances the world, preserves the unfinished task and summary',()=>{let c=start();c.schedule=makeSchedule(c);c=transition(c,{type:'event',id:c.schedule[0].id,choiceId:'plan'}).campaign;c=transition(c,{type:'take-task'}).campaign;const task=JSON.stringify(c.tasks);c.phase='home';activeCharacter(c).stats.stress=82;const day=c.life!.calendarDay,maturity=c.company!.projects[0].maturity;c=transition(c,{type:'vacation',days:7}).campaign;expect(activeCharacter(c).stats.stress).toBeLessThan(35);expect(c.life!.calendarDay-day).toBeGreaterThanOrEqual(7);expect(c.company!.projects[0].maturity).toBeGreaterThan(maturity);expect(JSON.stringify(c.tasks)).toBe(task);expect(c.life!.montage!.summary!.length).toBeGreaterThan(1);const restored=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(restored.life!.vacations).toEqual(c.life!.vacations);console.log('E vacation:',82,'→',activeCharacter(c).stats.stress,'elapsed:',c.life!.calendarDay-day);});
 it('old saves retain stress and receive safe recovery defaults',()=>{const c=start();activeCharacter(c).stats.stress=73;delete c.life!.drinksToday;delete c.life!.drinkDay;delete c.life!.drinkOfTheDay;delete c.life!.vacations;ensureLife(c);expect(activeCharacter(c).stats.stress).toBe(73);expect(c.life!.drinksToday).toBe(0);expect(c.life!.vacations).toEqual([]);});
});
