import { rosterNames,personalities } from '../content/roster';
import { tenureRequired } from './life';
import { emptyMeta } from './life';
import type { Campaign,Character,Company,DayEvent,Problem,Project,Task,WorldEvent } from './types';
import { archetypes,npcDefinitions,problemDefinitions,traitIds } from '../content/world';
import { professionById } from '../content/professions';
import { templateById } from '../content/scenarios';
export function seeded(seed:number){let n=seed>>>0;return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
export const clamp=(n:number)=>Math.max(0,Math.min(100,n));
export function makeCharacter(id:string,name:string,avatarId:string,profession:string):Character{return {id,name,avatarId,profession,careerNodeId:professionById[profession].startingNode,skills:{craft:1,debugging:0,communication:1,leadership:0},traits:[traitIds[id.length%4]],relationships:[],careerHistory:[],currentProjectIds:[],playable:true,employed:true,stats:{money:45000,energy:100,stress:15,reputation:0,xp:0},discoveredTerms:[],completedWork:[],milestones:[],scenarioCounts:{}};}
export function generateWorld(seed:number):{company:Company;characters:Character[]}{const random=seeded(seed),a=archetypes[Math.floor(random()*archetypes.length)];const projects:Project[]=[a,archetypes[(archetypes.indexOf(a)+3)%archetypes.length]].map((arch,index)=>({id:`project-${seed}-${index}`,nameKey:arch.nameKey,archetype:arch.id,stack:arch.stack,systems:[{id:'web',name:'Web',dependsOn:['api']},{id:'api',name:'API',dependsOn:['db','payment']},{id:'payment',name:'Payment',dependsOn:['bank']},{id:'db',name:'Database',dependsOn:[]},{id:'bank',name:'Bank adapter',dependsOn:[]}],maturity:arch.process,techDebt:clamp(arch.debt+Math.floor(random()*11)-5),stability:80-Math.floor(random()*20),securityLevel:arch.security,trafficLevel:arch.traffic,features:['checkout','reports'],history:[],problems:problemDefinitions.map((p,i)=>({id:`problem-${seed}-${index}-${i}`,titleKey:p.titleKey,category:p.category,severity:2+Math.floor(random()*3),affectedSystems:p.category==='interface'?['web']:p.category==='access'?['api','db']:['web','api','payment'],rootCause:p.root,discovered:i<2,status:i<2?'planned':'unknown',contributions:[],history:[]}))}));
 const names=[...rosterNames];const characters=npcDefinitions.map(n=>({...makeCharacter(n.id,names.splice(Math.floor(random()*names.length),1)[0],String(Math.floor(random()*24)),n.profession),personality:personalities[Math.floor(random()*personalities.length)],communicationStyle:random()>.5?'brief':'thoughtful',careerNodeId:n.level,playable:false,currentProjectIds:projects.map(p=>p.id)}));
 return {characters,company:{id:`company-${seed}`,nameKey:a.id==='fintech'?'company.bank':a.process>70?'company.scale':'company.craft',seed,archetype:a.id,culture:a.process<40?'fast':a.process>70?'careful':'calm',stage:a.process>70?'established':'growing',employeeIds:characters.map(c=>c.id),projects,reputation:30,stability:projects[0].stability,techDebt:projects[0].techDebt,processMaturity:a.process,incidents:[],history:[],currentDay:1}};}
export function emptyCampaign():Campaign{return {meta:emptyMeta(),life:undefined,schemaVersion:3,company:null,characters:[],activeCharacterId:'',tasks:[],activeTaskId:null,schedule:[],phase:'start',time:540,dayStart:{money:45000,energy:100,stress:15,reputation:0,xp:0},dayWorkStart:0,survey:'unseen',candidateRound:0,saveWarning:false};}
export const activeCharacter=(c:Campaign)=>c.characters.find(x=>x.id===c.activeCharacterId)!;
export const activeTask=(c:Campaign)=>c.tasks.find(x=>x.id===c.activeTaskId);
export function history(c:Campaign,kind:string,key:string,extra:Partial<WorldEvent>={}){const event:WorldEvent={id:`event-${c.company!.currentDay}-${c.company!.history.length}`,day:c.company!.currentDay,kind,key,actorId:c.activeCharacterId,...extra};c.company!.history.push(event);return event;}
export function makeSchedule(c:Campaign):DayEvent[]{const day=c.company!.currentDay;const event=(type:DayEvent['type'],key:string):DayEvent=>({id:`day-${day}-${type}`,type,key,status:'pending'});const list=[event('sync','ui.sync'),event('task','ui.work')];if(day%3===0||c.company!.stability<35||activeTask(c)?.status==='blocked')list.push(event('incident','ui.incident'));if(day%4===0||c.company!.processMaturity>75&&day%2===0)list.push(event('company','ui.companyEvent'));if(day%2===0)list.push(event('career','ui.careerEvent'));if(day>=2&&c.survey==='unseen')list.push(event('survey','ui.surveyTitle'));return list;}
export function plannedTemplateId(c:Campaign){const ch=activeCharacter(c),profession=professionById[ch.profession],node=profession.careers.find(n=>n.id===ch.careerNodeId)!;const ids=Number(node.id.split('-')[1])>=2?['lead-review','lead-plan',...profession.scenarioIds]:profession.scenarioIds;const early=ch.completedWork.length<profession.scenarioIds.length;const firstLeadership=node.leadership?['lead-review','lead-plan'].find(id=>!ch.scenarioCounts[id]):undefined;const scored=ids.map(id=>{const tpl=templateById[id];const related=c.company!.projects.flatMap(p=>p.problems).filter(p=>p.category===tpl.category&&p.status!=='resolved');return {id,count:ch.scenarioCounts[id]??0,priority:Math.max(0,...related.map(p=>p.severity+(p.workaround?3:0)))};}).sort((a,b)=>a.count-b.count||b.priority-a.priority||a.id.localeCompare(b.id));const selected=c.life?.queue.find(q=>q.status==='selected'&&!q.delegatedTo)?.id;const priorityTemplate=!early&&selected?'priority.'+selected:undefined;const templateId=firstLeadership??priorityTemplate??(early?profession.scenarioIds[ch.completedWork.length]:scored[0].id);return templateId;}
export function makeTask(c:Campaign):Task{const ch=activeCharacter(c),templateId=plannedTemplateId(c),template=templateById[templateId];const projects=c.company!.projects;let project=projects.find(p=>ch.currentProjectIds.includes(p.id))??projects[0];let problem:Problem|undefined=project.problems.find(p=>p.category===template.category&&p.status!=='resolved');if(!problem){problem={id:`problem-${project.id}-${c.company!.currentDay}-${project.problems.length}`,titleKey:`problem.${template.category}`,category:template.category,severity:2,affectedSystems:['web','api'],rootCause:'new scenario',discovered:true,status:'planned',contributions:[],history:[]};project.problems.push(problem);}problem.discovered=true;problem.status='in-progress';const id=`task-${c.company!.currentDay}-${c.tasks.length}-${ch.id}`;const blocked=c.company!.stability<35&&c.schedule.some(e=>e.type==='incident'&&e.status==='pending');return {id,templateId,projectId:project.id,problemId:problem.id,characterId:ch.id,status:blocked?'blocked':'active',currentStepId:template.steps[0].id,completedStepIds:[],attemptsByStep:{},taskStartedAtGameTime:c.time,taskElapsedMinutes:0,rewarded:false,legacyActorId:problem.causedBy??problem.history.find(e=>e.actorId!==ch.id)?.actorId,progress:Object.fromEntries(template.steps.map((s,i)=>[s.id,{status:i===0?'active':'locked',draft:[],allocation:{},clicks:0,run:'idle',charged:false}]))};}
export function canPromote(ch:Character,nodeId:string){const profession=professionById[ch.profession],current=profession.careers.find(n=>n.id===ch.careerNodeId),node=profession.careers.find(n=>n.id===nodeId);if(!node||!current?.next.includes(nodeId))return false;const r=node.requirements;return (ch.roleTenure??0)>=tenureRequired(Number(nodeId.split('-')[1]))&&(ch.performanceMilestones??0)>0&&(ch.reviewStage??0)===0&&ch.completedWork.length>=Math.max(4,r.work)&&ch.skills.craft>=r.craft&&ch.stats.reputation>=r.reputation&&ch.skills.communication>=r.communication&&ch.skills.leadership>=r.leadership&&(!r.milestone||ch.milestones.includes(r.milestone));}
export function isLeader(ch:Character){return professionById[ch.profession].careers.find(n=>n.id===ch.careerNodeId)!.leadership;}
export function candidates(c:Campaign){return Object.values(professionById).map((p,i)=>({...makeCharacter(`candidate-${c.company!.seed}-${c.candidateRound}-${p.id}`,['Алекс','Мира','Ника','Ян','Рен','Крис'][i%6],String(i%6),p.id),traits:[traitIds[(i+c.candidateRound)%4]],currentProjectIds:[c.company!.projects[0].id]}));}

