import { describe,it,expect,vi } from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import { transition } from './engine';import { emptyCampaign,activeCharacter } from './simulation';import { migrateLegacy } from './store';import { homeState,recovery } from './economy';
const start=()=>{const c=transition(emptyCampaign(),{type:'new',name:'',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete c.characters.find(n=>n.id===c.activeCharacterId)!.firstDay;return c;};
describe('social, marketplace and profile',()=>{
it('starts without a name, renames without resetting progress and persists',()=>{let c=start();expect(activeCharacter(c).name).toBe('Саша');const day=c.company!.currentDay;c=transition(c,{type:'rename',name:'  Тест  '}).campaign;expect(activeCharacter(migrateLegacy(JSON.parse(JSON.stringify(c)))).name).toBe('Тест');expect(c.company!.currentDay).toBe(day);expect(transition(c,{type:'rename',name:'  '}).campaign).toEqual(c);});
it('validates topics and choices, persists responses and prevents reward farming',()=>{let c=start();expect(transition(c,{type:'conversation',npcId:'anya',topicId:'ilya-work',choiceId:'ask'}).campaign).toEqual(c);const before=activeCharacter(c).skills.communication;c=transition(c,{type:'conversation',npcId:'anya',topicId:'anya-work',choiceId:'ask'}).campaign;expect(activeCharacter(c).skills.communication).toBe(before+1);expect(transition(c,{type:'conversation',npcId:'anya',topicId:'anya-work',choiceId:'share'}).campaign).toEqual(c);c=transition(c,{type:'conversation',npcId:'ilya',topicId:'ilya-work',choiceId:'share'}).campaign;expect(activeCharacter(c).skills.communication).toBe(before+1);expect(activeCharacter(migrateLegacy(JSON.parse(JSON.stringify(c)))).conversations?.['anya:anya-work']).toBe('ask');});
it('orders once, arrives tomorrow, unpacks only at home and keeps the item after reload',()=>{let c=start(),before=activeCharacter(c).stats.money;c=transition(c,{type:'order',itemId:'headphones'}).campaign;expect(activeCharacter(c).stats.money).toBe(before-11000);expect(transition(c,{type:'order',itemId:'headphones'}).campaign).toEqual(c);expect(transition(c,{type:'unpack',itemId:'headphones'}).campaign).toEqual(c);c.phase='home';expect(transition(c,{type:'unpack',itemId:'headphones'}).campaign).toEqual(c);c=transition(c,{type:'sleep'}).campaign;expect(transition(c,{type:'unpack',itemId:'headphones'}).campaign).toEqual(c);c.schedule.forEach(e=>e.status='completed');c=transition(c,{type:'end-day'}).campaign;c=transition(c,{type:'unpack',itemId:'headphones'}).campaign;expect(homeState(activeCharacter(c)).owned).toContain('headphones');expect(recovery(activeCharacter(c)).stress).toBe(7);expect(transition(c,{type:'unpack',itemId:'headphones'}).campaign).toEqual(c);expect(activeCharacter(migrateLegacy(JSON.parse(JSON.stringify(c)))).orders?.[0].received).toBe(true);});
it('rejects unknown items and spending beyond the balance',()=>{let c=start();activeCharacter(c).stats.money=0;expect(transition(c,{type:'order',itemId:'monitor'}).campaign).toEqual(c);expect(transition(c,{type:'order',itemId:'invalid'}).campaign).toEqual(c);});
});
