import { rememberPlayerName } from './playerName';
import { ensureLife,emptyMeta,archiveCareer } from './life';
import type { MetaProgress } from './lifeTypes';
const readMeta=():MetaProgress=>{try{return JSON.parse(localStorage.getItem('voiti-vaiti-meta')??'null')??emptyMeta();}catch{return emptyMeta();}};
const saveMeta=(meta:MetaProgress|undefined)=>{if(meta)try{localStorage.setItem('voiti-vaiti-meta',JSON.stringify(meta));}catch{/* campaign save still retains meta */}};
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { Campaign,Feedback,Task } from './types';
import { transition,type Action } from './engine';
import { emptyCampaign,generateWorld,makeCharacter,makeSchedule,makeTask } from './simulation';
import { templateById } from '../content/scenarios';
import { professionById } from '../content/professions';
type Store=Campaign&{feedback:Feedback[];dispatch:(action:Action)=>void;begin:()=>void;reset:()=>void;clearFeedback:()=>void};
export function snapshot(s:Campaign):Campaign{return Object.fromEntries(Object.keys(emptyCampaign()).map(k=>[k,s[k as keyof Campaign]])) as unknown as Campaign;}
export function migrateLegacy(raw:unknown):Campaign{
 const old=raw as Record<string,unknown>;if(!old||typeof old!=='object')return emptyCampaign();
 if(old.schemaVersion===3&&!old.company)return {...emptyCampaign(),meta:(old.meta as MetaProgress)??readMeta(),phase:old.phase==='create'?'create':'start'};
 if(old.schemaVersion===3&&old.company){const c=old as unknown as Campaign;if(Array.isArray(c.characters)&&c.characters.some(ch=>ch.id===c.activeCharacterId&&professionById[ch.profession])&&Array.isArray(c.tasks)&&c.tasks.every(t=>templateById[t.templateId]))return ensureLife({...emptyCampaign(),...c,meta:c.meta??readMeta()});return emptyCampaign();}
 const people=old.characters as {id:string;name:string;avatarId:string;profession:string}[]|undefined;
 const person=people?.find(p=>p.id===old.activeCharacterId);if(!person)return {...emptyCampaign(),phase:old.gamePhase==='creation'?'create':'start'};
 const c=emptyCampaign(),world=generateWorld(1427),ch=makeCharacter(person.id,person.name,person.avatarId,professionById[person.profession]?person.profession:'frontend');Object.assign(c,world);c.characters.push(ch);c.company!.employeeIds.push(ch.id);c.activeCharacterId=ch.id;ch.currentProjectIds=[c.company!.projects[0].id];Object.assign(ch.stats,old.playerStats??{});const skills=(old.skills??{}) as Record<string,number>;ch.skills={craft:(skills.htmlCss??1)+(skills.javascript??0),debugging:skills.debugging??0,communication:skills.communication??1,leadership:0};c.company!.currentDay=Number(old.currentDay??1);c.time=Number(old.time??540);c.dayStart={...ch.stats};c.schedule=makeSchedule(c);c.schedule.find(e=>e.type==='sync')!.status='completed';
 for(const templateId of (old.completedTasks??[]) as string[]){const t=makeTask(c);const template=templateById[templateId];if(!template)continue;t.templateId=templateId;t.currentStepId=template.steps.at(-1)!.id;t.completedStepIds=template.steps.map(s=>s.id);t.status='completed';t.rewarded=true;t.progress=Object.fromEntries(template.steps.map(s=>[s.id,{status:'completed',draft:[],allocation:{},clicks:2,run:'done',charged:true}]));c.tasks.push(t);ch.completedWork.push(t.id);}
 if(ch.completedWork.length)ch.milestones.push('independent');
 const currentId=String(old.currentTaskId??'FE-1427'),template=templateById[currentId];
 if(old.gamePhase==='task'&&template){const t:Task=makeTask(c);t.templateId=currentId;t.currentStepId=template.steps.some(s=>s.id===old.currentStepId)?String(old.currentStepId):template.steps[0].id;t.taskElapsedMinutes=Number(old.taskElapsedMinutes??0);t.taskStartedAtGameTime=Number(old.taskStartedAtGameTime??c.time);const completed=(old.completedStepIds??[]) as string[];const interaction=(old.interaction??{}) as Record<string,unknown>;t.progress=Object.fromEntries(template.steps.map(s=>{const done=completed.includes(`${currentId}:${s.id}`);return [s.id,{status:done?'completed':s.id===t.currentStepId?'active':'locked',draft:[],allocation:{},clicks:s.id===t.currentStepId?Number(interaction.clicks??0):0,run:s.id===t.currentStepId?(interaction.terminal??interaction.review??'idle') as 'idle'|'running'|'done':'idle',charged:done||((old.chargedReviewIds??[]) as string[]).includes(`${currentId}:${s.id}`),choiceId:s.id===t.currentStepId?String(interaction.choiceId??''):undefined,responseKey:s.id===t.currentStepId&&interaction.choiceId?`response.${currentId}.${s.id}.${interaction.choiceId}`:undefined}];}));t.completedStepIds=template.steps.filter(s=>completed.includes(`${currentId}:${s.id}`)).map(s=>s.id);const attempts=(old.attemptsByStep??{}) as Record<string,number>;t.attemptsByStep=Object.fromEntries(template.steps.map(s=>[s.id,attempts[`${currentId}:${s.id}`]??0]));c.tasks.push(t);c.activeTaskId=t.id;c.phase='office';}
 else if(['home','finished','day-end'].includes(String(old.gamePhase))){c.phase='home';c.schedule.forEach(e=>e.status='completed');}else{c.phase='office';if(ch.completedWork.length>=c.company!.currentDay)c.schedule.find(e=>e.type==='task')!.status='completed';}
 return ensureLife(c);
}
export const useWorld=create<Store>()(persist<Store, [], [], Campaign>((set,get)=>({...emptyCampaign(),meta:readMeta(),feedback:[],dispatch:action=>{const before=snapshot(get());if(action.type==='next-career'){const previous=before.characters.find(c=>c.id===before.activeCharacterId);if(previous)rememberPlayerName(previous.name);}const result=transition(before,action);if(action.type==='rename'||action.type==='onboarding'&&action.name){const current=result.campaign.characters.find(c=>c.id===result.campaign.activeCharacterId);if(current&&(action.type==='rename'||current.firstDay?.currentOnboardingStep!=='arrival'))rememberPlayerName(current.name);}saveMeta(result.campaign.meta);set({...result.campaign,feedback:result.feedback});},begin:()=>{if(get().phase==='start')set({phase:'create'});},reset:()=>{const current=structuredClone(snapshot(get()));const previous=current.characters.find(c=>c.id===current.activeCharacterId);if(previous&&previous.firstDay?.currentOnboardingStep!=='arrival')rememberPlayerName(previous.name);if(current.company&&!current.life?.ended)archiveCareer(current,'quit');const meta=current.meta??readMeta();saveMeta(meta);set({...emptyCampaign(),meta,feedback:[]});},clearFeedback:()=>set({feedback:[]})}),{name:'voiti-vaiti-campaign',version:3,partialize:snapshot,migrate:migrateLegacy,merge:(persisted,current)=>({...current,...migrateLegacy(persisted)}),storage:{getItem:name=>{try{const value=localStorage.getItem(name);return value?JSON.parse(value):null;}catch{return null;}},setItem:(name,value)=>{try{localStorage.setItem(name,JSON.stringify(value));}catch{queueMicrotask(()=>{if(!useWorld.getState().saveWarning)useWorld.setState({saveWarning:true});});}},removeItem:name=>{try{localStorage.removeItem(name);}catch{/* Reset also clears in-memory state. */}}}}));


