import {it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {emptyCampaign,activeCharacter,activeTask} from './simulation';
import {templateById} from '../content/scenarios';
import {availableTechnicalActions} from './technicalActions';
import {migrateLegacy} from './store';
import type {Campaign} from './types';
function at(templateId:string,stepId:string){let c=transition(emptyCampaign(),{type:'new',name:'Test',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete activeCharacter(c).firstDay;c=transition(c,{type:'event',id:c.schedule[0].id,choiceId:'plan'}).campaign;c=transition(c,{type:'take-task'}).campaign;const task=activeTask(c)!;task.templateId=templateId;const template=templateById[templateId];task.progress=Object.fromEntries(template.steps.map(s=>[s.id,{status:s.id===stepId?'active':'locked',draft:[],allocation:{},clicks:0,run:'idle',charged:false}]));task.currentStepId=stepId;return c;}
it('restart yields facts and new actions, cannot repeat or skip, and restores exactly',()=>{let c=at('FE-1451','search');const step=templateById['FE-1451'].steps.find(s=>s.id==='search')!,before=c.time;c=transition(c,{type:'technical-action',id:'restart'}).campaign;expect(c.time-before).toBe(12);expect(activeTask(c)!.progress.search.status).toBe('active');expect(availableTechnicalActions(step,activeTask(c)!.progress.search).map(a=>a.id)).toEqual(['docs','trace','ask']);expect(transition(c,{type:'technical-action',id:'restart'}).campaign).toEqual(c);expect(transition(c,{type:'advance'}).campaign).toEqual(c);c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(activeTask(c)!.progress.search.actionHistory).toEqual(['restart']);c=transition(c,{type:'technical-action',id:'trace'}).campaign;c=transition(c,{type:'technical-action',id:'docs'}).campaign;c=transition(c,{type:'technical-action',id:'example'}).campaign;expect(activeTask(c)!.progress.search.status).toBe('completed');expect(c.life!.decisions.technicalMistakes).toBe(0);});
it('every available technical branch reaches completion without repeating a question',()=>{for(const id of ['FE-1427','FE-1451'])for(const step of templateById[id].steps.filter(s=>s.actionFlow)){expect(step.options).toBeUndefined();const walk=(c:Campaign,depth=0)=>{expect(depth).toBeLessThan(12);const p=activeTask(c)!.progress[step.id];if(p.status==='completed')return;const actions=availableTechnicalActions(step,p);expect(actions.length).toBeGreaterThan(0);for(const action of actions){const next=transition(c,{type:'technical-action',id:action.id}).campaign;expect(activeTask(next)!.progress[step.id].actionHistory).toHaveLength(depth+1);walk(migrateLegacy(JSON.parse(JSON.stringify(next))),depth+1);}};walk(at(id,step.id));}});
it('migrates the exact old failed restart without charging time again',()=>{const c=at('FE-1451','search'),p=activeTask(c)!.progress.search;p.choiceId='restart';p.responseKey='response.FE-1451.search.restart';activeTask(c)!.attemptsByStep.search=1;c.time+=12;const restored=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(restored.time).toBe(c.time);expect(activeTask(restored)!.progress.search.actionHistory).toEqual(['restart']);expect(availableTechnicalActions(templateById['FE-1451'].steps.find(s=>s.id==='search')!,activeTask(restored)!.progress.search).some(a=>a.id==='restart')).toBe(false);});
