import type { Campaign,Character } from './types';
import type { WorkKind } from './lifeTypes';
import { professionById } from '../content/professions';
export function autonomy(ch:Character){const rank=professionById[ch.profession].careers.findIndex(n=>n.id===ch.careerNodeId);return rank>=3?4:rank===2?3:rank===1?2:ch.completedWork.length>=3?1:0;}
export function availableWork(ch:Character):WorkKind[]{return autonomy(ch)===0?['bug']:autonomy(ch)===1?['bug','feature']:autonomy(ch)===2?['bug','feature','review','debt']:['bug','feature','review','debt','support'];}
export const dayPhase=(minutes:number)=>{const clock=((minutes%1440)+1440)%1440;return clock<6*60||clock>=22*60?'night':clock<12*60?'morning':clock<18*60?'day':'evening';};
export function carryQueue(c:Campaign){for(const q of c.life!.queue){if(q.delegatedTo&&q.promisedDay!==undefined&&q.promisedDay<=c.life!.calendarDay){q.status='done';c.company!.stability=Math.min(100,c.company!.stability+2);}if(q.status==='done'){q.status='waiting';q.age=0;q.promisedDay=undefined;q.delegatedTo=undefined;q.urgency=1+((c.company!.seed+c.company!.currentDay+q.minutes)%4);}else{q.age=(q.age??0)+1;q.urgency=Math.min(5,q.urgency+(q.age%2===0?1:0));}}c.life!.routineSummary=undefined;}
export function finishOfficeHours(c:Campaign){const from=c.time,to=Math.max(from,1080+(c.company!.seed+c.company!.currentDay)%18);c.time=to;c.life!.routineSummary={from,to,unfinished:c.tasks.some(t=>t.id===c.activeTaskId&&!t.rewarded)};}
export const workOwner:Record<WorkKind,string>={bug:'max',feature:'oleg',review:'ilya',debt:'sergey',support:'anya'};
export function queuePressure(c:Campaign){const ch=c.characters.find(n=>n.id===c.activeCharacterId)!,l=c.life!;l.obligations??=[];for(const q of l.queue){if(q.status==='done'||(!availableWork(ch).includes(q.id)&&q.promisedDay===undefined))continue;const age=q.age??0;if(age<1)continue;const npcId=workOwner[q.id];if(age>=2){const relationship=ch.relationships.find(r=>r.characterId===npcId);if(relationship)relationship.trust=Math.max(0,relationship.trust-2);if(!l.obligations.some(o=>o.day===l.calendarDay&&o.work===q.id))l.obligations.push({day:l.calendarDay,work:q.id,npcId,kind:q.promisedDay!==undefined?'promise':'waiting'});}if(q.id==='debt')c.company!.techDebt=Math.min(100,c.company!.techDebt+2);if(q.id==='bug'&&(c.company!.seed+l.calendarDay*13)%100<Math.min(65,age*12)){c.company!.stability=Math.max(0,c.company!.stability-5);l.obligations.push({day:l.calendarDay,work:'bug',npcId,kind:'incident'});}}l.obligations=l.obligations.slice(-60);}
