import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition} from './engine';
import {activeTask,activeCharacter,emptyCampaign,makeSchedule} from './simulation';
import {resolveTaskTemplate} from '../content/scenarios';
import {migrateLegacy} from './store';
import {finishPlaytestTask} from './playtestHelpers';
import {roleArtifact} from '../content/workArtifacts';
import {translate} from '../content/localization';
function start(){let c=transition(emptyCampaign(),{type:'new',name:'Evidence',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete activeCharacter(c).firstDay;activeCharacter(c).completedWork=['intro1','intro2'];const q=c.life!.queue.find(q=>q.id==='bug')!,project=c.company!.projects[0];q.status='selected';q.explained=true;q.projectId=project.id;q.problemId=project.problems.find(p=>p.category==='payment')!.id;c.schedule=makeSchedule(c);c.schedule[0].status='completed';c=transition(c,{type:'take-task'}).campaign;return transition(c,{type:'technical-action',id:'inspect'}).campaign;}
const progress=(c:ReturnType<typeof start>)=>activeTask(c)!.progress[activeTask(c)!.currentStepId];
describe('work evidence',()=>{
 it('comparison records observation and advances exactly once',()=>{let c=start();expect(progress(c).observations?.trace).toBeUndefined();expect(transition(c,{type:'artifact-compare',id:'trace'}).campaign).toEqual(c);for(const rowId of ['request.first','request.repeat'])c=transition(c,{type:'artifact-inspect',actionId:'trace',rowId}).campaign;expect(progress(c).observations?.trace).toBeUndefined();c=transition(c,{type:'artifact-compare',id:'trace'}).campaign;expect(progress(c).observations?.trace).toBeTruthy();expect(progress(c).status).toBe('completed');expect(transition(c,{type:'artifact-compare',id:'trace'}).campaign).toEqual(c);expect(finishPlaytestTask(c).tasks.at(-1)!.rewarded).toBe(true);});
 it('irrelevant exploration is harmless and discoveries survive reload',()=>{let c=start();const before=c.time;c=transition(c,{type:'artifact-inspect',actionId:'trace',rowId:'reference.health'}).campaign;expect(c.time).toBe(before);expect(progress(c).status).toBe('active');expect(transition(c,{type:'artifact-inspect',actionId:'trace',rowId:'invented'}).campaign).toEqual(c);c=transition(c,{type:'artifact-inspect',actionId:'trace',rowId:'request.first'}).campaign;c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(progress(c).artifactReadings!.trace).toEqual(['reference.health','request.first']);c=transition(c,{type:'artifact-inspect',actionId:'trace',rowId:'request.repeat'}).campaign;c=transition(c,{type:'artifact-compare',id:'trace'}).campaign;expect(progress(c).status).toBe('completed');});
 it('roles receive relevant artifacts with localized fields',()=>{const kinds=new Set();for(const role of ['frontend','qa','sre','product','designer'])for(const category of ['interface','payment','performance'] as const){const artifact=roleArtifact(role,category,'ui.taskHint')!;kinds.add(artifact.kind);for(const locale of ['ru','en'] as const)for(const key of [artifact.titleKey,artifact.promptKey,...artifact.rows.flatMap(r=>[r.labelKey,r.detailKey])])expect(translate(key,{},locale,'clean')).not.toBe(key);}expect(kinds.size).toBeGreaterThanOrEqual(5);});
 it('first Frontend task exposes source fragments',()=>{const c=transition(emptyCampaign(),{type:'new',name:'Evidence',avatarId:'1',professionId:'frontend',seed:1427}).campaign;delete activeCharacter(c).firstDay;c.schedule=makeSchedule(c);c.schedule[0].status='completed';const next=transition(c,{type:'take-task'}).campaign;expect(resolveTaskTemplate(activeTask(next)!).steps.some(s=>s.actionFlow?.actions.some(a=>a.artifact?.kind==='code'))).toBe(true);});
});
