import {describe,it,expect,vi} from 'vitest';
vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{}});
import {transition,type Action} from './engine';
import {emptyCampaign,activeCharacter,activeTask,makeSchedule} from './simulation';
import {migrateLegacy} from './store';
import {availableTopics} from '../content/contextDialogue';
import {autonomy,availableWork,dayPhase,queuePressure} from './workLoop';
import {recovery} from './economy';
import {templateById} from '../content/scenarios';
const start=()=>transition(emptyCampaign(),{type:'new',name:'Test',avatarId:'1',professionId:'frontend',seed:1427}).campaign;
function established(){const c=start();activeCharacter(c).firstDay!.onboardingCompleted=true;activeCharacter(c).firstDay!.currentOnboardingStep='done';c.company!.currentDay=2;c.schedule=makeSchedule(c);return c;}
describe('work across days',()=>{
 it('processes the review reply and two other choices during onboarding once',()=>{let c=start();const npc=c.characters.find(n=>n.id==='ilya')!;for(const id of ['context-review','context-morning','context-personal']){activeCharacter(c).relationships=[{characterId:npc.id,trust:30}];const topic=availableTopics(c,npc).find(t=>t.id===id)!;expect(topic).toBeDefined();c=transition(c,{type:'conversation',npcId:npc.id,topicId:id,choiceId:topic.choices[0].id}).campaign;expect(activeCharacter(c).conversations![npc.id+':'+id]).toBe(topic.choices[0].id);const before=JSON.stringify(c);expect(JSON.stringify(transition(c,{type:'conversation',npcId:npc.id,topicId:id,choiceId:topic.choices[0].id}).campaign)).toBe(before);}expect(c.life!.queue.find(q=>q.id==='review')!.promisedDay).toBe(2);expect(migrateLegacy(JSON.parse(JSON.stringify(c))).characters).toEqual(c.characters);});
 it('assigns junior work, carries its exact step and reaches evening before home',()=>{let c=established();const act=(a:Action)=>{c=transition(c,a).campaign;};expect(autonomy(activeCharacter(c))).toBe(0);act({type:'event',id:c.schedule[0].id,choiceId:'help'});act({type:'take-task'});act({type:'choose',id:'hero'});act({type:'advance'});const task=structuredClone(activeTask(c)!);act({type:'end-day'});expect(c.phase).toBe('home');expect(c.time).toBeGreaterThanOrEqual(1080);expect(dayPhase(c.time)).toBe('evening');activeCharacter(c).stats.stress=65;act({type:'sleep'});expect(activeCharacter(c).stats.stress).toBeGreaterThan(45);expect(activeTask(c)!.id).toBe(task.id);expect(activeTask(c)!.progress).toEqual(task.progress);expect(activeTask(c)!.currentStepId).toBe(task.currentStepId);c=migrateLegacy(JSON.parse(JSON.stringify(c)));expect(activeTask(c)!.progress).toEqual(task.progress);expect(c.life!.queue.find(q=>q.id==='bug')!.age).toBe(1);});
 it('grows autonomy and makes postponed promises visible to the actual colleague',()=>{const c=established(),ch=activeCharacter(c);ch.completedWork=['1','2','3'];expect(availableWork(ch)).toEqual(['bug','feature']);ch.careerNodeId='level-1';expect(availableWork(ch)).toContain('review');ch.careerNodeId='level-3';expect(autonomy(ch)).toBe(4);const q=c.life!.queue.find(q=>q.id==='review')!;q.age=2;q.promisedDay=1;queuePressure(c);expect(c.life!.obligations!.some(o=>o.work==='review'&&o.kind==='promise')).toBe(true);expect(availableTopics(c,c.characters.find(n=>n.id==='ilya')!).some(t=>t.id.startsWith('obligation-'))).toBe(true);expect(recovery(ch).stress).toBeLessThanOrEqual(12);expect(dayPhase(660)).toBe('morning');expect(dayPhase(120)).toBe('night');});
 it('accepts a noncanonical plan while keeping wrong-file retry',()=>{const c=established();for(const id of ['qa-repeat','devops-deploy','sre-incident','lead-plan','priority.debt']){const plan=templateById[id].steps.find(s=>['planning','incident-response','resource-allocation'].includes(s.type));expect(plan?.resolution).toBe('consequential');}let next=transition(c,{type:'event',id:c.schedule[0].id,choiceId:'plan'}).campaign;next=transition(next,{type:'take-task'}).campaign;next=transition(next,{type:'choose',id:'home'}).campaign;expect(activeTask(next)!.progress.files.status).toBe('active');expect(activeTask(next)!.progress.files.responseKey).toBeTruthy();});
 it('helps once and lets a lead delegate work across days',()=>{let c=established();c=transition(c,{type:'event',id:c.schedule[0].id,choiceId:'plan'}).campaign;activeCharacter(c).careerNodeId='level-3';c=transition(c,{type:'help-work',id:'review'}).campaign;expect(c.life!.queue.find(q=>q.id==='review')!.status).toBe('done');const after=JSON.stringify(c);expect(JSON.stringify(transition(c,{type:'help-work',id:'review'}).campaign)).toBe(after);c=transition(c,{type:'delegate-work',id:'feature',npcId:'oleg'}).campaign;expect(c.life!.queue.find(q=>q.id==='feature')!.delegatedTo).toBe('oleg');c=transition(c,{type:'end-day'}).campaign;expect(c.time).toBeGreaterThanOrEqual(1080);c=transition(c,{type:'sleep'}).campaign;expect(c.life!.queue.find(q=>q.id==='feature')!.status).toBe('waiting');expect(c.life!.queue.find(q=>q.id==='feature')!.delegatedTo).toBeUndefined();});
 it('keeps evidence checks specific and remedy choices consequential',()=>{for(const id of ['backend-api','data-quality','qa-repeat']){const template=templateById[id];expect(template.steps.find(s=>s.id==='resolve')!.resolution).toBe('consequential');expect(template.steps[0].failureKey).toBeTruthy();}});

});
