import '../content/workspaceUx';
import './workspaceUx.css';
import {AppContext} from './AppContext';
import {resolveTaskTemplate} from '../content/scenarios';
import {TaskResult} from './TaskResult';
import { useEffect,useRef,useState } from 'react';
import { AnimatePresence,motion,useIsPresent } from 'framer-motion';
import { Code2,Globe,Terminal,MessageSquare,X,LockKeyhole,Check } from 'lucide-react';
import { useWorld } from '../world/store';
import { activeTask } from '../world/simulation';
import { useI18n } from '../content/localization';
import type { AppId,Step } from '../world/types';
import { StepRenderer } from './Mechanic';
import { Button } from './shared';
const apps=[{id:'ide' as AppId,Icon:Code2},{id:'browser' as AppId,Icon:Globe},{id:'console' as AppId,Icon:Terminal},{id:'chat' as AppId,Icon:MessageSquare}];
export function Laptop({onClose}:{onClose:()=>void}){const present=useIsPresent(),world=useWorld(),{t}=useI18n(),task=activeTask(world),template=task?resolveTaskTemplate(task):undefined,step=template?.steps.find(s=>s.id===task?.currentStepId),[app,setApp]=useState<AppId>(step?.app??'ide'),[view,setView]=useState<Step|null>(null),ref=useRef<HTMLDivElement>(null),contentRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const origin=document.activeElement instanceof HTMLElement?document.activeElement:null;ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const all=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);if(origin?.isConnected)origin.focus({preventScroll:true});};},[onClose]);
 useEffect(()=>{if(step){setView(null);setApp(step.app);}},[step?.id,task?.id]);
 useEffect(()=>{contentRef.current?.scrollTo({top:0});},[step?.id,task?.id,app,view?.id]);
 useEffect(()=>{const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;};},[]);
 return <motion.div className="laptop-backdrop" style={{pointerEvents:present?'auto':'none'}} initial={{backgroundColor:'#17231d00',backdropFilter:'blur(0px)'}} animate={{backgroundColor:'#17231d99',backdropFilter:'blur(8px)'}} exit={{backgroundColor:'#17231d00',backdropFilter:'blur(0px)'}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><motion.div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={t('ui.laptop')} className="laptop-shell" layoutId="player-laptop" transition={{type:'spring',stiffness:280,damping:32}}><div className="laptop-bezel"><i className="camera"/><span>almost.ready</span><button onClick={onClose} aria-label={t('ui.close')}><X size={18}/></button></div><div className="laptop-display"><header className="laptop-menubar"><b>{t('ui.workspace')}</b><span>{template?t(template.titleKey):''}</span></header><div className="laptop-body"><aside className="laptop-apps">{apps.map(({id,Icon})=><button key={id} className={app===id&&!view?'active':''} aria-pressed={app===id&&!view} title={t(step?.app===id?'workspace.currentApp':'workspace.referenceApp')} onClick={()=>{setApp(id);setView(null);}}><Icon size={23}/><span>{t(`ui.${id}`)}</span>{step?.app===id&&<i/>}</button>)}{template&&<div className="laptop-step-list" aria-label={t('workspace.steps')}><p className="laptop-steps-label">{t('workspace.steps')}</p>{template.steps.filter(s=>task!.progress[s.id].status!=='locked').map(s=><button key={s.id} disabled={task!.progress[s.id].status==='locked'} className={s.id===step?.id?'current':''} aria-current={s.id===step?.id?'step':undefined} onClick={()=>{if(s.id===step?.id){setView(null);setApp(s.app);}else setView(s);}}>{task!.progress[s.id].status==='completed'?<Check size={13}/>:task!.progress[s.id].status==='locked'?<LockKeyhole size={12}/>:<i className="live-dot"/>}<span>{t(s.titleKey)}</span></button>)}</div>}</aside><div className="laptop-content" ref={contentRef}><AnimatePresence mode="wait"><motion.div key={view?.id??`${task?.currentStepId}-${app}`} initial={{opacity:0,y:5}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.15}}>{world.phase==='reward'&&task?.rewarded?<TaskResult onClose={onClose}/>:!task||task.rewarded?<div className="empty-app"><Code2 size={42}/><h2>{t('ui.noTask')}</h2></div>:task.status==='blocked'?<div className="empty-app"><LockKeyhole size={40}/><p>{t('ui.taskBlocked')}</p><Button onClick={onClose}>{t('ui.returnOffice')}</Button></div>:view?<><p className="read-only-notice">{t('ui.readOnly')}</p><StepRenderer step={view} readOnly viewProgress={task.progress[view.id]}/></>:step&&app===step.app?<StepRenderer step={step}/>:<AppContext app={app} task={task} onContinue={()=>setApp(step!.app)}/>}</motion.div></AnimatePresence></div></div></div><div className="laptop-chin"><span>{t('ui.brand')}</span></div><div className="laptop-base"><i/></div></motion.div></motion.div>;
}


