import { useState,useEffect } from 'react';
import { useWorld } from '../world/store';
import { activeCharacter } from '../world/simulation';
import { careerRank,tenureRequired,recentIssues } from '../world/life';
import { professionById,professions } from '../content/professions';
import { roleLinks,roleSides,linkKinds } from '../content/life';
import { useI18n } from '../content/localization';
import { Button,Modal,characterName } from './shared';
import type { WorkKind } from '../world/lifeTypes';
export function LifeStatus(){const w=useWorld(),{t,locale}=useI18n(),ch=activeCharacter(w),l=w.life;if(!l)return null;const date=new Date(Date.UTC(2026,0,l.calendarDay));const event=l.worldEvents.at(-1);return <div className="life-status"><span>{date.toLocaleDateString(locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})} · {t('life.days',{days:l.daysAtCompany,months:Math.floor((l.calendarDay-l.roleStartedDay)/30)})}</span>{ch.stats.stress>=70&&<strong role="status">{t('life.warning'+(ch.stats.stress>=95?95:ch.stats.stress>=85?85:70))}</strong>}{event&&event.until>l.calendarDay&&<span title={t('life.event.'+event.id+'.body')}>{t('life.event.'+event.id)} · {t('life.event.'+event.id+'.body')}</span>}{l.salaryHeld>0&&<strong>{t('life.payHeld',{amount:l.salaryHeld})}</strong>}{l.reviewDue&&<strong>{t('life.review')}</strong>}</div>}
export function WorkQueue(){const w=useWorld(),{t}=useI18n(),ch=activeCharacter(w),[chosen,setChosen]=useState<WorkKind|null>(null),l=w.life;if(!l)return null;const selected=l.queue.find(q=>q.status!=='waiting');return <div className="priority-queue"><p className="eyebrow">{t('life.side.'+(roleSides[ch.profession]??'development'))}</p><p>{t('life.side.'+(roleSides[ch.profession]??'development')+'.body')}</p>{selected?<div className="selected-priority"><b>{t('life.selected')}: {t('life.work.'+selected.id)}</b><p>{t('life.work.'+selected.id+'.body')}</p></div>:<><h2>{t('life.queue')}</h2><p>{t('life.queueHint')}</p><div className="queue-items">{l.queue.map(q=><button key={q.id} aria-pressed={chosen===q.id} onClick={()=>setChosen(q.id)}><b>{t('life.work.'+q.id)}</b><small>{t('life.urgency',{value:q.urgency,minutes:q.minutes})}</small></button>)}</div>{chosen&&<><p>{t('life.work.'+chosen+'.body')}</p><Button disabled={l.reviewDue} onClick={()=>w.dispatch({type:'priority',id:chosen,explained:true})}>{t('life.explain')}</Button><Button secondary disabled={l.reviewDue} onClick={()=>w.dispatch({type:'priority',id:chosen,explained:false})}>{t('life.dismiss')}</Button></>}</>}</div>}
export function PerformancePanel(){const w=useWorld(),{t}=useI18n();if(!w.life?.reviewDue)return null;return <div className="performance-panel"><h2>{t('life.review')}</h2><b>{t('life.stage'+Math.min(3,w.life.reviewStage))}</b><p>{t('life.reviewCopy')}</p><ul>{Object.entries(recentIssues(w)).filter(([,n])=>n>0).map(([key,n])=><li key={key}>{t('life.'+key)}: {n}</li>)}</ul><p>{t('life.reviewRecovery')}</p><Button onClick={()=>w.dispatch({type:'performance',accept:true})}>{t('life.mentor')}</Button><Button secondary onClick={()=>w.dispatch({type:'performance',accept:false})}>{t('life.reject')}</Button></div>}
export function CareerPacing(){const w=useWorld(),ch=activeCharacter(w),l=w.life!,{t}=useI18n(),[map,setMap]=useState(false),[ending,setEnding]=useState(false);return <><div className="career-pacing"><p>{t('life.tenure',{days:l.calendarDay-l.roleStartedDay,need:tenureRequired(careerRank(ch)+1)})}</p><p>{ch.milestones.includes('performance')?'✓':'○'} {t('life.reviewMilestone')}</p>{l.reviewStage>0&&<p>{t('life.stage'+Math.min(3,l.reviewStage))} · {t('life.reviewRecovery')}</p>}<div className="life-actions"><Button secondary onClick={()=>setMap(true)}>{t('life.map')}</Button><Button secondary onClick={()=>setEnding(true)}>{t('life.end')}</Button></div></div>{map&&<Modal title={t('life.map')} onClose={()=>setMap(false)}><MetaMap/></Modal>}{ending&&<Modal title={t('life.end')} onClose={()=>setEnding(false)}><p>{t('life.confirmEnd')}</p><Button onClick={()=>{w.dispatch({type:'quit'});setEnding(false);}}>{t('life.end')}</Button></Modal>}</>}
export function MetaMap(){const w=useWorld(),m=w.meta!,{t}=useI18n();return <div className="meta-map"><p>{t('life.terms',{count:m.terms.length})} · {t('life.companies',{count:m.companies.length})}</p><div className="meta-roles">{professions.map(p=><div key={p.id}><b>{m.roles[p.id]?.tasks?'✓':'○'} {t(p.titleKey)}</b><small>{m.roles[p.id]?.tasks?t(p.careers[m.roles[p.id].maxGrade]?.titleKey??p.careers[0].titleKey):t('life.unseen')}</small></div>)}</div><h3>{t('life.map')}</h3>{roleLinks.map(([a,b])=>{const kinds=linkKinds[a+':'+b]??[];const aDone=!!m.perspectives[a]?.some(k=>kinds.includes(k)),bDone=!!m.perspectives[b]?.some(k=>kinds.includes(k));return <div className="meta-link" key={a+b}><b>{aDone?'✓':'○'} {t('life.side.'+a)} ↔ {bDone?'✓':'○'} {t('life.side.'+b)}</b><p>{aDone&&bDone?t('life.understood'):t('life.side.'+(!aDone?a:b)+'.body')}</p></div>})}<h3>{t('life.archive')}</h3>{!m.careers.length&&<p>{t('life.emptyArchive')}</p>}{m.careers.map(r=><article className="archive-record" key={r.characterId}><h3>{r.name.startsWith('roster.')?t(r.name):r.name}</h3><p>{t(professionById[r.profession].titleKey)} · {t(professionById[r.profession].careers.find(n=>n.id===r.maxGrade)!.titleKey)}</p><small>{t('life.record',{days:r.calendarDays,played:r.playedDays,salary:r.maxSalary})}</small><b>{t('life.'+r.outcome)}</b></article>)}</div>}
export function EndedCareer(){const w=useWorld(),{t}=useI18n();return <section className="collection-view world-collection ended-career"><p className="eyebrow">{characterName(activeCharacter(w),t)}</p><h1>{t('life.ended')}</h1><h2>{t('life.'+w.life!.ended)}</h2><p>{t('life.confirmEnd')}</p><Button onClick={()=>w.dispatch({type:'next-career'})}>{t('life.newCareer')}</Button><MetaMap/></section>}
export function RoutinePanel(){const w=useWorld(),{t}=useI18n(),l=w.life!,ch=activeCharacter(w),ready=l.characterPlayedDays-(l.lastMontagePlayedDay??0)>=3;return <div className="routine-panel"><h3>{t('life.montage')}</h3><p>{t('life.montageHint')}</p><Button secondary disabled={w.phase!=='home'||l.reviewDue||!ready||!!l.montage} onClick={()=>w.dispatch({type:'montage'})}>{t('life.montage')}</Button>{!ready&&<small>{t('life.montageLocked')}</small>}<Button secondary disabled={w.phase!=='home'||l.reviewDue||ch.stats.money<5000||!!l.montage} onClick={()=>w.dispatch({type:'vacation'})}>{t('life.vacation')}</Button>{l.montage&&<MontagePlayback/>}</div>}

function MontagePlayback(){const w=useWorld(),{t}=useI18n(),result=w.life!.montage!,[frame,setFrame]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches?result.days:0);useEffect(()=>{if(frame>=result.days)return;const timer=setTimeout(()=>setFrame(n=>n+1),Math.max(90,650-frame*75));return()=>clearTimeout(timer)},[frame,result.days]);return <div className="montage-result" role="status">{frame<result.days?<><p className="routine-animation">{t('life.routine')}</p><h3>{t('ui.day',{day:w.life!.calendarDay-result.days+frame})}</h3><progress max={result.days} value={frame}/><Button secondary onClick={()=>setFrame(result.days)}>{t('ui.skip')}</Button></>:<><h3>{t(result.stop)}</h3><p>{t('life.montageResult',result)}</p><Button onClick={()=>w.dispatch({type:'montage-close'})}>{t('life.continue')}</Button></>}</div>}
