import {CareerReport} from './CareerReport';
import '../content/mastery';
import '../content/recovery';
import '../content/corrections';
import {useWorld} from '../world/store';
import {professionById,professions} from '../content/professions';
import {roleLinks,linkKinds} from '../content/life';
import {useI18n} from '../content/localization';
import {characterName} from './shared';

export function MetaMap(){const w=useWorld(),m=w.meta!,{t}=useI18n();return <div className="meta-map"><p>{t('life.terms',{count:m.terms.length})} · {t('life.companies',{count:m.companies.length})}</p><div className="meta-roles">{professions.map(p=><div key={p.id}><b>{m.roles[p.id]?.tasks||m.perspectives[p.id]?.length?'✓':'○'} {t(p.titleKey)}</b><small>{m.roles[p.id]?.tasks?t(p.careers[m.roles[p.id].maxGrade]?.titleKey??p.careers[0].titleKey):t('life.unseen')}</small></div>)}</div><h3>{t('life.map')}</h3>{roleLinks.map(([a,b])=>{const kinds=linkKinds[a+':'+b]??[];const aDone=!!m.perspectives[a]?.some(k=>kinds.includes(k)),bDone=!!m.perspectives[b]?.some(k=>kinds.includes(k));return <div className="meta-link" key={a+b}><b>{aDone?'✓':'○'} {t('life.side.'+a)} ↔ {bDone?'✓':'○'} {t('life.side.'+b)}</b><p>{aDone&&bDone?t('life.understood'):t('life.side.'+(!aDone?a:b)+'.body')}</p></div>})}<h3>{t('mastery.stories')}</h3>{w.characters.filter(ch=>ch.experience?.length).map(ch=><article key={ch.id}><b>{characterName(ch,t)} · {t(professionById[ch.profession].titleKey)}</b>{ch.experience!.filter(e=>e.taskId).slice(-6).map(e=><p key={e.id}>{t(e.titleKey)} · {t('ui.day',{day:e.day})}</p>)}</article>)}<h3>{t('life.archive')}</h3>{!m.careers.length&&<p>{t('life.emptyArchive')}</p>}{m.careers.map(r=><article className="archive-record" key={r.characterId}><h3>{r.name.startsWith('roster.')?t(r.name):r.name}</h3><p>{t(professionById[r.profession].titleKey)} · {t(professionById[r.profession].careers.find(n=>n.id===r.maxGrade)!.titleKey)}</p><small>{t('life.record',{days:r.calendarDays,played:r.playedDays,salary:r.maxSalary})}</small><p>{t('recovery.months',{months:Math.floor(r.calendarDays/30)})}</p><b>{t('life.'+r.outcome)}</b>{r.experience?.filter(e=>e.taskId).slice(-4).map(e=><p key={e.id}>{t(e.titleKey)}</p>)}{r.report?<details><summary>{t('report.title')}</summary><CareerReport report={r.report} characterId={r.characterId}/></details>:<><p>{t('report.legacy')}</p>{r.majorEvents.slice(-3).map((key,i)=><p key={i}>{t(key)}</p>)}</>}</article>)}</div>}
