import { useEffect,useState } from 'react';
import { useWorld } from '../world/store';
import { activeCharacter,activeTask } from '../world/simulation';
import { careerRank } from '../world/life';
import { hasNewTopic } from '../content/contextDialogue';
import { CharacterAvatar } from '../components/CharacterAvatar';
import { useI18n } from '../content/localization';
import { characterName } from './shared';
export function OfficeSimulation({onTalk}:{onTalk:(id:string)=>void}){const w=useWorld(),{t}=useI18n(),[beat,setBeat]=useState(0),[mode,setMode]=useState<'full'|'reduced'|'hero'>('hero');useEffect(()=>{const update=()=>setMode(innerWidth>=1200?'full':innerWidth>=768?'reduced':'hero');update();addEventListener('resize',update);return()=>removeEventListener('resize',update)},[]);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=setInterval(()=>setBeat(b=>b+1),mode==='full'?7000:mode==='reduced'?14000:30000);return()=>clearInterval(timer)},[mode]);const task=activeTask(w),incident=w.schedule.some(e=>e.type==='incident'&&e.status==='pending'),review=task?.status==='review',qa=task?.status==='qa',phase=beat%6,dispute=!incident&&!review&&phase===3;useEffect(()=>{if(dispute&&w.phase==='office'&&w.life?.officeEncounterDay!==w.company?.currentDay)w.dispatch({type:'office-encounter'});},[dispute,w.phase,w.life?.officeEncounterDay,w.company?.currentDay]);const activity=incident?'officeIncident':review?'officeReview':qa?'officeQa':w.time>=1080?'officeEvening':w.time>=780&&w.time<=840?'officeLunch':dispute?'officeDispute':phase===4?'officeMeeting':'officeWork';const people=w.characters.filter(c=>c.employed&&c.id!==w.activeCharacterId).sort((a,b)=>['anya','ilya','sergey','max','oleg'].indexOf(a.id)-['anya','ilya','sergey','max','oleg'].indexOf(b.id)).slice(0,mode==='hero'?2:mode==='reduced'?3:5);const positions=[[31,30],[70,38],[24,62],[62,65],[48,23]];return <div className={'office-simulation mode-'+mode}><div className="office-activity" role="status">{t('life.'+activity)}</div>{people.map((c,i)=>{let [x,y]=positions[i];if(mode==='full'){if(incident||review||qa){x=20+i*14;y=46+(i%2)*11;}else if(phase===1&&i===2){x=82;y=71;}else if(dispute&&(i===1||i===4)){x=57+i*3;y=27;}else if(phase===4){x=28+i*8;y=30;}}return <button key={c.id} className="office-agent" style={{left:x+'%',top:y+'%',opacity:activity==='officeEvening'&&i>2?.2:1}} onClick={()=>onTalk(c.id)} aria-label={t('ui.talkWith',{name:characterName(c,t)})}><CharacterAvatar id={c.avatarId} size={28}/><span>{characterName(c,t)}{hasNewTopic(w,c)?' •':''}</span></button>})}<div className="office-experience">{t('life.role'+(['Junior','Middle','Senior','Lead'][Math.min(3,careerRank(activeCharacter(w)))]))}</div>{careerRank(activeCharacter(w))>0&&<div className="desk-mementos" aria-hidden="true">{careerRank(activeCharacter(w))>=2?'DEV CONF · ✓':'TODO · ✓'}</div>}</div>}
