import {useState} from 'react';
import {Check} from 'lucide-react';
import {useWorld} from '../world/store';
import {professions} from '../content/professions';
import {useI18n} from '../content/localization';
import {OfficeScene} from '../components/OfficeScene';
import {CharacterAvatar} from '../components/CharacterAvatar';
import {Button,Speech} from './shared';

export function Onboarding(){const w=useWorld(),{t}=useI18n(),[avatar,setAvatar]=useState('0'),[role,setRole]=useState('frontend'),[search,setSearch]=useState(''),[seed,setSeed]=useState('');return <main className={`world-onboarding ${w.phase==='create'?'creating':''}`}><section><p className="eyebrow"><i className="live-dot"/>{t('ui.gameLabel')}</p>{w.phase==='start'?<><h1 className="world-title">{t('ui.brand').split(' ').map((x,i)=><span key={i}>{x}</span>)}</h1><h2>{t('ui.tagline')}</h2><p className="start-copy">{t('ui.startCopy')}</p><Button onClick={w.begin}>{t('ui.enter')}</Button><p className="fine-print">{t('ui.introNote')}</p></>:<><h1>{t('ui.create')}</h1><div className="creation-row"><label>{t('ui.seed')}<input type="number" value={seed} placeholder="1427" onChange={e=>setSeed(e.target.value)}/></label></div><div className="world-avatars" aria-label={t('ui.avatar')}>{Array.from({length:24},(_,i)=><button key={i} aria-pressed={avatar===String(i)} onClick={()=>setAvatar(String(i))}><CharacterAvatar id={String(i)} size={43}/></button>)}</div><h2>{t('ui.profession')}</h2><input className="role-search" aria-label={t('ui.searchRoles')} placeholder={t('ui.searchRoles')} value={search} onChange={e=>setSearch(e.target.value)}/><div className="world-role-grid">{professions.filter(p=>`${t(p.titleKey)} ${t(p.descriptionKey)}`.toLowerCase().includes(search.toLowerCase())).map(p=><button key={p.id} className={role===p.id?'selected':''} onClick={()=>setRole(p.id)}><b>{t(p.titleKey)}</b><small>{t(p.descriptionKey)}</small>{role===p.id&&<Check size={16}/>}</button>)}</div><Button onClick={()=>w.dispatch({type:'new',name:t('first.provisional'),avatarId:avatar,professionId:role,seed:seed?Number(seed):crypto.getRandomValues(new Uint32Array(1))[0]})}>{t('ui.workStart')}</Button></>}</section><aside><OfficeScene hero/><div className="onboarding-sticky"><Speech>{t('npc.sergey.line')}</Speech></div><p className="fine-print">{t('ui.introNote')}</p></aside></main>}
