import '../content/responsibility';
import {DelegationResults} from './DelegationResults';
import {absenceObligations,type VacationArrangements} from '../world/vacation';
import {handoffCandidate} from '../world/responsibility';
import {characterName} from './shared';
import '../content/mastery';
import '../content/recovery';
import '../content/corrections';
import {useState,useEffect} from 'react';
import {useWorld} from '../world/store';
import {activeCharacter} from '../world/simulation';
import {useI18n} from '../content/localization';
import {Button,Modal} from './shared';

export function RoutinePanel(){const w=useWorld(),{t}=useI18n(),l=w.life!,ch=activeCharacter(w),[leave,setLeave]=useState<3|7|14|null>(null),[arrangements,setArrangements]=useState<VacationArrangements>({}),ready=l.characterPlayedDays-(l.lastMontagePlayedDay??0)>=3;return <div className="routine-panel"><h3>{t('life.montage')}</h3><p>{t('life.montageHint')}</p><Button secondary disabled={w.phase!=='home'||w.tasks.some(t=>t.id===w.activeTaskId&&!t.rewarded)||l.reviewDue||!ready||!!l.montage} onClick={()=>w.dispatch({type:'montage'})}>{t('life.montage')}</Button>{!ready&&<small>{t('life.montageLocked')}</small>}<p>{t('recovery.vacationHint')}</p>{ch.stats.stress>=65&&<p>{t('recovery.home')}</p>}{([3,7,14] as const).map(days=><Button key={days} secondary disabled={w.phase!=='home'||!!l.montage} onClick={()=>{setArrangements({});setLeave(days);}}>{t('recovery.vacation',{days})}</Button>)}<DelegationResults/>{leave&&<Modal title={t('absence.title')} onClose={()=>setLeave(null)}><p>{t('absence.hint')}</p>{absenceObligations(w).filter(q=>!q.delegatedTo).map(q=>{const reserved=Object.entries(arrangements).filter(([id,a])=>id!==q.id&&typeof a==='object').map(([,a])=>(a as {npcId:string}).npcId),npc=handoffCandidate(w,q,reserved),arrangement=arrangements[q.id],value=typeof arrangement==='object'?'handoff:'+arrangement.npcId:arrangement??'ignore',canPostpone=q.expectation&&!q.expectation.extensionUsed&&q.urgency<4&&q.expectation.state!=='escalated';return <div className="world-card" key={q.id}><label>{t('life.work.'+q.id)}<select aria-label={t('life.work.'+q.id)} value={value} onChange={e=>{const value=e.target.value;setArrangements(a=>({...a,[q.id]:value.startsWith('handoff:')?{kind:'handoff',npcId:value.slice(8)}:value as 'ignore'|'postpone'}));}}><option value="ignore">{t('absence.ignore')}</option>{npc&&<option value={"handoff:"+npc.id}>{t('absence.handoff',{name:characterName(npc,t)})}</option>}{canPostpone&&<option value="postpone">{t('absence.postpone')}</option>}</select></label>{!canPostpone&&<small>{t('absence.limits')}</small>}</div>;})}<Button onClick={()=>{w.dispatch({type:'vacation',days:leave,arrangements});setLeave(null);}}>{t('absence.start',{days:leave})}</Button></Modal>}{l.montage&&<MontagePlayback/>}</div>}

function MontagePlayback(){const w=useWorld(),{t}=useI18n(),result=w.life!.montage!,[frame,setFrame]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches?result.days:0);useEffect(()=>{if(frame>=result.days)return;const timer=setTimeout(()=>setFrame(n=>n+1),Math.max(90,650-frame*75));return()=>clearTimeout(timer)},[frame,result.days]);return <Modal title={t('life.montage')} onClose={()=>w.dispatch({type:'montage-close'})}><div className="montage-result" role="status">{frame<result.days?<><p className="routine-animation">{t('life.routine')}</p><h3>{t('ui.day',{day:w.life!.calendarDay-result.days+frame})}</h3><progress max={result.days} value={frame}/><Button secondary onClick={()=>setFrame(result.days)}>{t('ui.skip')}</Button></>:<><h3>{t(result.stop)}</h3><p>{t('life.montageResult',{days:result.days,income:result.income,expenses:result.expenses})}</p>{result.summary?.filter(k=>k!==result.stop).map(k=><p key={k}>{t(k)}</p>)}<Button onClick={()=>w.dispatch({type:'montage-close'})}>{t('life.continue')}</Button></>}</div></Modal>}
