import {useWorld} from '../world/store';
import {activeCharacter} from '../world/simulation';
import {glossary} from '../content/world';
import {text,useI18n} from '../content/localization';
import {professionById} from '../content/professions';
import {promotionChecks} from '../world/mastery';
import '../content/mastery';
import '../content/promotion';
import {Hammer,Bug,MessagesSquare,Compass,BookOpen,Route,Check,ArrowRight,GraduationCap} from 'lucide-react';
import type {Skill} from '../world/types';
import './skills.css';
const axes=[{id:'craft',Icon:Hammer,ru:'Создавай и проверяй результат своей работы.',en:'Build and check the result of your work.'},{id:'debugging',Icon:Bug,ru:'Сопоставляй наблюдения и проверяй причины сбоя.',en:'Compare observations and investigate causes.'},{id:'communication',Icon:MessagesSquare,ru:'Уточняй ожидания, проси помощь и передавай результат.',en:'Clarify expectations, ask for help and hand off results.'},{id:'leadership',Icon:Compass,ru:'Выбирай приоритеты, делегируй и отвечай за последствия.',en:'Prioritize, delegate and own consequences.'}] as const;
axes.forEach(a=>text('skillMap.'+a.id,a.ru,a.en));
[['relative','Длина полос показывает соотношение твоих навыков, а не предел уровня.','Bar lengths show your relative strengths, not a maximum level.'],['intro','Опыт складывается из того, что ты делаешь, проверяешь и обсуждаешь.','Experience grows through what you do, check and discuss.'],['profile','Твой рабочий профиль','Your work profile'],['practice','Как развивать','How to develop'],['road','Ближайшая ступень','Next milestone'],['roadHelp','Для роста важны реальные рабочие ситуации, а не только числа навыков.','Growth depends on real work experience, not just skill numbers.'],['done','Подтверждено','Confirmed'],['plan','В план развития','Development plan'],['loop','Как работа превращается в опыт','How work becomes experience'],['see','Наблюдай','Observe'],['try','Действуй','Act'],['check','Проверяй','Verify'],['share','Обсуждай','Discuss'],['knowledge','Словарь из твоих историй','Terms from your stories'],['noNext','Ты на вершине этой ветки. Продолжай развивать команду и накапливать опыт.','You reached the top of this branch. Keep developing the team and gaining experience.']].forEach(([id,ru,en])=>text('skillMap.'+id,ru,en));
text('skillMap.sections','Разделы навыков','Skill sections');
text('skillMap.jumpProfile','Профиль','Profile');
text('skillMap.jumpRoad','План роста','Growth plan');
text('skillMap.jumpTerms','Словарь','Glossary');
export function Skills(){
 const ch=useWorld(activeCharacter),{t}=useI18n(),role=professionById[ch.profession],node=role.careers.find(n=>n.id===ch.careerNodeId)!,scale=Math.max(1,...Object.values(ch.skills)),terms=glossary.filter(term=>ch.discoveredTerms.includes(term.id));
 const jump=(id:string)=>{const target=document.getElementById(id);target?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});target?.focus({preventScroll:true});};
 return <section className="collection-view world-collection skill-map"><header className="skill-map-heading"><span className="skill-map-emblem"><GraduationCap size={30}/></span><div><p className="eyebrow">{t(role.titleKey)}</p><h1>{t('ui.skills')}</h1><p>{t('skillMap.intro')}</p></div></header><nav className="skill-section-nav" aria-label={t('skillMap.sections')}>{[{id:'skill-profile',Icon:Hammer,key:'jumpProfile'},{id:'skill-road',Icon:Route,key:'jumpRoad'},{id:'skill-terms',Icon:BookOpen,key:'jumpTerms'}].map(({id,Icon,key})=><button key={id} onClick={()=>jump(id)}><Icon size={16}/>{t('skillMap.'+key)}</button>)}</nav>
 <div className="skill-map-overview" id="skill-profile" tabIndex={-1}><article className="skill-profile"><h2>{t('skillMap.profile')}</h2><p>{t(node.titleKey)}</p><div className="skill-bars">{axes.map(({id,Icon})=><div key={id}><Icon size={19}/><span>{t('ui.'+id)}</span><b>{ch.skills[id]}</b><div className="skill-bar"><i style={{width:`${ch.skills[id]/scale*100}%`}}/></div></div>)}</div><small>{t('skillMap.relative')}</small></article><div className="skill-practice-grid">{axes.map(({id,Icon})=><article key={id} className={'skill-practice skill-'+id}><span className="skill-icon"><Icon size={24}/></span><div><small>{t('ui.level',{value:ch.skills[id as Skill]})}</small><h2>{t('ui.'+id)}</h2><p>{t('skillMap.'+id)}</p></div></article>)}</div></div>
 <section className="skill-work-cycle"><h2>{t('skillMap.loop')}</h2><ol>{['see','try','check','share'].map((id,i)=><li key={id}><span>{i+1}</span><b>{t('skillMap.'+id)}</b>{i<3&&<ArrowRight size={18}/>}</li>)}</ol></section>
 <section className="skill-roadmap" id="skill-road" tabIndex={-1}><div className="skill-section-title"><Route size={23}/><h2>{t('skillMap.road')}</h2></div><p>{t('skillMap.roadHelp')}</p>{!node.next.length&&<p>{t('skillMap.noNext')}</p>}{node.next.map(id=>{const next=role.careers.find(n=>n.id===id)!,checks=promotionChecks(ch,id);return <article className="skill-next" key={id}><h3>{t(node.titleKey)} <ArrowRight size={17}/> {t(next.titleKey)}</h3><ol>{checks.map(c=><li key={c.key} className={c.met?'met':''}><span className="skill-road-dot">{c.met?<Check size={16}/>:<Compass size={16}/>}</span><div><b>{t(c.key)}</b>{!c.met&&c.key.startsWith('mastery.')&&<p>{t(c.key.replace('mastery.','mastery.hint.'))}</p>}</div><span className="skill-road-count">{c.key.startsWith('mastery.')?`${c.current} / ${c.required}`:t('skillMap.'+(c.met?'done':'plan'))}</span></li>)}</ol></article>})}</section>
 <section className="skill-knowledge" id="skill-terms" tabIndex={-1}><div className="skill-section-title"><BookOpen size={23}/><h2>{t('skillMap.knowledge')}</h2><span>{terms.length}</span></div>{!terms.length&&<p>{t('ui.termsEmpty')}</p>}<div className="skill-term-grid">{terms.map(term=><details key={term.id}><summary>{t(term.titleKey)}</summary><p>{t(term.explanationKey)}</p>{ch.termMemories?.[term.id]&&<div className="skill-memory"><small>{t('first.memory',{day:ch.termMemories[term.id].discoveredAt})}</small><p>«{ch.termMemories[term.id].firstSeenContext}»</p></div>}</details>)}</div></section></section>;
}
