import './spaces.css';
import '../content/workspaceUx';
import {hasNewTopic,availableTopics} from '../content/contextDialogue';
import {Conversation} from './Conversation';
import {useState} from 'react';
import {useWorld} from '../world/store';
import {activeCharacter} from '../world/simulation';
import {professionById} from '../content/professions';
import {text,useI18n} from '../content/localization';
import {CharacterAvatar} from '../components/CharacterAvatar';
import {Button,characterName} from './shared';
import {Users,MessagesSquare,Code2,Palette,ShieldCheck,Compass,HeartHandshake,ArrowUpRight,Sparkles,Search} from 'lucide-react';
import './team.css';
[['search','Имя или профессия','Name or profession'],['all','Все коллеги','Everyone'],['fresh','Новые темы','New topics'],['nothing','Никого не нашли. Попробуй другое имя или сбрось фильтры.','No matches. Try another name or reset filters.'],['reset','Сбросить','Reset'],['discuss','Можно обсудить','You can discuss'],['intro','Разные роли. Общая работа.','Different roles. Shared work.'],['help','Здесь можно уточнить задачу, попросить помощь и узнать другую сторону работы.','Clarify a task, ask for help and discover another side of the work.'],['people','Коллег в команде','Teammates'],['topics','Есть о чём поговорить','Something to discuss'],['new','Новая тема','New topic'],['trust','Доверие','Trust'],['trustHelp','Растёт и меняется после совместной работы и разговоров.','Changes through shared work and conversations.'],['empty','Сначала познакомься с коллегами на рабочем экране.','Meet your colleagues in the work screen first.']].forEach(([id,ru,en])=>text('teamView.'+id,ru,en));
function appearance(family:string){if(['design','research'].includes(family))return {Icon:Palette,tone:'design'};if(family==='qa')return {Icon:ShieldCheck,tone:'quality'};if(['product','analysis'].includes(family))return {Icon:Compass,tone:'product'};return {Icon:Code2,tone:'engineering'};}
export function Team(){
 const w=useWorld(),ch=activeCharacter(w),{t}=useI18n(),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[onlyNew,setOnlyNew]=useState(false),[profession,setProfession]=useState('all'),[initialTopic,setInitialTopic]=useState<string|undefined>();
 const people=w.characters.filter(c=>c.id!==ch.id&&c.employed&&(!ch.firstDay||ch.firstDay.onboardingCompleted||ch.firstDay.introducedNpcIds.includes(c.id))),topics=people.filter(c=>hasNewTopic(w,c)).length;
 const visible=people.filter(c=>(!onlyNew||hasNewTopic(w,c))&&(profession==='all'||c.profession===profession)&&[characterName(c,t),t(professionById[c.profession].titleKey),t(professionById[c.profession].careers.find(n=>n.id===c.careerNodeId)?.titleKey??'')].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 return <section className="collection-view world-collection team-view"><header className="team-banner"><div className="team-banner-copy"><p className="eyebrow">{t(w.company!.nameKey)}</p><h1>{t('ui.team')}</h1><h2>{t('teamView.intro')}</h2><p>{t('teamView.help')}</p><div className="team-banner-stats"><span><Users size={17}/><b>{people.length}</b> {t('teamView.people')}</span><span><MessagesSquare size={17}/><b>{topics}</b> {t('teamView.topics')}</span></div></div><div className="team-banner-people" aria-hidden="true">{people.slice(0,5).map(c=><CharacterAvatar key={c.id} id={c.avatarId} size={72}/>)}<HeartHandshake className="team-banner-symbol" size={96}/></div></header>
 {!people.length&&<p>{t('teamView.empty')}</p>}<div className="team-tools"><label className="team-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('teamView.search')} aria-label={t('teamView.search')}/></label><select value={profession} onChange={e=>setProfession(e.target.value)} aria-label={t('workspace.roleFilter')}><option value="all">{t('teamView.all')}</option>{[...new Set(people.map(c=>c.profession))].map(id=><option key={id} value={id}>{t(professionById[id].titleKey)}</option>)}</select><button className="world-secondary" aria-pressed={onlyNew} onClick={()=>setOnlyNew(!onlyNew)}><Sparkles size={15}/> {t('teamView.fresh')} · {topics}</button></div>{!!people.length&&!visible.length&&<div className="team-empty"><p>{t('teamView.nothing')}</p><button className="world-secondary" onClick={()=>{setQuery('');setProfession('all');setOnlyNew(false);}}>{t('teamView.reset')}</button></div>}<div className="team-roster">{visible.map(c=>{const role=professionById[c.profession],{Icon,tone}=appearance(role.family),trust=ch.relationships.find(r=>r.characterId===c.id)?.trust??20,fresh=hasNewTopic(w,c);return <article className={'team-member tone-'+tone} key={c.id}><div className="team-member-cover"><Icon className="team-cover-symbol" size={94}/><div className="team-member-portrait"><CharacterAvatar id={c.avatarId} size={84}/><span><Icon size={17}/></span></div>{fresh&&<span className="team-new-topic"><Sparkles size={12}/>{t('teamView.new')}</span>}</div><div className="team-member-body"><h2>{characterName(c,t)}</h2><p className="team-member-role">{t(role.careers.find(n=>n.id===c.careerNodeId)?.titleKey??role.titleKey)}</p><p className="team-member-purpose">{t(role.descriptionKey)}</p><div className="team-topic-preview"><small>{t('teamView.discuss')}</small>{availableTopics(w,c).filter(topic=>!ch.conversations?.[c.id+':'+topic.id]).slice(0,2).map(topic=><button key={topic.id} onClick={()=>{setInitialTopic(topic.id);setSelected(c.id);}}>{t(topic.titleKey)}<ArrowUpRight size={13}/></button>)}</div>{c.personality&&<span className="team-personality">{t('roster.'+c.personality)}</span>}{c.completedWork.length>0&&<p className="team-former">{t('ui.formerHero')} · {c.completedWork.length} {t('ui.tasksDone').toLowerCase()}</p>}<div className="team-trust"><div><HeartHandshake size={15}/><span>{t('teamView.trust')}</span><b>{trust}</b></div><div className="team-trust-track" aria-hidden="true"><i style={{width:`${Math.max(0,Math.min(100,trust))}%`}}/></div><small>{t('teamView.trustHelp')}</small></div><Button secondary onClick={()=>{setInitialTopic(undefined);setSelected(c.id);}}>{t('ui.talk')}<ArrowUpRight size={17}/></Button></div></article>})}</div>{selected&&<Conversation key={selected} initialTopicId={initialTopic} npcId={selected} onClose={()=>setSelected(null)}/>}</section>;
}
