import type {RoleLens} from './roleLenses';
export const additionalRoleLenses:RoleLens[]=[
 {id:'mobile',app:'console',contribution:'repair',inspect:['Повторить действие на устройстве и записать переходы экрана','Repeat the action on a device and record screen transitions'],trace:['Сопоставить состояние экрана, очередь отправки и ответ сервера','Compare screen state, the send queue and server response'],ask:['Повторно отправить сохранённое действие после возвращения сети','Resend the saved action after connectivity returns'],missing:['Сеть вернулась, но приложение отправило сохранённое действие ещё раз. Повторный успех не доказывает, что результат один. Посмотри очередь и состояние операции.','Connectivity returned, but the app sent the stored action again. Another successful response does not prove there is only one result. Inspect the queue and operation state.'],fast:['Остановить повторную отправку в затронутом экране','Stop resubmission on the affected screen'],care:['Согласовать восстановление состояния и очередь отправки','Align state restoration and the send queue'],check:['Повторить переход между экранами и потерю сети','Repeat screen transitions and loss of connectivity'],facts:{
 interface:['После поворота экран использует старые размеры. После возврата из фона кнопка остаётся за краем: обновление состояния пропущено.','After rotation the screen uses old dimensions. On returning from the background the button stays outside the screen: a state update was missed.'],
 payment:['Первое действие сохранено в очереди. При возвращении сети экран создаёт новое, а очередь отправляет старое: у одной попытки появляются две операции.','The first action was stored in the queue. When connectivity returns the screen creates a new one while the queue sends the old one: one attempt creates two operations.'],
 performance:['Сервер отвечает быстро. При возврате из фона приложение снова собирает весь список на устройстве, поэтому экран долго не реагирует.','The server responds quickly. Returning from the background rebuilds the entire list on the device, leaving the screen unresponsive.']
 },observations:{inspect:['На устройстве случай повторился. Сохранил последовательность экранов и состояние сети; теперь сравни их с журналом отправки.','The case reproduced on the device. Screen sequence and connectivity were recorded; compare them with the send log.'],fast:['На этом экране повтор остановлен. Остались возврат из фона и очередь сохранённых действий — проверь их отдельно.','Repeating was stopped on this screen. Background restoration and queued actions still need a separate check.'],care:['Экран и очередь теперь восстанавливают одну и ту же операцию. Проверь переходы, поворот и потерю сети.','The screen and queue now restore the same operation. Test transitions, rotation and lost connectivity.'],limited:['Затронутый экран проходит проверку. Другой экран ещё отправляет старое действие после восстановления сети; ограничение передано команде.','The affected screen passes. Another screen still sends an old action when connectivity returns; the limitation was handed to the team.'],shared:['Проверены поворот, возврат из фона и повтор после восстановления сети. Приложение сохраняет состояние и не создаёт лишний результат.','Rotation, background restoration and retries after connectivity returns were checked. The app preserves state without producing extra results.']}},
 {id:'support',app:'chat',contribution:'discovery',inspect:['Уточнить время, устройство и шаги без личных данных','Ask for the time, device and steps without personal data'],trace:['Сопоставить обращение с журналом и областью сбоя','Match the report with logs and the affected scope'],ask:['Попросить пароль, чтобы войти за пользователя','Ask for a password to sign in as the user'],missing:['Коллега остановил запрос: пароль нельзя передавать поддержке. Для разбора достаточно времени, шагов и номера обращения. Попроси безопасные данные и продолжи проверку.','A colleague stopped the request: passwords must not be shared with support. Time, steps and a report identifier are enough. Ask for safe evidence and continue.'],fast:['Дать проверенный временный путь и отметить ограничение','Provide a verified temporary route and record its limitation'],care:['Передать воспроизводимый случай владельцу и согласовать ответ','Hand a reproducible case to the owner and agree on a response'],check:['Вернуться к пользователю и проверить, удалось ли закончить действие','Return to the user and check whether the action could be completed'],facts:{
 interface:['Обращения приходят с узких экранов после поворота устройства. Пароль не нужен: последовательность шагов повторяет сбой на тестовом аккаунте.','Reports come from narrow screens after rotation. No password is needed: the steps reproduce the failure on a test account.'],
 payment:['У пользователя две операции после одного ожидания. Номера обращений связаны с повтором на медленной сети; повторная оплата проблему усугубит.','The user has two operations after one wait. Report identifiers link the issue to retries on a slow network; another payment would worsen it.'],
 performance:['Люди с большими списками ждут после релиза, а маленькие списки открываются быстро. Собраны время, объём и версия для владельца сервиса.','People with large lists wait after the release while small lists load quickly. Time, volume and version were collected for the service owner.']
 },observations:{inspect:['Пользователь прислал время, устройство и шаги. Секретов в обращении нет. Теперь найди соответствующую операцию и проверь, кто ещё затронут.','The user sent the time, device and steps without secrets. Find the matching operation and check who else is affected.'],fast:['Пользователь получил обход с указанными границами. Не закрывай обращение на основании отправленной инструкции: проверь результат.','The user received a workaround and its boundaries. Sending instructions is not enough to close the report: verify the outcome.'],care:['Владелец получил воспроизводимый случай и сообщил следующий шаг. Ты ведёшь обращение, а исправление выполняет профильная команда.','The owner received a reproducible case and supplied the next step. You own the report; the specialist team handles the fix.'],limited:['Пользователь закончил действие через обход. Причина остаётся у владельца; соседние обращения нельзя закрыть тем же обещанием.','The user completed the action through the workaround. The cause remains with the owner; neighboring reports cannot be closed with the same promise.'],shared:['Пользователь и владелец подтвердили результат в исходном и соседнем случае. Поддержка передала проверенные данные и ответ людям, а не написала исправление за команду.','The user and owner confirmed the original and neighboring cases. Support provided verified evidence and a response, without writing the fix for the team.']}}
];
