import {text} from './localization';
const rows=[
 ['title','Твоя история в компании','Your story at the company'],
 ['timeline','Как развивалась карьера','How the career unfolded'],
 ['decisions','Решения и их продолжение','Decisions and what followed'],
 ['patterns','Что повторялось в твоих действиях','Patterns in your actions'],
 ['stats','Карьера в числах','The career in numbers'],
 ['emptyPatterns','Пока мало повторяющихся действий для выводов.','There are too few repeated actions to draw conclusions.'],
 ['legacy','Этот архив создан до появления подробных отчётов. Сохранены прежние итоги; недостающие события не восстановлены догадками.','This archive predates detailed reports. Original results remain; missing events have not been invented.'],
 ['sources','Записей в основе: {count}','Evidence: {count} history records'],
 ['arrival','День {day}: начало работы.','Day {day}: work began.'],
 ['promotion','День {day}: новая роль.','Day {day}: a new role.'],
 ['temporary','День {day}: выбран временный результат.','Day {day}: a temporary result was chosen.'],
 ['return','День {day}: прежнее решение получило продолжение.','Day {day}: an earlier decision had a follow-up.'],
 ['absence','День {day}: обязательства остались без согласованного переноса. Всего таких эпизодов: {count}.','Day {day}: obligations lacked an agreed postponement. Recorded episodes: {count}.'],
 ['vacationPath','За {days} календарных дней завершено {tasks} основных задач. Отпусков: {count}, запрошено {away} рабочих дней отдыха.','Over {days} calendar days, {tasks} main tasks were completed. Leave periods: {count}, requested working days off: {away}.'],
 ['mentor','День {day}: завершена помощь с проверкой и границами работы.','Day {day}: support with verification and work boundaries was completed.'],
 ['finished','День {day}: этот карьерный этап закончился.','Day {day}: this career chapter ended.'],
 ['end.fired','Сотрудничество прекращено после обсуждений результатов работы.','Employment ended after performance discussions.'],
 ['end.burnout','Нагрузка дошла до предела: продолжать работу стало невозможно.','Stress reached the limit and continuing work became impossible.'],
 ['end.quit','Ты решил завершить эту карьеру.','You chose to end this career.'],
 ['end.changed_role','Этап закончился переходом в другую профессию.','This chapter ended with a move to another profession.'],
 ['end.changed_company','Этап закончился сменой компании.','This chapter ended with a company change.'],
 ['end.hired_successor','Ты передал место нового героя следующему сотруднику и остался частью мира.','You handed the next playable chapter to a new colleague and remained part of the world.'],
 ['end.other','Этот этап карьеры завершён.','This career chapter ended.'],
 ['reviewChain','В истории сохранено обсуждений результатов: {count}. Уровень предупреждения к завершению: {stage}.','Recorded performance discussions: {count}. Warning stage at the end: {stage}.'],
 ['unagreed','За последние 14 календарных дней без согласованного переноса оставлено обязательств: {count}.','Obligations without agreed postponement in the last 14 calendar days: {count}.'],
 ['incomplete','В сохранённой истории не хватает данных для более точного объяснения.','The saved history lacks evidence for a more precise explanation.'],
 ['stress','Максимальный сохранённый стресс: {value}/100. Вечерних занятий для себя записано: {count}.','Maximum recorded stress: {value}/100. Recorded personal evening activities: {count}.'],
 ['tradeoff','Временное решение: польза сейчас и оставшаяся граница.','Temporary solution: immediate benefit and remaining boundaries.'],
 ['debt','Изменение технического долга от записанных действий: {debt}.','Technical debt change from recorded actions: {debt}.'],
 ['fix','Последующая работа действительно изменила систему.','Follow-up work actually changed the system.'],
 ['encountered','Эта проблема вернулась в следующую рабочую ситуацию.','This problem returned in a later work encounter.'],
 ['followupObserved','Последствие уже наблюдалось в мире; отдельная новая задача к этому моменту ещё не завершена.','The consequence was observed in the world; a separate new encounter has not been completed yet.'],
 ['incident','Инцидент: выбранное ограничение воздействия и наблюдаемый результат.','Incident: chosen containment and observed result.'],
 ['review','Проверка чужой работы: наблюдения и принятые границы.','Review: observations and accepted boundaries.'],
 ['pending','Дальнейший результат ещё не наблюдался к завершению карьеры.','No later outcome was observed by the end of this career.'],
 ['changed','Рабочая версия изменилась; это больше, чем закрытая карточка.','The working version changed; this is more than a completed task card.'],
 ['delegation.working','Работа передана; результата ещё нет.','Work was delegated; the result is still pending.'],
 ['delegation.returned','Коллега вернул результат; твоя проверка ещё не завершена.','The colleague returned a result; your review is unfinished.'],
 ['delegation.checked','Коллега вернул результат, и ты ответил на него.','The colleague returned a result and you responded to it.'],
 ['mentoring','Помощь коллеге: что получилось после разбора.','Helping a colleague: the observed outcome.'],
 ['obligation','День {day}: ожидание работы и реакция на него.','Day {day}: a work expectation and its response.'],
 ['work','Завершённая работа и зафиксированный результат.','Completed work and its recorded result.'],
 ['checked','Работа завершена; отдельного подтверждения изменения production в записи нет.','Work completed; the record contains no separate confirmation of a production change.'],
 ['pattern.temporary','Временные результаты выбраны {count} раз. Возвратов в новую задачу: {returned}.','Temporary results were chosen {count} times. Returns as new encounters: {returned}.'],
 ['pattern.evidence','В {count} из {total} завершённых работ записано исследование или проверка перед результатом.','Investigation or verification was recorded in {count} of {total} completed jobs.'],
 ['pattern.communication','О переносе или blocker сообщено {count} раз. Это сообщения, а не гарантии соблюдения срока.','Delays or blockers were communicated {count} times. These are communications, not proof of meeting deadlines.'],
 ['pattern.absence','Обязательства оставались без согласованного переноса {count} раз.','Obligations lacked agreed postponement {count} times.'],
 ['pattern.delegation','Работа передана {count} раз; результат разобран тобой в {checked} случаях.','Work was delegated {count} times; you reviewed the returned result in {checked} cases.'],
 ['pattern.mentoring','Завершённых эпизодов помощи коллеге: {count}. Итоги приведены выше.','Completed colleague support episodes: {count}. Their outcomes appear above.'],
 ['pattern.recovery','В истории есть {count} вечерних занятий для себя.','The history records {count} personal evening activities.'],
 ['pattern.systemic','После временного результата ты вернулся к реальному исправлению {count} раз.','You returned from a temporary result to an actual system repair {count} times.'],
 ['continuation','Позже с этой историей работал: {name}.','This story was later continued by: {name}.'],
 ['issue.technicalMistakes','За последние 14 календарных дней: технических действий с доказанным неуспехом — {count}.','In the last 14 calendar days: technical actions with observed failure — {count}.'],
 ['issue.ignoredQa','За последние 14 календарных дней: срочные обращения QA остались без работы — {count}.','In the last 14 calendar days: urgent QA requests left without work — {count}.'],
 ['issue.ignoredReview','За последние 14 календарных дней: срочные review остались без работы — {count}.','In the last 14 calendar days: urgent reviews left without work — {count}.'],
 ['issue.communicationFailures','За последние 14 календарных дней: записанных сбоев договорённостей и коммуникации — {count}.','In the last 14 calendar days: recorded communication or agreement failures — {count}.'],
 ['issue.riskyDeploys','За последние 14 календарных дней: выпусков с принятым риском — {count}.','In the last 14 calendar days: releases with accepted risk — {count}.'],
 ['issue.deadlineFailures','За последние 14 календарных дней: нарушений сроков — {count}.','In the last 14 calendar days: missed deadlines — {count}.'],
 ['issue.repeatedMistakes','За последние 14 календарных дней: повторных технических ошибок — {count}.','In the last 14 calendar days: repeated technical errors — {count}.']
];
rows.forEach(([id,ru,en])=>text('report.'+id,ru,en));
const stats=[['calendarDays','Календарных дней','Calendar days'],['playedDays','Закрытых рабочих дней','Closed work days'],['completedTasks','Основных задач','Main tasks'],['problemTypes','Типов проблем','Problem types'],['structures','Структур работы','Work structures'],['incidents','Инцидентов','Incidents'],['reviews','Проверок чужой работы','Reviews'],['mentoring','Эпизодов помощи','Mentoring episodes'],['delegations','Передач работы','Delegations'],['delegationsChecked','Разобранных результатов коллег','Reviewed colleague results'],['temporary','Временных результатов','Temporary results'],['recurrences','Возвратов после обхода','Returns after workarounds'],['properFixes','Изменений рабочей системы','Working system changes'],['overdue','Эскалаций обязательств','Obligation escalations'],['communicated','Сообщений о переносе/blocker','Delay/blocker communications'],['unagreed','Несогласованных обязательств','Unagreed obligations'],['maxStress','Максимальный сохранённый стресс','Maximum recorded stress'],['vacations','Отпусков','Leave periods'],['vacationDays','Запрошено рабочих дней отдыха','Requested working days off'],['recovery','Вечерних занятий','Evening activities']];
stats.forEach(([id,ru,en])=>text('report.stat.'+id,ru,en));
