import { text } from './localization';
type Pair=[string,string];
type Row=[string,Pair,Pair,Pair,Pair,Pair,Pair];
const rows:Row[]=[
['anya-work',['Про красивый интерфейс','About good design'],['Я убрала три рамки, и все решили, что это новый дизайн. Иногда лучшая работа — убрать лишнее.','I removed three borders and everyone called it a redesign. Sometimes the best work is subtraction.'],['А как понять, что лишнее?','How do you know what to remove?'],['Спроси, что человек должен сделать на экране. Всё, что мешает найти это действие, — кандидат на удаление.','Ask what someone needs to do on this screen. Anything hiding that action is a candidate.'],['Я бы добавил ещё тень.','I would add another shadow.'],['Можно. Но тень не спасёт кнопку, которую никто не заметил. Давай сначала проверим её на телефоне.','Sure. But a shadow will not rescue an invisible button. Let us check it on a phone first.']],
['anya-home',['Про уют дома','Making a home'],['У тебя дома тоже одна верхняя лампа? Она превращает любой вечер в допрос.','Do you also have one ceiling light at home? It makes every evening feel like an interrogation.'],['Что купить первым?','What should I buy first?'],['Настольную лампу. Тёплый свет и растение делают больше, чем десять модных постеров.','A table lamp. Warm light and a plant do more than ten trendy posters.'],['Я коплю на монитор.','I am saving for a monitor.'],['Тоже хорошо. Только оставь на столе место для чашки и локтей, а не только для пикселей.','Fair enough. Just leave room for your mug and elbows, not only pixels.']],
['ilya-work',['Когда код не работает','When code fails'],['Сегодня полчаса искал ошибку. Оказалось, смотрел не ту вкладку. Опыт — это узнавать свои грабли быстрее.','I spent half an hour debugging the wrong tab. Experience means recognising your own mistakes faster.'],['У меня такое каждый день.','That happens to me every day.'],['Тогда начни с простого: что ожидал, что получил, как повторить. Три строки лучше паники.','Start simple: what you expected, what happened, how to repeat it. Three lines beat panic.'],['И ты тоже ошибаешься?','You make mistakes too?'],['Конечно. Просто теперь я записываю причину, чтобы завтра не знакомиться с ней заново.','Of course. I write down the cause so I do not have to meet it again tomorrow.']],
['ilya-gear',['Про рабочий сетап','Desk setup'],['Заказал механическую клавиатуру. Теперь кот знает, когда я работаю, даже из другой комнаты.','I ordered a mechanical keyboard. Now my cat hears me working from the other room.'],['Оно того стоит?','Is it worth it?'],['Если приятно печатать — да. Скорость мысли не вырастет, но садиться за стол будет приятнее.','If you enjoy typing, yes. It will not speed up your thoughts, but your desk will feel nicer.'],['Мне бы второй экран.','I would rather have a second screen.'],['Полезная штука: на одном код, на другом результат. Только не превращай второй экран в ленту новостей.','Useful: code on one screen, the result on the other. Just do not turn it into a news feed.']],
['sergey-work',['Как просить помощь','Asking for help'],['Я больше переживаю за тех, кто молчит три дня, чем за тех, кто задаёт вопросы.','I worry more about people who stay silent for three days than those who ask questions.'],['Боюсь отвлекать.','I am afraid of interrupting.'],['Напиши, где застрял и что уже попробовал. Я выберу время. Просить помощь — часть работы.','Tell me where you are stuck and what you tried. I will find time. Asking is part of the job.'],['А если вопрос глупый?','What if it is a silly question?'],['Лучше пять минут разговора, чем день работы не туда. Даже если ответ оказался простым.','Five minutes talking beats a day in the wrong direction, even when the answer is simple.']],
['sergey-rest',['Работа после работы','After hours'],['Ноутбук закрыл? Отлично. Умение остановиться тоже профессиональный навык.','Laptop closed? Good. Knowing when to stop is a professional skill too.'],['Хочу ещё немного поучиться.','I want to study a little more.'],['Выбери одну тему и поставь предел. Учёба не должна съедать сон.','Choose one topic and set a limit. Learning should not eat your sleep.'],['Сегодня просто погуляю.','I will just go for a walk.'],['Хороший план. Иногда решение приходит, когда перестаёшь пялиться в экран.','Good plan. Sometimes the answer arrives when you stop staring at a screen.']],
['max-work',['Как Макс находит баги','How Max finds bugs'],['Я нажал назад во время оплаты. Потом ещё раз. Разработчики смотрели на меня как на стихийное бедствие.','I pressed Back during payment. Then again. The developers looked at me like a natural disaster.'],['Зачем так мучить кнопку?','Why torture the button?'],['Пользователь не читает наш сценарий. Он торопится, ошибается и теряет интернет. Я играю за него.','Users do not read our script. They rush, make mistakes and lose connection. I play their part.'],['Давай проверим вместе.','Let us test it together.'],['Вот это люблю. Ты расскажешь, как должно работать, а я попробую сделать иначе.','I like that. You explain how it should work, and I try something else.']],
['max-games',['Во что играешь?','What are you playing?'],['Вчера проиграл в стратегии. Зато составил подробный отчёт о том, почему виноват баланс.','Lost a strategy game yesterday. Wrote a detailed report explaining why the balance was at fault.'],['Классика: виновата игра.','Classic: blame the game.'],['Разумеется. Но сохранение перед битвой я всё-таки сделал. Проверка гипотез требует повторяемости.','Obviously. I did save before the battle though. Testing a theory requires reproducibility.'],['Позови в следующий раз.','Invite me next time.'],['Договорились. Только без рабочих созвонов в голосовом чате. Вечер должен оставаться вечером.','Deal. No work meetings in voice chat, though. An evening should stay an evening.']],
['oleg-work',['Зачем эта задача?','Why this task?'],['Красивая цифра в отчёте радует пять минут. А человек, который смог оплатить заказ, — весь бизнес.','A pretty report feels good for five minutes. Someone successfully paying helps the whole business.'],['Как понять, что стало лучше?','How do we know it improved?'],['Заранее договоримся, что измеряем. Например, сколько людей дошло от корзины до оплаты.','Agree on a measure before changing things. For example, how many people get from cart to payment.'],['Давай просто выпустим.','Let us just ship it.'],['Выпустим маленькой группе и посмотрим. Быстро — не обязательно вслепую.','To a small group first, then observe. Fast does not have to mean blind.']],
['oleg-shopping',['Опять маркетплейс?','Shopping again?'],['Положил в корзину держатель для наушников. Потом понял, что сначала нужны наушники.','Added a headphone stand to my basket. Then remembered I need headphones first.'],['Рекомендации победили?','The recommendations won?'],['Пока ничья. Теперь перед заказом спрашиваю: какую проблему эта вещь решает?','A draw so far. Now I ask what problem an item actually solves before ordering.'],['Я тоже обустраиваю квартиру.','I am furnishing my place too.'],['Начни с того, чем пользуешься каждый день. И проверь, есть ли куда поставить посылку.','Start with things you use every day. And make sure there is room for the parcel.']],
['former-story',['Про прежние задачи','Past work'],['Я до сих пор узнаю свои решения в этом проекте. Некоторые радуют, некоторые хочется переделать.','I still recognise my decisions in this project. Some make me proud, others I would redo.'],['Что бы ты изменил?','What would you change?'],['Оставлял бы больше объяснений рядом со сложными местами. Код живёт дольше нашей памяти.','I would explain the tricky parts better. Code outlives our memory.'],['Спасибо за основу.','Thanks for laying the groundwork.'],['Теперь твоя очередь улучшать. Если встретишь странность — спроси, я мог просто не знать лучшего способа.','Your turn to improve it. Ask about odd parts; I may simply not have known a better way.']],
];
export const conversations=rows.map(([id,title,body,a,ar,b,br])=>({id,npcId:id.split('-')[0],titleKey:text('chat.'+id+'.title',...title),bodyKey:text('chat.'+id+'.body',...body),choices:[{id:'ask',labelKey:text('chat.'+id+'.ask',...a),responseKey:text('chat.'+id+'.ask.response',...ar)},{id:'share',labelKey:text('chat.'+id+'.share',...b),responseKey:text('chat.'+id+'.share.response',...br)}]}));
export const topicsFor=(id:string)=>conversations.filter(c=>c.npcId===id||(c.npcId==='former'&&!conversations.some(x=>x.npcId===id)));
text('chat.topics','О чём поговорим?','What shall we talk about?');text('chat.again','К другим темам','Other topics');text('chat.remember','Вы уже говорили об этом.','You have talked about this.');
