import { tasks as legacy } from '../game/data/tasks';
import { text } from './localization';
import type { Effect,Mechanic,TaskTemplate,AppId } from '../world/types';
const english:Record<string,{title:string;body:string;options?:string[][]}>={
 'FE-1427.files':{title:'Where does the heading live?',body:'The heading lives in Hero, the first large section of the page. .tsx files describe components; .css files describe their appearance.',options:[['Home.tsx','This is the whole page. The heading lives in its own component.'],['Hero.tsx','Component found. There is our heading.'],['hero.module.css','We found the styles. First, let us identify the component they belong to.'],['App.tsx','Too high up. This file assembles the whole application.'],['package.json','The heading does not live here. At least you now know the React version.']]},
 'FE-1427.search':{title:'Searching is part of the job',body:'css how to move an element up',options:[['CSS margin-top','A negative top margin is what we need. For example, −10 px.','The outside spacing above an element. A negative value moves it up.'],['Stack Overflow on negative margins','To move the heading up 10 px, decrease its top margin by 10 px.','You can use a negative margin if you understand why you need it.'],['Forum: use position: absolute','Sounds confident. Suspiciously confident.\n17 replies: DO NOT DO THAT','A very confident person on the internet. What could go wrong?']]},
 'FE-1427.css':{title:'Ten pixels up',body:'Change only the top margin. A negative value moves the element up.',options:[['margin-top: -10px','The heading moved up exactly 10 px. Almost ready.'],['margin-bottom: 10px','The spacing below changed, but the heading did not move up.'],['position: absolute','The heading moved up. And left the normal document flow.'],['transform: rotate(180deg)','The heading certainly changed. The requirement was not met.']]},
 'FE-1427.tests':{title:'Check that nothing broke',body:'Automated tests check familiar scenarios. Run them and wait for the results.'},
 'FE-1427.review':{title:'A second pair of eyes',body:'If this value changes again, we should not have to find it everywhere. Let us give it one home. This is called a CSS variable.',options:[['Okay, I will update it','Thanks! A variable keeps the spacing in one place, making future changes easier.'],['Why?','Because the designers have changed this spacing three times already.'],['It works on my machine','Yes. Now make it easier for the rest of us to work with.']]},
 'FE-1427.variable':{title:'One variable, fewer surprises',body:'A named value can be changed in one place, updating every style that uses it.',options:[['Use a CSS variable','Review approved ✓\nSent to QA. Ilya approved the changes.'],['Add !important','The review comment is still there. Now it has an !important next to it.'],['Duplicate the rule','The same rule now exists in two places. Ilya sensed it from across the office.'],['Change nothing','The merge request is still waiting for changes.']]},
 'FE-1427.qa':{title:'Tests passed. Max did not.',body:'The heading is misplaced on an iPhone SE.\n“But the tests passed!”\nTests are people too. They sometimes make mistakes.',options:[['Use a separate offset on small screens','Max: “Looks good now.”','Keep the offset at 0 below 375 px; use −10 px on larger screens.'],['Hide the heading','The bug is gone. So is the heading.'],['Halve the font size','Anya: “Why is the heading the size of a footnote?”']]},
 'FE-1451.reproduce':{title:'Click. Now click again.',body:'The button removes a hint. Click twice to repeat what the user did.'},
 'FE-1451.console':{title:'Listen to the application',body:'The browser keeps a message journal. When something breaks, it often leaves a clue here. This journal is called Console.'},
 'FE-1451.understand':{title:'What disappeared after the first click?',body:'querySelector looks for an element. remove deletes it. Looking for the deleted hint again gives us null: nothing was found.',options:[['The server broke','Look at the word null again.'],['On the second click, hint is null','Exactly. The first click deleted the hint. The second tries to delete something that is no longer there.'],['It is a CSS problem','Look at the word null again.']]},
 'FE-1451.search':{title:'You are not the first to search for this',body:'javascript cannot read properties of null',options:[['Check whether the value exists before calling its method','Check whether the hint exists before calling remove.','if (hint) runs its block only when an element was found.'],['Restart the computer','The computer restarted. The bug stayed, rested and full of energy.']]},
 'FE-1451.fix':{title:'Do not talk to nothing',body:'If the hint still exists, remove it. If it is gone, do nothing. Which option checks whether it exists?',options:[['if (hint) { hint.remove(); }','Now remove is called only on an existing element.'],['window.location.reload();','The page reloaded. The cause of the bug remained.'],['try { hint.remove(); } catch {}','The error is hidden, but the code still tries to remove nothing. Check the value instead.'],['button.remove();','The hint stayed. The button resigned.']]},
 'FE-1451.retest':{title:'Same button. Another attempt.',body:'Test the fix with two clicks. The first removes the hint. The second safely does nothing.'},
 'FE-1451.review':{title:'One final review',body:'Yes, this one is straightforward. Approved.'},
};
const effect=(old:{stat:string;value:number}):Effect=>({target:old.stat==='htmlCss'||old.stat==='javascript'?'craft':old.stat as Effect['target'],value:old.value});
const mechanic:Record<string,Mechanic>={'file-picker':'file-browser',search:'search','code-choice':'code-choice',terminal:'terminal',review:'review','bug-preview':'visual-compare',reproduce:'bug-reproduction',console:'console'};
const app:Record<string,AppId>={'file-picker':'ide',search:'browser','code-choice':'ide',terminal:'console',review:'chat','bug-preview':'browser',reproduce:'browser',console:'console'};
export const frontendTasks:TaskTemplate[]=legacy.map((task,index)=>({id:task.id,titleKey:text(`task.${task.id}.title`,task.title,index===0?'Move the heading up 10 px':'The button breaks on the second click'),descriptionKey:text(`task.${task.id}.description`,task.description,index===0?'The heading on the home page sits too close to the next block. Move it slightly up.':'The first click works. The second does nothing. Naturally, the user clicked a third time.'),author:task.author,estimate:task.estimate,category:index===0?'interface':'payment',contribution:'repair',rewards:task.rewards.map(effect),steps:task.steps.map(step=>{
 const id=`${task.id}.${step.id}`,en=english[id];if(!en)throw new Error(`Missing frontend translation ${id}`);
 const ruBody=step.id==='review'&&index===0?'Если значение снова поменяют, не хочется искать его по всему проекту. Давай вынесем его в одно место. Это называется CSS variable.':step.id==='console'?'В журнале сообщений браузера часто остаётся подсказка о поломке. Этот журнал называется Console.':step.id==='understand'?'Подсказку уже удалили. Повторный поиск возвращает «ничего» — null. querySelector ищет элемент, remove удаляет найденное.':step.id==='variable'?'Сохраним отступ в одном месте и дадим ему имя. Такое именованное значение называется CSS variable.':step.text;
 return {id:step.id,type:mechanic[step.type],app:app[step.type],speaker:step.speaker,titleKey:text(`step.${id}.title`,step.title,en.title),bodyKey:text(`step.${id}.body`,ruBody,en.body),code:step.code,resultCode:step.resultCode,minutes:step.timeCostMinutes,wrongMinutes:step.wrongAttemptTimeCostMinutes??5,effects:(step.effects??[]).map(effect),wrongEffects:(step.wrongEffects??[]).map(effect),fixed:step.id==='retest',terms:step.id==='review'?['review','mr']:step.id==='variable'?['variable']:step.id==='qa'?['qa']:step.id==='understand'?['null']:step.id==='reproduce'?['bug']:step.id==='files'?['frontend']:[],options:step.choices?.map((c,i)=>{const ec=en.options![i];return {id:c.id,labelKey:text(`choice.${id}.${c.id}`,c.label,ec[0]),responseKey:text(`response.${id}.${c.id}`,c.response??'',ec[1]),detailKey:c.description?text(`detail.${id}.${c.id}`,c.description,ec[2]??''):undefined,correct:c.correct,effects:c.effects?.map(effect),minutes:c.timeCostMinutes};})};
})}));



