import { text } from './localization';
export const homeUpgrades = [
 {id:'plants',price:2500,stress:3,energy:0,ru:'Зелёный уголок',en:'A little greenery',desc:'Живые растения. Стресс после сна −3.',eng:'Living plants. Sleep removes 3 more stress.'},
 {id:'lamp',price:4500,stress:2,energy:0,ru:'Тёплый свет',en:'Warm lighting',desc:'Мягкий свет вместо офисного. Стресс после сна −2.',eng:'A softer light. Sleep removes 2 more stress.'},
 {id:'kitchen',price:12000,stress:0,energy:0,ru:'Кухня для себя',en:'Your own kitchen',desc:'Готовка восстанавливает ещё 15 энергии.',eng:'Cooking restores 15 more energy.'},
 {id:'chair',price:18000,stress:0,energy:0,ru:'Удобное кресло',en:'A comfortable chair',desc:'Чтение больше не расходует энергию.',eng:'Reading no longer costs energy.'},
 {id:'bed',price:28000,stress:4,energy:20,ru:'Хорошая кровать',en:'A proper bed',desc:'Сон: ещё +20 энергии и −4 стресса.',eng:'Sleep: 20 extra energy and 4 less stress.'},
 {id:'library',price:9000,stress:0,energy:0,ru:'Личная библиотека',en:'Your own library',desc:'Чтение приносит ещё +1 к мастерству.',eng:'Reading gives 1 extra craft point.'},
].map(u=>({...u,titleKey:text('home.item.'+u.id,u.ru,u.en),descriptionKey:text('home.item.'+u.id+'.desc',u.desc,u.eng)}));
const labels:Record<string,[string,string]>={title:['Место, где можно выдохнуть.','Room to breathe.'],subtitle:['Твой дом','Your home'],shop:['Обустроить дом','Make it yours'],evening:['Один вечер — для себя','An evening for yourself'],walk:['Прогуляться · стресс −7','Take a walk · stress −7'],cook:['Приготовить ужин · энергия +{value}','Cook dinner · energy +{value}'],read:['Почитать · мастерство +{value}','Read · craft +{value}'],readCost:['Без кресла: энергия −5.','Without a chair: energy −5.'],done:['На сегодня планы выполнены. Можно отдыхать.','Your evening is complete. Time to rest.'],owned:['Уже дома','At home'],buy:['Купить за {price} ₽','Buy for ₽{price}'],short:['Не хватает {price} ₽','Need ₽{price} more'],salary:['Оклад на руки / месяц','Monthly take-home salary'],daily:['За рабочий день: {price} ₽','Per working day: ₽{price}'],payNote:['В игре 22 рабочих дня в месяце. Деньги приходят после завершения дня. Премии за задачи — отдельно.','22 working days per game month. Pay arrives when you finish the day. Task bonuses are separate.'],paid:['Последнее начисление: {price} ₽','Last payment: ₽{price}'],recovery:['После сна: энергия +{energy}, стресс −{stress}','Sleep: energy +{energy}, stress −{stress}'],market:['Ориентиры: РФ, I полугодие 2026. Суммы по уровням адаптированы для игры.','Benchmarks: Russia, H1 2026. Career-level amounts are adapted for the game.'],roomAlt:['Твоя квартира с купленными улучшениями','Your apartment with purchased upgrades'],count:['Улучшения: {count} из 6','Upgrades: {count} of 6'],purchase:['Улучшение дома','Home improvement'],pay:['Зарплата','Salary'],rest:['Вечер дома','Evening at home']};
Object.entries(labels).forEach(([id,[ru,en]])=>text('home.'+id,ru,en));
