import {text} from './localization';
const rows=[
 ['variety','Разобраться в разных типах проблем','Handle different problem types'],
 ['autonomy','Самостоятельно исследовать рабочую проблему','Investigate a work problem independently'],
 ['planning','Выбрать объём работы и проверить результат','Choose scope and validate the result'],
 ['cross-team','Передать результат другому специалисту','Hand work to another specialist'],
 ['production','Поработать с оплатой, нагрузкой или инцидентом','Handle payments, performance or an incident'],
 ['tradeoff','Прожить компромисс между локальным и общим решением','Experience a local versus shared solution tradeoff'],
 ['ownership','Довести общий подход до проверенного результата','Own a shared approach through validation'],
 ['mentoring','Помочь коллеге проверить работу и объяснить границы','Help a colleague validate work and explain limits'],
 ['prioritization','Объяснить приоритет оставшейся работы','Explain the priority of remaining work'],
 ['delegation','Передать работу коллеге с договорённостью','Delegate work with an agreement'],
 ['people','Обсудить препятствие или командное решение','Discuss a blocker or a team decision'],
 ['context','В этой роли: {days} дн. Опыт растёт через работу, а не ожидание.','In this role: {days} days. Experience grows through work, not waiting.'],
 ['stories','Прожитые рабочие истории','Work stories experienced'],
 ['episode','Посмотреть на эту проблему глазами {role}','See this problem through {role}'],
 ['episodeTitle','Другая сторона той же работы','The other side of the same work'],
 ['return','Вернуться к своей работе','Return to your work'],
 ['reproduce','Повторить обращение пользователя','Reproduce the user report'],
 ['environment','Сменить окружение и повторить действие','Change environment and repeat the action'],
 ['regression','Проверить соседний сценарий','Check a neighboring scenario'],
 ['approve','Передать подтверждение с границами проверки','Send confirmation with test boundaries'],
 ['request','Вернуть работу с воспроизводимым случаем','Return work with a reproducible case'],
 ['mentor','Объяснить коллеге, что проверить и почему','Explain to a colleague what to check and why'],
 ['approveResult','Коллега получил подтверждение и знает, какие случаи ещё не проверены.','The colleague received confirmation and knows which cases remain untested.'],
 ['returnResult','Коллега получил условия сбоя. Следующий шаг — исправить этот конкретный случай.','The colleague received reproduction conditions. Next: fix this specific case.'],
 ['mentorResult','Коллега повторил проверку по твоему объяснению и смог описать границы результата.','The colleague repeated your check and could explain its boundaries.'],
 ['originalConditions','Это условия исходного обращения. Теперь повтори их на переданной версии.','These are the conditions of the original report. Now repeat them on the delivered version.'],
 ['qa1','Повторяешь действие из исходной задачи. Теперь важно не обещание исправления, а наблюдаемый результат.','You repeat the action from the original task. What matters is the observed result, not a promise.'],
 ['qa2','Сохраняешь устройство, версию и шаги. На другом окружении результат может отличаться.','You record device, version and steps. Another environment may behave differently.'],
 ['qa3','Проверка соседнего сценария — regression: не сломалось ли то, что раньше работало.','Checking a neighboring scenario is regression: did something previously working break?'],
 ['front1','Сопоставляешь экран и действия пользователя с тем, что пришло от сервера.','You compare the screen and user actions with the server response.'],
 ['front2','Меняешь состояние экрана и повторяешь действие. Уточняешь, где возникает расхождение.','You change screen state and repeat the action, locating the divergence.'],
 ['front3','Проверяешь соседний экран. У общей правки могут быть последствия за пределами исходного обращения.','You check a neighboring screen. A shared change can affect more than the original report.']
];rows.forEach(([id,ru,en])=>text('mastery.'+id,ru,en));
