import type {AppId,Problem,TaskTemplate,TechnicalAction,WorkArtifact} from '../world/types';
import {causalKey as k,paymentLabel as label} from './paymentCausalCopy';
const evidence=(id:string,kind:WorkArtifact['kind'],data:string[]):WorkArtifact=>({kind,titleKey:label(id+'-title','Оплата · проверяемые данные','Payment · observable evidence'),promptKey:'artifact.hint',rows:data.map((text,i)=>({id:String(i),labelKey:label(id+'-'+i,'Запись '+(i+1),'Record '+(i+1)),detailKey:label(id+'-data-'+i,text,text)}))});
export function paymentCausalScene(base:TaskTemplate,p:Problem,grade:number):TaskTemplate{
 const state=p.paymentCausal!,mode=state.phase,backendKey=state.contractChanged||state.limitation==='contained-pending'?'backendPendingReply':'backendReply';
 const a=(id:string,ru:string,en:string,key:string,next?:string[]):TechnicalAction=>({id:'causal-'+id,labelKey:label(id,ru,en),observationKey:k(key),minutes:8,next:next?.map(id=>'causal-'+id)});
 const finish=(action:TechnicalAction,kind:'temporary'|'durable',key:string,changed=false)=>{action.completes=true;action.outcome={kind,systemChanged:changed,summaryKey:k(key),followupKey:k(key),contribution:changed?'repair':'validation',delayDays:2};};
 const inspect=a('network','Сопоставить запрос и повтор','Compare the request and retry','qaEvidence',grade===0?['client']:grade===1?['client','contract-hypothesis']:['client','contract-hypothesis','metrics']);
 inspect.artifact=evidence('initial-'+state.revision+'-'+(state.limitation??'none'),'network',state.contractChanged?['requestId: pay-71 · operationKey: checkout-71 · pending · statusUrl: /payments/v2/status/71','handler polls /orders/status/71 → 404; original payment still exists']:state.limitation==='contained-pending'?['requestId: pay-71 · operationKey: checkout-71 · status: pending','retry disabled · duplicate orders: 0; pending payments: 7']:['requestId: pay-71 · operationKey: checkout-71 · status: timeout','retry · operationKey: checkout-72 · response: pending']);
 const metrics=a('metrics','Сопоставить общий spike с локальным воспроизведением','Compare the global spike with local reproduction','qaEvidence',['backend']);metrics.artifact=evidence('conflict','metrics',['QA: only reopened pending flow fails','metrics: global timeout spike; no correlation with duplicate order count']);metrics.experienceTags=['ambiguity'];
 const client=a('client','Проверить гипотезу ошибки клиента','Investigate the client hypothesis','qaEvidence',['backend']);
 const hypothesis=a('contract-hypothesis','Проверить гипотезу смены контракта','Investigate the contract hypothesis','qaEvidence',['backend']);
 const waitBackend=a('wait-backend','Пока ждём Backend, подготовить сравнение запросов','Prepare request comparison while Backend responds','qaEvidence',['reply']);waitBackend.minutes=30;
 const request=a('backend','Запросить Backend по requestId','Ask Backend about the requestId','qaEvidence',['reply','wait-backend']);request.dependency=true;request.dependencyRole='backend';request.dependencyResponseKey=k(backendKey);
 const reply=a('reply','Прочитать ответ Backend и пересмотреть гипотезу','Read the Backend reply and revise the hypothesis',backendKey,['contract','qa']);reply.requiresReply=true;reply.paymentCausal='backend-reply';reply.experienceTags=['cross-team','ambiguity'];
 const contract=a('contract','Сравнить completed и pending в контракте','Compare completed and pending in the contract',state.contractChanged?'contractChanged':'contractRule',['repair','defer']);
 contract.artifact=evidence('contract-v'+state.revision,'network',state.contractChanged?['completed · same operationKey → existing order','pending · statusUrl: /payments/v2/status/71; old endpoint → 404']:['completed · same operationKey → existing order','pending · same operationKey → check original status; new key → another order']);
 const qa=a('qa','Сопоставить воспроизведение QA с ответом Backend','Compare the QA reproduction with the Backend reply','qaEvidence',['repair','defer']);qa.artifact=evidence('qa-'+state.revision,'environment',state.contractChanged?['QA: reopened pending checkout uses old URL → 404','QA control: supplied statusUrl + original key → one order']:['lost reply + reopen → pending; client key changed','control: completed + same key → one order']);
 const repair=a('repair','Изменить обработку pending без нового ключа','Change pending handling without a new key','repairBuilt',['verify']);repair.experienceTags=['autonomy','planning','tradeoff'];
 const verify=a('verify','Проверить изменённую версию на двух состояниях','Verify the changed build in both states','proper');verify.artifact=evidence('fixed-'+state.revision,'network',['completed · keys: checkout-71, checkout-71 · orders: 1',state.contractChanged?'pending → response.statusUrl → original order · keys: checkout-71, checkout-71 · orders: 1':'pending → status original · keys: checkout-71, checkout-71 · orders: 1']);verify.paymentCausal='proper-fix';verify.experienceTags=['verification','production','ownership'];verify.effects=[{target:'techDebt',value:-(p.paymentChain?.debt??0)},{target:'stability',value:2}];finish(verify,'durable','proper',true);
 const defer=a('defer','Передать открытое ограничение и запросить новые данные','Hand over the open limit and request more evidence','deferred');defer.paymentCausal='defer-contract';finish(defer,'temporary','deferred');
 let actions=[inspect,client,hypothesis,metrics,request,waitBackend,reply,contract,qa,repair,verify,defer],initial=['causal-network'],app:AppId='browser',body=k(state.contractChanged?'contractChanged':'qaEvidence');
 if(mode==='review'){app='ide';
  const diff=a('diff','Прочитать изменение коллеги после timeout','Inspect the colleague’s timeout change','reviewOld',['comment','bounded']);diff.artifact=evidence('diff-'+state.peerRevision,'code',['before: timeout → createNewKey()','proposal: pending → retry(newKey) · missing original operation']);
  const comment=a('comment','Вернуть с конкретным замечанием по ключу операции','Return a specific operation-key review comment','reviewComment',['rework','wait-rework']);comment.paymentCausal='request-rework';comment.dependency=true;comment.dependencyRole='frontend';comment.dependencyResponseKey=k('reviewNew');comment.experienceTags=['review','cross-team'];
  const rework=a('rework','Открыть новый вариант, присланный коллегой','Open the colleague’s reworked version','reviewNew',['approve','return']);rework.requiresReply=true;rework.paymentCausal='read-rework';rework.artifact=evidence('reworked-'+(state.peerRevision+1),'code',['revision: '+(state.peerRevision+1)+' · timeout → retainOriginalKey()','pending → readOriginalStatus(); completed → existingOrder']);
  const approve=a('approve','Проверить новый diff и одобрить результат','Verify the new diff and approve','reviewApproved');approve.artifact=evidence('review-check','network',['timeout + same key → original status · orders: 1','pending + reopen → same operation · orders: 1']);approve.paymentCausal='approve-rework';approve.experienceTags=['review','verification','ownership'];finish(approve,'durable','reviewApproved');
  const again=a('return','Запросить отдельную проверку QA перед одобрением','Request independent QA verification before approval','deferred');again.paymentCausal='defer-contract';finish(again,'temporary','deferred');
  const bounded=a('bounded','Принять выпуск с непроверенным pending','Accept the release with pending unverified','risk');bounded.paymentCausal='accept-risk';bounded.experienceTags=['review','tradeoff'];finish(bounded,'temporary','risk');
  const waitRework=a('wait-rework','Подготовить проверку, пока коллега меняет работу','Prepare checks while the colleague reworks','reviewComment',['rework']);waitRework.minutes=30;
  actions=[diff,comment,waitRework,rework,approve,again,bounded];initial=['causal-diff'];body=k('reviewDue');
 }
 if(mode==='incident'){app='console';
  const triage=a('triage','Проверить дубли после принятого ограничения','Inspect duplicates after the accepted limit','incident',['contain']);triage.artifact=evidence('incident','logs',['release accepted pending risk · duplicate orders: '+(state.metrics?.duplicates??3),'requestId pay-71 · pending → NEW key']);
  const contain=a('contain','Отключить повтор для pending на время разбора','Disable pending retries during investigation','mitigated',['observe','wait-effect']);contain.paymentCausal='mitigate';contain.dependency=true;contain.dependencyRole='qa';contain.dependencyResponseKey=k('effect');
  const observe=a('observe','Посмотреть метрики после ограничения','Inspect metrics after containment','effect',['investigate','keep']);observe.requiresReply=true;observe.paymentCausal='observe-mitigation';observe.artifact=evidence('metrics','metrics',['before mitigation: duplicate orders '+(state.metrics?.duplicates??3)+'; pending '+(state.metrics?.pending??2),'after mitigation: new duplicates 0; pending 7']);
  const investigate=a('investigate','Передать частичный эффект и запросить контракт','Hand over the partial effect and request the contract','effect');investigate.paymentCausal='request-contract';finish(investigate,'temporary','effect');
  const keep=a('keep','Сохранить ограничение и принять незавершённые оплаты','Keep containment and accept unfinished payments','risk');keep.paymentCausal='accept-risk';finish(keep,'temporary','risk');
  const waitEffect=a('wait-effect','Собрать контрольное окно после ограничения','Collect a monitoring window after containment','mitigated',['observe']);waitEffect.minutes=30;
  actions=[triage,contain,waitEffect,observe,investigate,keep];initial=['causal-triage'];body=k('incident');
 }
 if(mode==='stable'){
  const validate=a('validate','Проверить текущий результат без повторного исправления','Validate the current result without another repair','proper');validate.artifact=evidence('current-fixed','network',['current build · retry same key → existing order','scope: completed and lost-reply paths · orders: 1']);validate.experienceTags=['verification','cross-team'];finish(validate,'durable','proper');actions=[validate];initial=['causal-validate'];body=k('proper');
 }
 if(grade>=3&&mode==='dependency'){
  const delegate=a('delegate','Передать проверку контракта Backend с условиями приёмки','Delegate the contract check to Backend with acceptance criteria','qaEvidence',['reply','wait-backend']);delegate.dependency=true;delegate.delegates=true;delegate.dependencyRole='backend';delegate.dependencyResponseKey=k(backendKey);delegate.experienceTags=['prioritization','ownership'];
  initial=['causal-delegate'];actions=[delegate,waitBackend,reply,contract,qa,repair,verify,defer];
 }
 for(const action of actions)if(action.artifact)action.requiresEvidence=true;
 return {...base,descriptionKey:body,steps:[{...base.steps[0],id:'payment-causal',app,titleKey:body,bodyKey:body,effects:[],actionFlow:{initial,actions}}],completionEffects:[],rewards:base.rewards.filter(e=>e.target!=='xp'),contribution:mode==='dependency'?'repair':'validation'};
}
