import {text} from './localization';
import {historyArtifact} from './historyArtifacts';
import type {Problem,TaskTemplate,TechnicalAction,WorkArtifact} from '../world/types';

const k=(id:string,ru:string,en:string)=>text('payment.chain.'+id,ru,en);
export const paymentChainKeys={
 temporary:k('temporary','Защита кнопки остановила двойной клик. Повтор после потери ответа всё ещё создаёт второй заказ; QA ждёт проверки этого ограничения.','The button guard stopped double clicks. Retrying after a lost response still creates another order; QA is waiting for this limitation to be checked.'),
 recurrence:k('recurrence','QA вернулась к той же оплате: после потери ответа пользователь повторил заказ. Локальная защита сбросилась при открытии экрана — появились два заказа.','QA returned to the same payment: after a lost response the user retried. Reopening the screen reset the local guard and produced two orders.'),
 fixed:k('fixed','Повтор оплаты сохраняет ключ операции и получает прежний заказ. Локальная защита удалена; её долг закрыт. QA ждёт независимой проверки двойного клика и потери ответа.','Payment retries retain the operation key and return the existing order. The local guard was removed and its debt repaid. QA awaits independent checks of double clicks and lost responses.'),
 verified:k('verified','Следующий герой повторил двойной клик и потерю ответа: в обоих случаях один заказ. QA получила условия и результаты; повторный сбор исходного бага больше не нужен.','The successor repeated double clicks and lost responses: both yielded one order. QA received conditions and results; gathering the original bug again is unnecessary.')
};
function artifact(id:string,rows:[string,string][]):WorkArtifact{
 return {kind:'network',titleKey:k(id+'.title','Повтор одной оплаты · журнал запросов','Retrying one payment · request log'),promptKey:k(id+'.prompt','Сравни ключ операции и номер заказа. Два запроса допустимы; два заказа для одной оплаты — нет.','Compare the operation key and order number. Two requests are allowed; two orders for one payment are not.'),rows:rows.map(([label,data],i)=>({id:String(i),labelKey:k(id+'.'+i+'.label',label.split(' / ')[0],label.split(' / ')[1]??label),detailKey:k(id+'.'+i+'.data',data,data)}))};
}
export function paymentChainScene(base:TaskTemplate,problem:Problem,successor:boolean,newHero=true):TaskTemplate{
 const a=(id:string,ru:string,en:string,observationKey:string,next?:string[],completes=false,tags:string[]=[]):TechnicalAction=>({id,labelKey:k(id+'.label',ru,en),observationKey,next,completes,minutes:10,experienceTags:tags});
 const fixed=artifact('fixed',[['Первый запрос / First request','POST /orders · operationKey: checkout-71 · order: A71'],['Повтор после потери ответа / Retry after lost response','POST /orders · operationKey: checkout-71 · order: A71 · reused: true']]);
 const before=artifact('before',[['Двойной клик / Double click','buttonGuard: active · requests: 1 · order: A71'],['Повтор после открытия / Retry after reopening','buttonGuard: reset · operationKey: NEW · orders: A71, A72']]);
 const previous=a('previous','Открыть результат прежней работы','Open the previous work result',paymentChainKeys.temporary,['trace'],false,['consequences']);previous.artifact=historyArtifact(problem);
 const compare=a('trace','Сравнить прежний обход с новым обращением QA','Compare the previous workaround with the new QA report',paymentChainKeys.recurrence,['contract'],false,['investigation','ambiguity','consequences']);compare.artifact=before;compare.effects=[{target:'debugging',value:1},{target:'xp',value:10}];
 const contract=a('contract','Посмотреть подтверждённое правило Backend','Inspect the confirmed Backend rule',k('contract.observation','Backend: «Повтор с тем же ключом уже возвращает прежний заказ. Клиент при повторе создаёт новый ключ. Сохрани исходный ключ до получения результата».','Backend: “A retry with the same key already returns the existing order. The client creates a new key on retry. Retain the original key until the result arrives.”'),['shared','limited'],false,['cross-team']);
 contract.artifact=artifact('contract',[['Один ключ / Same key','operationKey: checkout-71 → A71; retry checkout-71 → A71'],['Новый ключ / New key','operationKey: checkout-72 → A72']]);
 const repair=a('shared','Сохранить ключ оплаты между повторами и убрать локальную заплатку','Retain the payment key across retries and remove the local patch',k('repair.observation','Общий обработчик хранит ключ незавершённой оплаты после открытия экрана. Двойной клик и повтор используют одну операцию. Теперь проверь изменённую версию.','The shared handler retains the pending payment key after reopening. Double clicks and retries use one operation. Now check the changed build.'),['verify-shared'],false,['planning','tradeoff']);
 const limited=a('limited','Оставить обход и передать открытое ограничение','Keep the workaround and hand over its open limitation',paymentChainKeys.temporary,['verify-limited'],false,['tradeoff']);
 const check=a('verify-shared','Проверить повтор после потери ответа','Check retries after a lost response',paymentChainKeys.fixed,undefined,true,['verification','production','ownership']);check.artifact=fixed;
 check.outcome={kind:'durable',systemChanged:true,summaryKey:paymentChainKeys.fixed,followupKey:paymentChainKeys.fixed,contribution:'repair',delayDays:3};
 check.effects=[{target:'craft',value:1},{target:'xp',value:20},{target:'techDebt',value:-problem.paymentChain!.debt},{target:'stability',value:2}];
 const defer=a('verify-limited','Зафиксировать непокрытый повтор','Record the uncovered retry',paymentChainKeys.temporary,undefined,true,['consequences']);defer.outcome={kind:'temporary',systemChanged:false,summaryKey:paymentChainKeys.temporary,followupKey:paymentChainKeys.recurrence,contribution:'coordination',delayDays:2};
 const inspect=a('inspect-inherited','Открыть переданную проверку исправления','Open the inherited fix evidence',paymentChainKeys.fixed,['verify-inherited'],false,['consequences']);inspect.artifact=fixed;
 const verifiedKey=newHero?paymentChainKeys.verified:paymentChainKeys.fixed;
 const verify=a('verify-inherited','Самостоятельно повторить оба условия на новой версии','Independently repeat both conditions on the new build',verifiedKey,undefined,true,newHero?['review','verification']:['verification']);
 verify.artifact=artifact('successor',[['Двойной клик / Double click','build: fixed · clicks: 2 · orders: 1 · A71'],['Потеря ответа и повтор / Lost response and retry','build: fixed · response: lost · reopen → retry · orders: 1 · A71']]);
 verify.effects=[{target:'debugging',value:1},{target:'xp',value:20}];verify.worldContribution='validation';verify.outcome={kind:'durable',systemChanged:false,summaryKey:verifiedKey,followupKey:verifiedKey,contribution:'validation',delayDays:3};
 const handoff=a('handoff','Отправить QA условия, результат и следующий шаг','Send QA the conditions, result and next step',successor?verifiedKey:paymentChainKeys.fixed,undefined,true,['communication','cross-team']);handoff.observationByOutcome={temporary:paymentChainKeys.temporary,durable:successor?verifiedKey:paymentChainKeys.fixed};handoff.effects=[{target:'communication',value:1}];
 const body=successor?paymentChainKeys.fixed:paymentChainKeys.recurrence;
 const steps=[{...base.steps[0],id:'payment-evidence',app:'browser' as const,titleKey:k(successor?'inherit.title':'return.title',successor?'Проверить переданное исправление':'Та же оплата: обход встретил повтор',successor?'Verify the delivered fix':'The same payment: the workaround met a retry'),bodyKey:body,effects:[],actionFlow:{initial:[successor?'inspect-inherited':'previous'],actions:successor?[inspect,verify]:[previous,compare,contract,repair,limited,check,defer]}},{...base.steps.at(-1)!,id:'payment-handoff',bodyKey:body,effects:[],actionFlow:{initial:['handoff'],actions:[handoff]}}];
 for(const step of steps)for(const action of step.actionFlow.actions)if(action.artifact)action.requiresEvidence=true;
 return {...base,descriptionKey:body,steps,rewards:base.rewards.filter(e=>e.target!=='xp'),completionEffects:[],contribution:successor?'validation':'repair'};
}
