import { text } from './localization';
import type { Profession } from '../world/types';
type RoleRow=[string,string,string,string,string,string,string[],string[]];
const rows:RoleRow[]=[
 ['frontend','Frontend Developer','Frontend Developer','Делаешь понятные экраны и живые кнопки.','Build understandable screens and working buttons.','frontend',['Junior Frontend','Middle Frontend','Senior Frontend','Tech Lead','Engineering Manager','Architect'],['FE-1427','FE-1451']],
 ['backend','Backend Developer','Backend Developer','Соединяешь данные и действия за кулисами.','Connect data and actions behind the scenes.','backend',['Junior Backend','Middle Backend','Senior Backend','Tech Lead','Software Architect'],['backend-api','backend-query']],
 ['mobile','Mobile Developer','Mobile Developer','Делаешь продукт удобным в кармане.','Make the product work in your pocket.','mobile',['Junior Mobile','Middle Mobile','Senior Mobile','Mobile Lead','Mobile Architect'],['mobile-offline','mobile-layout']],
 ['qa','QA Engineer','QA Engineer','Находишь проблемы раньше пользователя.','Find problems before users do.','qa',['Junior QA','Middle QA','Senior QA','QA Lead','Head of Quality'],['qa-repeat','qa-regression']],
 ['qa-automation','QA Automation Engineer','QA Automation Engineer','Убираешь ручную рутину из проверок.','Take the repetitive work out of testing.','qa',['Junior QA Automation','QA Automation Engineer','Senior QA Automation','QA Lead','Test Architect'],['automation-flaky','automation-suite']],
 ['designer','Продуктовый дизайнер','Product Designer','Делаешь сложное понятным и удобным.','Make complex things clear and usable.','design',['Junior Product Designer','Middle Product Designer','Senior Product Designer','Design Lead','Head of Design'],['design-checkout','design-accessibility']],
 ['ux-research','UX Researcher','UX Researcher','Узнаёшь, что людям действительно мешает.','Find out what really gets in people’s way.','research',['Research Assistant','UX Researcher','Senior Researcher','Research Lead','Head of Research'],['research-interviews','research-evidence']],
 ['analyst','Системный аналитик','System Analyst','Превращаешь желания в работающие правила.','Turn wishes into rules a system can follow.','analysis',['Junior System Analyst','System Analyst','Senior System Analyst','Analysis Lead','Solution Architect'],['analysis-contract','analysis-dependencies']],
 ['business-analyst','Бизнес-аналитик','Business Analyst','Связываешь потребности бизнеса и продукта.','Connect business needs and the product.','analysis',['Business Analyst','Business Analyst II','Senior Business Analyst','Analysis Lead','Head of Analysis'],['business-process','business-criteria']],
 ['product','Product Manager','Product Manager','Выбираешь, какую проблему решать следующей.','Choose which problem to solve next.','product',['Associate Product Manager','Product Manager','Senior Product Manager','Product Lead','Head of Product'],['product-metrics','product-priority']],
 ['project','Project Manager','Project Manager','Помогаешь людям договориться о плане.','Help people agree on a workable plan.','delivery',['Project Coordinator','Project Manager','Senior PM','Delivery Manager','Head of Delivery'],['project-plan','project-resources']],
 ['delivery','Delivery Manager','Delivery Manager','Собираешь релиз из зависимостей и реальности.','Build a release plan around dependencies and reality.','delivery',['Delivery Coordinator','Delivery Manager','Senior Delivery Manager','Delivery Lead','Head of Delivery'],['delivery-release','delivery-capacity']],
 ['devops','DevOps Engineer','DevOps Engineer','Помогаешь изменениям безопасно попасть к людям.','Help changes reach users safely.','operations',['Junior DevOps','DevOps Engineer','Senior DevOps','Platform Lead','Platform Architect'],['devops-deploy','devops-alerts']],
 ['sre','SRE','SRE','Делаешь сервис надёжным даже в плохой день.','Keep services reliable on their worst days.','operations',['Reliability Engineer','SRE','Senior SRE','Platform Lead','Principal SRE'],['sre-incident','sre-budget']],
 ['sysadmin','Системный администратор','System Administrator','Поддерживаешь инфраструктуру и доступы.','Keep infrastructure and access working.','systems',['Junior Administrator','System Administrator','Senior Administrator','Infrastructure Lead','Head of Infrastructure'],['sysadmin-access','sysadmin-backup']],
 ['security','Security Engineer','Security Engineer','Замечаешь угрозы до того, как они станут новостями.','Spot threats before they make the news.','security',['Security Analyst','Security Engineer','Senior Security Engineer','Security Lead','Head of Security'],['security-permissions','security-incident']],
 ['data-analyst','Аналитик данных','Data Analyst','Отделяешь полезный сигнал от красивого графика.','Separate useful signals from pretty charts.','data',['Junior Data Analyst','Data Analyst','Senior Data Analyst','Analytics Lead','Head of Analytics'],['data-funnel','data-cohorts']],
 ['data-engineer','Data Engineer','Data Engineer','Доставляешь данные туда, где они нужны.','Get data where it is needed.','data-engineering',['Junior Data Engineer','Data Engineer','Senior Data Engineer','Data Lead','Data Architect'],['data-pipeline','data-quality']],
 ['dba','DBA','DBA','Помогаешь базе отвечать быстро и не терять данные.','Keep databases fast and data safe.','database',['Database Specialist','DBA','Senior DBA','Database Lead','Principal DBA'],['dba-query','dba-migration']],
 ['solution-architect','Solution Architect','Solution Architect','Соединяешь системы без лишних зависимостей.','Connect systems without unnecessary dependencies.','architecture',['Integration Analyst','Solution Designer','Solution Architect','Architecture Lead','Principal Architect'],['solution-boundaries','solution-migration']],
 ['architect','Software Architect','Software Architect','Выбираешь границы, которые переживут следующий релиз.','Choose boundaries that survive the next release.','architecture',['Software Designer','Software Architect','Senior Architect','Architecture Lead','Principal Architect'],['architecture-map','architecture-migration']],
 ['support','Техническая поддержка L2/L3','Technical Support L2/L3','Разбираешь сложные обращения и возвращаешь людям спокойствие.','Resolve difficult tickets and restore users’ peace of mind.','support',['Support L2','Support Engineer L3','Senior Support','Support Lead','Head of Support'],['support-diagnosis','support-escalation']],
];
export const professions:Profession[]=rows.map(([id,ru,en,descRu,descEn,family,titles,scenarioIds],index)=>({id,titleKey:text(`role.${id}`,ru,en),descriptionKey:text(`role.${id}.desc`,descRu,descEn),family,icon:['⌘','{ }','▣','✓','⚙','✳','◉','≋','◇','⚑'][index%10],scenarioIds,startingNode:'level-0',careers:titles.map((title,i)=>({id:`level-${i}`,titleKey:text(`career.${id}.${i}`,title,title),next:id==='frontend'&&i===3?['level-4','level-5']:i===titles.length-1||id==='frontend'&&i===4?[]:[`level-${i+1}`],leadership:i>=3,requirements:{work:i===0?0:Math.max(4,i*4),craft:i*2+1,reputation:i*5,communication:i,leadership:i>=4?2:0,...(i?{milestone:'independent'}:{})}}))}));
export const professionById=Object.fromEntries(professions.map(p=>[p.id,p]));
