import {text} from './localization';
const rows=[
['empty','Доступная тебе работа на сегодня закончилась','Your available work is done for today'],
['locked','Ещё {count} задач доступны на следующих уровнях самостоятельности. Они не блокируют завершение дня.','Another {count} tasks unlock at higher autonomy levels. They do not prevent finishing the day.'],
['emptyBody','Можно обсудить оставшиеся события с командой или закончить рабочий день. Новая очередь появится утром.','Talk through remaining team events or finish the workday. The queue renews tomorrow morning.'],
['office','К событиям команды','Go to team events'],
['finish','Закончить рабочий день','Finish the workday'],
['offDuty','Сейчас время отдыха. Рабочая очередь будет доступна утром.','It is rest time. The work queue will be available in the morning.'],
['pending','Следующий шаг: {event}','Next step: {event}'],
['victory','Карьера пройдена!','Career completed!'],
['victoryBody','Ты дорос до управления командой. Следующий герой начнёт в этом же мире: решения, исправления и незакрытые проблемы останутся.','You grew into team leadership. The next hero starts in this same world: decisions, repairs and unresolved problems remain.'],
['summary','Итоги прохождения','Run summary'],
['plus','Новая игра+ · выбрать следующего героя','New game+ · choose the next hero'],
['stay','Продолжить этой командой','Keep playing with this team'],
['tasks','Завершено задач','Completed tasks'],
['days','Игровых календарных дней','In-game calendar days'],
['played','Сыграно рабочих дней','Played workdays'],
['active','Время в игре, мин','Time in game, min'],
['real','Прошло реальных дней','Real days elapsed'],
['unknown','Нет данных для старого сохранения','Unavailable for this older save'],
['partial','Время считается с этого обновления; предыдущие сессии не восстановить.','Time is tracked from this update; earlier sessions cannot be recovered.'],
['achievements','Достижения этого героя','This hero’s achievements'],
['fixes','Настоящие исправления: {count}','Proper fixes: {count}'],
['reviewed','Проведённые ревью: {count}','Completed reviews: {count}'],
['delegated','Проверенные результаты коллег: {count}','Checked colleague results: {count}'],
['terms','Открытые понятия: {count}','Terms explored: {count}'],
['promotions','Повышения: {count}','Promotions: {count}'],
['preview','Просмотр итогов не завершает карьеру. Передача мира произойдёт только после подтверждения найма.','Viewing this summary does not end your career. The world transfers only after you confirm hiring.']
];rows.forEach(([id,ru,en])=>text('flow.'+id,ru,en));
