import {deliveryLenses} from './deliveryLenses';
import {accessLenses} from './accessLenses';
import {dataLenses} from './dataLenses';
import {analysisLenses} from './analysisLenses';
import {investigationLenses} from './investigationLenses';
import {infrastructureLenses} from './infrastructureLenses';
import {additionalRoleLenses} from './additionalRoleLenses';
import {text} from './localization';
import type {AppId,Problem,SceneOutcome,Step,TaskTemplate,TechnicalAction} from '../world/types';

type Pair=[string,string];
type CaseId='interface'|'payment'|'performance';
export type RoleLens={probe?:[Pair,Pair];observations?:{inspect:Pair;fast:Pair;care:Pair;limited:Pair;shared:Pair};id:string;app:AppId;contribution:string;inspect:Pair;trace:Pair;ask:Pair;missing:Pair;fast:Pair;care:Pair;check:Pair;facts:Record<CaseId,Pair>};
export const lensCases:CaseId[]=['interface','payment','performance'];
const contexts:Record<CaseId,Pair>={
 interface:['На телефоне часть формы исчезает. Люди не могут закончить действие, хотя на большом экране всё видно.','Part of the form disappears on phones. People cannot finish the action although it works on larger screens.'],
 payment:['После повторного нажатия создаются два результата вместо одного. Поддержка получила обращения от пользователей.','A repeated click creates two results instead of one. Support has received user reports.'],
 performance:['После релиза люди дольше ждут ответ. Команда не знает, где именно потерялось время.','After a release people wait longer for a response. The team does not yet know where time is being spent.']
};
export const roleLenses:RoleLens[]=[...additionalRoleLenses,...infrastructureLenses,...investigationLenses,...analysisLenses,...dataLenses,...accessLenses,...deliveryLenses,
 {id:'frontend',app:'browser',contribution:'repair',inspect:['Воспроизвести действие в браузере','Reproduce the action in the browser'],trace:['Сопоставить экран, состояние и сетевой запрос','Compare the screen, state and network request'],ask:['Сразу попросить серверного разработчика исправить ответ','Ask Backend to fix the response immediately'],missing:['Backend: «Пришли шаги и конкретный запрос — requestId. Пока мы не знаем, где расходится поведение». Теперь можно собрать эти данные.','Backend: “Send the steps and a specific request — requestId. We do not yet know where behavior diverges.” You can now gather that evidence.'],fast:['Добавить локальную защиту в этот компонент','Add a local guard to this component'],care:['Исправить общий компонент и его состояние','Fix the shared component and its state'],check:['Проверить повторное действие и соседний экран','Test repeated interaction and a neighboring screen'],facts:{
 interface:['Сетевой ответ одинаковый. При ширине 390 кнопка уходит за край: компонент рассчитывает ширину только при первом открытии.','The network response is identical. At width 390 the button leaves the screen: the component calculates its width only when first opened.'],
 payment:['Браузер отправляет два POST до обновления состояния. У каждого запроса есть номер — requestId. На время ожидания компонент не защищает повторный клик.','The browser sends two POST requests before state updates. Each has a requestId. The component does not guard repeated clicks while waiting.'],
 performance:['Ответ приходит быстро, но интерфейс снова строит весь длинный список при каждом изменении. Время теряется в компоненте, а не в сети.','The response arrives quickly, but every change rebuilds the entire long list. Time is spent in the component, not on the network.']
 }},
 {id:'qa',app:'browser',contribution:'validation',inspect:['Повторить обращение в двух окружениях','Repeat the report in two environments'],trace:['Изменить одно условие и проверить границы сбоя','Change one condition and establish the failure scope'],ask:['Отправить баг без условий воспроизведения','Send a bug report without reproduction conditions'],missing:['Разработчик не смог повторить сбой. Нужны устройство, версия и последовательность действий. Собери воспроизводимый случай, а не ещё один скриншот.','The developer could not reproduce it. Device, version and action sequence are missing. Gather a reproducible case rather than another screenshot.'],fast:['Проверить затронутый сценарий и ограничить рекомендацию','Check the affected scenario and limit the release recommendation'],care:['Расширить проверку на соседние сценарии','Extend testing to neighboring scenarios'],check:['Повторить сбой на исправленной версии','Repeat the failure on the corrected version'],facts:{
 interface:['Сбой повторяется на узком экране после поворота устройства; на широком его нет. Область проверки — размер и смена ориентации, а не все формы сразу.','It reproduces on narrow screens after rotation, not wide screens. The test scope is size and orientation changes rather than every form.'],
 payment:['Обычный клик проходит. При двойном клике на медленной сети появляются два заказа. Важны задержка и повтор, а не имя пользователя.','A normal click passes. Double clicking on a slow network creates two orders. Delay and repetition matter, not the username.'],
 performance:['Пустой список быстрый; список из 5000 записей зависает после релиза. Есть повторяемое условие для проверки исправления.','An empty list is fast; 5000 records stall after the release. There is a repeatable condition to verify a fix.']
 }},
 {id:'sre',app:'console',contribution:'repair',inspect:['Посмотреть доступность и время ответа вокруг релиза','Inspect availability and response time around the release'],trace:['Сравнить новую версию со старой под той же нагрузкой','Compare new and old versions under the same load'],ask:['Добавить мощности до проверки причины','Add capacity before checking the cause'],missing:['Ресурсов стало больше, жалобы остались. График нагрузки почти не изменился: сначала сравни версии, иначе масштабирование только увеличит расходы.','Capacity increased but reports remain. Load barely changed: compare versions first or scaling will only increase costs.'],fast:['Вернуть прежнюю версию и наблюдать','Restore the previous version and monitor'],care:['Ограничить новую версию и проверить исправление','Limit the new version and verify a fix'],check:['Наблюдать восстановление под реальной нагрузкой','Observe recovery under real load'],facts:{
 interface:['Сервис доступен, но после нового релиза выросли отказы мобильных сессий. Предыдущая версия с той же нагрузкой не даёт такого роста.','The service is available, but mobile session failures increased after the release. The previous version under the same load does not show this increase.'],
 payment:['После релиза выросло число повторных операций без роста посетителей. Запросы доходят до сервера; сеть не является единственной причиной.','Repeated operations increased after the release without more visitors. Requests reach the server; networking is not the only cause.'],
 performance:['Медленные ответы начались вместе с релизом. На прежней версии при той же нагрузке время ответа возвращается к норме.','Slow responses started with the release. Under the same load, response times return to normal on the previous version.']
 }},
 {id:'product',app:'chat',contribution:'coordination',inspect:['Узнать, кому мешает сбой и что они не могут сделать','Find who is affected and what they cannot do'],trace:['Сопоставить обращения, масштаб и обещания релиза','Compare reports, impact and release commitments'],ask:['Объявить срок исправления без оценки команды','Announce a deadline before asking the team'],missing:['Lead: «Мы ещё не оценили объём. Обещанный срок уже ждут в поддержке. Сначала согласуем влияние и границы решения, потом обновим обещание».','Lead: “We have not assessed the work yet. Support is already relying on that deadline. Agree on impact and scope first, then update the promise.”'],fast:['Согласовать временное ограничение и предупредить поддержку','Agree on a temporary restriction and inform support'],care:['Перенести релиз ради полного исправления','Move the release to allow a full fix'],check:['Сверить принятый объём с командой и поддержкой','Check the agreed scope with the team and support'],facts:{
 interface:['Мобильные пользователи не заканчивают форму; desktop почти не затронут. Поддержка может предложить временный путь, но он не заменяет исправление.','Mobile users cannot complete the form; desktop is barely affected. Support can offer a temporary route but it does not replace a fix.'],
 payment:['Повторные действия приводят к двойным результатам. Поддержка тратит время на разбор, а люди теряют доверие. Новая функция может подождать.','Repeated actions create duplicate results. Support spends time investigating and users lose trust. The new feature can wait.'],
 performance:['От ожидания страдают пользователи с большими списками. Быстро ограничить объём можно, но ограничение придётся объяснить тем, кто работает с архивом.','Users with large lists are affected. Volume can be limited quickly, but archive users will need that restriction explained.']
 }},
 {id:'designer',app:'browser',contribution:'design',inspect:['Пройти путь пользователя на узком экране','Walk through the user journey on a narrow screen'],trace:['Понаблюдать попытку и проверить обратную связь','Observe an attempt and examine feedback'],ask:['Передвинуть элементы без проверки сценария','Move elements without testing the journey'],missing:['Элементы сдвинулись, но человек всё ещё не понимает, что происходит. Проверка с пользователем нужна до следующей правки: проблема не только в расстоянии.','Elements moved, but the person still cannot understand what is happening. Observe the user before the next change: spacing is not the whole problem.'],fast:['Сделать понятный обход для затронутого экрана','Design a clear workaround for the affected screen'],care:['Пересобрать состояния и адаптацию общего паттерна','Redesign states and responsive behavior of the shared pattern'],check:['Пройти прототип с пользователем и проверить ограничения','Walk through the prototype with a user and check its limitations'],facts:{
 interface:['На узком экране действие теряется за рамкой. Пользователь не видит ни продолжения, ни объяснения. Нужен адаптивный путь, а не уменьшенный desktop.','On a narrow screen the action is outside the frame. The user sees neither a next step nor an explanation. This needs a responsive journey rather than a smaller desktop.'],
 payment:['После клика экран никак не отвечает. Человек нажимает снова, потому что не знает, принят ли заказ. Нужны состояния ожидания и подтверждения.','The screen gives no feedback after a click. The person clicks again because they do not know if the order was accepted. Waiting and confirmation states are needed.'],
 performance:['Пока длинный список готовится, экран выглядит сломанным. Человек повторяет действие. Нужно показать ожидание и возможность продолжить безопасно.','While the long list loads the screen looks broken. The person repeats the action. Show progress and a safe way to continue.']
 }},
 {id:'backend',app:'console',contribution:'repair',inspect:['Найти обращение по номеру запроса','Find the report by its request identifier'],trace:['Проследить состояние операции в журнале и базе','Trace operation state in logs and the database'],ask:['Повторно отправить операцию без проверки состояния','Resubmit the operation before checking its state'],missing:['Повтор создал ещё одну операцию. Клиентский успех не доказывает, что записан один результат. Найди исходное обращение по requestId и проверь состояние.','The retry created another operation. A successful response does not prove there is only one result. Find the original requestId and inspect its state.'],fast:['Ограничить проблемный путь на входе','Limit the problematic path at the entry point'],care:['Исправить правило обработки и хранение результата','Fix processing rules and result persistence'],check:['Проверить повтор и состояние сохранённых данных','Verify retries and persisted data'],facts:{
 interface:['Для узкого экрана ответ содержит все данные, но отсутствует признак доступного действия. Клиент и API понимают состояние по-разному; контракт нужно согласовать.','The narrow-screen response has all the data but lacks an available-action flag. Client and API disagree about state; align the contract.'],
 payment:['Два POST имеют один ключ операции, но создают две записи. Повтор не узнаёт сохранённый результат: нужна идемпотентность, то есть один результат при повторе.','Two POST requests share an operation key but create two records. The retry does not reuse the result: idempotency means producing one result when repeated.'],
 performance:['Запрос после релиза читает все строки вместо нужного диапазона. Время тратится в базе; увеличение таймаута только продлит ожидание.','After the release the query reads all rows instead of the required range. Time is spent in the database; increasing the timeout only extends the wait.']
 }}
];
export const hasRoleLens=(role:string)=>roleLenses.some(l=>l.id===role);
const step=(id:string,app:AppId,title:Pair,bodyKey:string,actions:TechnicalAction[],initial:string[]):Step=>({id,app,type:'choice',titleKey:text('lens.step.'+id,...title),bodyKey,actionFlow:{actions,initial},minutes:0,wrongMinutes:0,wrongEffects:[],effects:[]});
function lensTemplate(lens:RoleLens,category:CaseId):TaskTemplate{
 const id=`lens.${lens.id}.${category}`,key=(suffix:string,pair:Pair)=>text(id+'.'+suffix,...pair);
 const action=(name:string,label:Pair,observation:Pair,minutes:number,next?:string[],completes=false):TechnicalAction=>({id:name,labelKey:key(name+'.label',label),observationKey:key(name+'.observation',observation),minutes,next,completes});
 const outcome=(kind:SceneOutcome['kind']):SceneOutcome=>({kind,contribution:lens.contribution,delayDays:kind==='temporary'?2:3,
  summaryKey:key(kind+'.summary',kind==='temporary'?['Твой результат проверен в ограниченном сценарии. Общая причина и работа для коллег остаются; они знают границы твоего вклада.','Your result was verified for a limited scenario. The underlying cause and colleagues’ work remain; they know the scope of your contribution.']:['Проверка охватила исходный и соседний сценарии. Твой вклад передан коллегам; они продолжают работу с проверенными данными.','Testing covered the original and neighboring cases. Your contribution gives colleagues verified evidence to continue.']),
  followupKey:key(kind+'.followup',kind==='temporary'?['Поддержка принесла новый случай за пределами обхода. Lead просит вернуться к общей причине; ограничение осталось в проекте.','Support brought a new case outside the workaround. The lead asks to revisit the underlying cause; the limitation remains in the project.']:['Коллеги повторили проверку на следующей версии. Твой результат подтвердился; оставшиеся части проблемы видны в проекте.','Colleagues repeated the check on the next version. Your result held; remaining parts of the problem are visible in the project.'])});
 const inspect=action('inspect',lens.inspect,['Случай удалось повторить. Теперь можно отделить симптом от причины и сопоставить данные.','The case reproduced. You can now separate the symptom from its cause and compare evidence.'],12,['trace']);
 if(lens.id==='support'||lens.id==='mobile'||lens.probe)inspect.next=['trace','contact'];
 const ask=action('premature',lens.ask,lens.missing,8,['inspect']);ask.effects=[{target:'stress',value:1}];
 const trace=action('trace',lens.trace,lens.facts[category],18,undefined,true);trace.effects=[{target:'debugging',value:1},{target:'xp',value:10}];
 const fast=action('limited',lens.fast,['Локальный путь изменён. Это быстрее, но соседние случаи не покрыты. Проверь ограниченный результат до передачи.','The local path changed. It is faster, but neighboring cases are not covered. Verify the limited result before handing it over.'],20,['verify-limited']);
 const care=action('shared',lens.care,['Общий подход изменён. Потребовалось больше времени; теперь проверь исходный и соседний случаи.','The shared approach changed. It took longer; now verify the original and neighboring cases.'],40,['verify-shared']);
 const verifyLimited=action('verify-limited',lens.check,['Исходный случай проходит. Соседний остаётся за границами обхода; запиши это ограничение для коллег.','The original case passes. A neighboring case remains outside the workaround; record that limitation for colleagues.'],12,undefined,true);verifyLimited.outcome=outcome('temporary');verifyLimited.effects=[{target:'craft',value:1},{target:'techDebt',value:2}];
 const verifyShared=action('verify-shared',lens.check,['Исходный и соседний случаи проверены. Результат готов к передаче, включая то, что твоя роль не исправляла.','The original and neighboring cases were checked. The result is ready to hand over, including work outside your role.'],20,undefined,true);verifyShared.outcome=outcome('durable');verifyShared.effects=[{target:'craft',value:1},{target:'techDebt',value:-2}];
 if(lens.observations){inspect.observationKey=key('inspect.observation',lens.observations.inspect);fast.observationKey=key('limited.observation',lens.observations.fast);care.observationKey=key('shared.observation',lens.observations.care);verifyLimited.observationKey=key('verify-limited.observation',lens.observations.limited);verifyShared.observationKey=key('verify-shared.observation',lens.observations.shared);}
 if(['dba','qa-automation','ux-research','analyst','business-analyst','data-analyst','data-engineer','sysadmin','security','project','delivery'].includes(lens.id)){verifyLimited.effects=[{target:'craft',value:1}];verifyShared.effects=[{target:'craft',value:1}];}
 if(lens.id==='qa'){fast.worldContribution='repair';care.worldContribution='repair';
  fast.observationKey=key('limited.observation',['Разработчик прислал тестовую версию по твоим условиям. Начни с затронутого случая; остальные окружения пока не проверены.','The developer sent a test build based on your reproduction conditions. Check the affected case first; other environments are unverified.']);
  care.observationKey=key('shared.observation',['Разработчик прислал тестовую версию. Добавь соседние условия и смену окружения; это займёт больше времени.','The developer sent a test build. Add neighboring conditions and environment changes; this takes more time.']);
  verifyLimited.observationKey=key('verify-limited.observation',['В тестовой версии исходный случай больше не воспроизводится. Остальные окружения не проверены: рекомендация ограничена этим случаем.','The original failure no longer reproduces in the test build. Other environments are unverified: the recommendation is limited to this case.']);
  verifyShared.observationKey=key('verify-shared.observation',['В тестовой версии прошли исходный и соседний случаи. Разработчик получил результаты regression — проверки, что прежнее поведение не сломалось.','The original and neighboring cases pass in the test build. The developer received regression results — checks that existing behavior still works.']);
 }
 if(lens.id==='designer'){
  fast.observationKey=key('limited.observation',['В прототипе появился понятный обход. Проверим, замечает ли его человек; другие экраны пока не изменены.','The prototype now offers a clear workaround. Check whether a person notices it; other screens are unchanged.']);
  care.observationKey=key('shared.observation',['В прототипе согласованы ожидание, результат и узкий экран. Теперь проведи по этому пути пользователя.','The prototype aligns waiting, results and narrow screens. Now walk a user through the journey.']);
  verifyLimited.observationKey=key('verify-limited.observation',['Человек прошёл локальный прототип без повторного действия. Общий паттерн ещё не проверен, реализация остаётся за разработкой.','The person completed the local prototype without repeating the action. The shared pattern remains unverified and implementation belongs to development.']);
  verifyShared.observationKey=key('verify-shared.observation',['Человек понял ожидание и результат на двух экранах. Дизайн готов к реализации; исправление в продукте ещё предстоит проверить с QA.','The person understood waiting and results on both screens. Design is ready for implementation; the product fix still needs QA verification.']);
 }
 if(lens.id==='product'){
  fast.observationKey=key('limited.observation',['Поддержка получила границы временного ограничения. Уточни у команды, что именно остаётся доступным и когда вернёмся к причине.','Support received the temporary restriction boundaries. Confirm with the team what remains available and when the underlying cause will be revisited.']);
  care.observationKey=key('shared.observation',['Команда перенесла релиз и согласовала объём исправления. Проверь ожидания поддержки и тех, кто ждал новую функцию.','The team moved the release and agreed on the fix scope. Check support expectations and those waiting for the new feature.']);
  verifyLimited.observationKey=key('verify-limited.observation',['Команда подтвердила ограниченный путь; поддержка предупреждает затронутых людей. Причина остаётся в работе, новая функция пока задерживается.','The team confirmed the limited route; support informs affected users. The cause remains in progress and the new feature is delayed.']);
  verifyShared.observationKey=key('verify-shared.observation',['Поддержка и команда подтвердили новый план. Исправление получило место в релизе; ты согласовал ожидания, а не написал код за разработчиков.','Support and the team confirmed the new plan. The fix has a release slot; you aligned expectations rather than writing code for developers.']);
 }
 const handoff=action('handoff',['Передать проверенный результат и ограничения','Send the verified result and limitations'],['Коллега получил результат проверки. Следующие действия согласованы; твой вклад добавлен к общей проблеме проекта.','The colleague received the verified result. Next steps are agreed; your contribution was added to the shared project problem.'],10,undefined,true);
 handoff.observationByOutcome={temporary:key('handoff.limited',['Коллега: «Обход подтверждён. Поддержка знает ограничение; общая причина остаётся в очереди. Вернёмся к ней».','Colleague: “The workaround is confirmed. Support knows the limitation; the general cause remains queued. We will revisit it.”']),durable:key('handoff.shared',['Коллега: «Есть условия и результаты проверки. Могу продолжить свою часть, не собирая данные заново».','Colleague: “The conditions and verification results are here. I can continue my part without gathering the data again.”'])};
 handoff.effects=[{target:'communication',value:1}];
 return {id,titleKey:'problem.'+category,descriptionKey:key('context',contexts[category]),author:lens.id==='designer'?'anya':lens.id==='product'?'oleg':lens.id==='qa'?'max':'sergey',category,contribution:lens.contribution,estimate:110,rewards:[{target:'money',value:1400},{target:'xp',value:60},{target:'reputation',value:5}],steps:[
  step('investigate',lens.app,['Что происходит в твоей части продукта?','What is happening in your part of the product?'],key('context',contexts[category]),[inspect,ask,trace,...(lens.id==='support'||lens.id==='mobile'||lens.probe?[action('contact',lens.probe?.[0]??(lens.id==='support'?['Вернуться к пользователю за условиями повторения','Return to the user for reproduction conditions']:['Проверить потерю сети и возврат из фона','Test connectivity loss and background restoration']),lens.probe?.[1]??(lens.id==='support'?['Пользователь уточнил последовательность и подтвердил, что проблема повторяется. Владелец получит шаги, а не догадку.','The user clarified the sequence and confirmed the failure repeats. The owner will receive steps rather than a guess.']:['После потери сети сохранённое действие осталось в очереди. После возврата из фона экран не знает, что оно уже отправлено. Сопоставь состояния.','After connectivity loss the stored action remained in the queue. Returning from the background the screen does not know it was sent. Compare the states.']),10,['trace'])]:[])],['inspect','premature']),
  step('resolve',lens.id==='frontend'?'ide':lens.app,['Какой объём берёшь?','What scope will you take?'],key('scope',['Факты собраны. Можно дать проверенный локальный обход или вложить время в общий подход. Оба пути требуют проверки.','Evidence is gathered. Provide a verified local workaround or invest time in a shared approach. Both require verification.']),[fast,care,verifyLimited,verifyShared],['limited','shared']),
  step('handoff','chat',['Передать результат тем, кто ждёт','Send the result to those waiting'],key('ready',['Работа проверена. Отправь результат и его границы; ответ коллеги появится после отправки.','The work was verified. Send the result and its boundaries; the colleague responds after you send it.']),[handoff],['handoff'])
 ]};
}
export const roleLensTemplates=roleLenses.flatMap(lens=>lensCases.map(category=>lensTemplate(lens,category)));
export const supportedLensCategory=(category:Problem['category']):category is CaseId=>lensCases.includes(category as CaseId);
