import { priorityTasks } from './priorityTasks';
import { text } from './localization';
import { frontendTasks } from './frontend';
import type { AppId,Mechanic,Option,Step,TaskTemplate } from '../world/types';
type Pair=[string,string];
type Scenario={id:string;title:Pair;brief:Pair;type:Mechanic;items:Pair[];answer:number[]|Record<string,number>;fix:Pair;bad:Pair;category:TaskTemplate['category'];code?:string;budget?:number;preview?:Step['preview'];series?:[number,number][]};
const scenarios:Scenario[]=[
 {id:'backend-api',title:['Два запроса — один заказ','Two requests, one order'],brief:['В журнале два POST с одним paymentId. Найди строки, доказывающие дублирование.','Two POST requests share a paymentId. Select the lines proving duplication.'],type:'log-analysis',items:[['10:01 POST /orders payment=42 → order=801','10:01 POST /orders payment=42 → order=801'],['10:01 GET /health → 200','10:01 GET /health → 200'],['10:02 POST /orders payment=42 → order=802','10:02 POST /orders payment=42 → order=802']],answer:[0,2],fix:['Сохранять результат по paymentId и возвращать его повторно','Store the result by paymentId and return it for repeats'],bad:['Повторять запрос, пока не станет 200','Repeat requests until a 200 appears'],category:'payment'},
 {id:'backend-query',title:['Список заказов стал медленным','The orders list is slow'],brief:['Запрос читает все строки и возвращает всё клиенту. Отметь две причины нагрузки.','The query scans every row and returns everything to the client. Select two causes of load.'],type:'query-analysis',code:'SELECT * FROM orders;\nEXPLAIN: Seq Scan, rows=2400000',items:[['Полное сканирование 2,4 млн строк','Full scan of 2.4 million rows'],['Нет ограничения количества результатов','No result limit'],['В таблице есть поле id','The table has an id field']],answer:[0,1],fix:['Добавить фильтр, индекс и пагинацию','Add a filter, index and pagination'],bad:['Увеличить время ожидания до часа','Increase the timeout to one hour'],category:'performance'},
 {id:'mobile-offline',title:['Сеть пропала между нажатиями','The network vanished mid-tap'],brief:['Собери порядок безопасной отправки заказа при нестабильной сети. Сначала сохрани действие локально.','Order the steps for safe submission on an unreliable network. Save the action locally first.'],type:'planning',items:[['Сохранить действие локально','Save the action locally'],['Дождаться сети','Wait for connectivity'],['Отправить с уникальным ключом','Send with a unique key'],['Подтвердить результат пользователю','Confirm the result to the user']],answer:[0,1,2,3],fix:['Повторять одно действие с тем же ключом','Retry the same action with the same key'],bad:['Создавать новый заказ при каждом reconnect','Create a new order on every reconnect'],category:'payment'},
 {id:'mobile-layout',preview:'keyboard',title:['Кнопка под клавиатурой','The keyboard covers the button'],brief:['Проверь маленький экран. Найди нарушения: кнопка перекрыта, текст обрезан.','Inspect the small screen. Find the covered button and clipped text.'],type:'visual-compare',items:[['Кнопка оплаты под клавиатурой','Pay button behind keyboard'],['Заголовок обрезан на крупном шрифте','Heading clipped with large text'],['Иконка видна','Icon is visible']],answer:[0,1],fix:['Учесть клавиатуру и системный размер текста','Respect the keyboard and system text size'],bad:['Запретить увеличение шрифта','Disable larger text'],category:'interface'},
 {id:'qa-repeat',title:['Баг без магии','A reproducible bug'],brief:['Подготовь воспроизведение. Сначала чистая сессия, затем два одинаковых действия и сравнение результата.','Build a reproduction: clean session, repeat the action twice, then compare the result.'],type:'planning',items:[['Открыть чистую сессию','Open a clean session'],['Отправить оплату','Submit payment'],['Повторить ту же оплату','Repeat the same payment'],['Сравнить номера заказов','Compare order IDs']],answer:[0,1,2,3],fix:['Описать шаги, ожидание и фактические номера','Report steps, expected behavior and actual IDs'],bad:['Написать «всё сломано» без шагов','Report “everything is broken” without steps'],category:'payment'},
 {id:'qa-regression',title:['Проверим соседние двери','Check the neighboring paths'],brief:['После исправления повторной оплаты выбери обязательные проверки. Не забудь отказ банка.','Choose regression checks after fixing repeat payments. Remember bank declines.'],type:'release-check',items:[['Первая и повторная оплата','First and repeated payment'],['Отказ и повторная попытка','Decline and retry'],['Цвет аватара в профиле','Profile avatar color']],answer:[0,1],fix:['Приложить результаты и окружение','Attach results and environment'],bad:['Проверить только успешный первый клик','Check only the first successful click'],category:'payment'},
 {id:'automation-flaky',title:['Тест красный через раз','A test fails every other run'],brief:['Найди источники нестабильности в тесте.','Find the sources of test flakiness.'],type:'log-analysis',items:[['sleep(100) перед сетевым ответом','sleep(100) before a network response'],['Общий пользователь для параллельных тестов','One shared user across parallel tests'],['Уникальное имя теста','A unique test name']],answer:[0,1],fix:['Ждать конкретный ответ и изолировать данные','Wait for a specific response and isolate data'],bad:['Перезапускать тест десять раз до зелёного','Retry ten times until green'],category:'delivery'},
 {id:'automation-suite',title:['Регрессия до обеда','Regression before lunch'],brief:['На прогон есть 8 минут. Критичный checkout требует 5, авторизация — 3. Декоративные снимки можно отложить.','The run has 8 minutes: checkout needs 5 and authentication 3. Decorative snapshots can wait.'],type:'resource-allocation',items:[['Checkout','Checkout'],['Авторизация','Authentication'],['Декоративные снимки','Decorative snapshots']],answer:{'item-0':5,'item-1':3,'item-2':0},budget:8,fix:['Запустить критичный набор на каждый релиз','Run critical tests on every release'],bad:['Проверять только визуальные снимки','Run only decorative snapshots'],category:'delivery'},
 {id:'design-checkout',preview:'checkout',title:['Пользователь потерялся перед оплатой','Lost before payment'],brief:['Найди два препятствия на экране: неясная кнопка и скрытая итоговая сумма.','Find two obstacles: a vague button and a hidden total.'],type:'visual-compare',items:[['Кнопка «Продолжить» без пояснения','“Continue” without explaining the next step'],['Итог появляется только после подтверждения','Total appears only after confirmation'],['Доставка указана заранее','Delivery is shown upfront']],answer:[0,1],fix:['Показать итог и назвать действие «Оплатить»','Show the total and label the action “Pay”'],bad:['Сделать кнопку ярче, оставив всё остальное','Make the button brighter and change nothing else'],category:'interface'},
 {id:'design-accessibility',preview:'accessibility',title:['Красиво, но не прочитать','Pretty, but unreadable'],brief:['Отметь проблемы доступности. Цель — чтобы интерфейс был понятен без идеального зрения.','Select accessibility problems. The interface should not require perfect vision.'],type:'visual-compare',items:[['Светло-серый текст на белом','Light gray text on white'],['Ошибка обозначена только красным цветом','Error indicated only by red color'],['У поля есть видимая подпись','Field has a visible label']],answer:[0,1],fix:['Усилить контраст и добавить текст ошибки','Increase contrast and add an error message'],bad:['Добавить анимацию вместо пояснения','Add animation instead of explanation'],category:'interface'},
 {id:'research-interviews',title:['Пять разговоров вместо догадок','Five conversations, fewer guesses'],brief:['Сначала наблюдаем действия, потом задаём нейтральные вопросы, затем сравниваем наблюдения.','Observe behavior, ask neutral questions, then compare observations.'],type:'planning',items:[['Дать человеку реальную задачу','Give the person a realistic task'],['Наблюдать, не подсказывая','Observe without prompting'],['Спросить, что было непонятно','Ask what was confusing'],['Сопоставить наблюдения','Compare observations']],answer:[0,1,2,3],fix:['Записать повторяющиеся затруднения','Record recurring difficulties'],bad:['Спросить «вам ведь нравится?»','Ask “you like it, right?”'],category:'interface'},
 {id:'research-evidence',title:['Слова и действия не совпали','Words and actions disagree'],brief:['Выбери наблюдения, а не догадки команды.','Select observations rather than team assumptions.'],type:'metric-analysis',items:[['4 из 5 людей не нашли итоговую сумму','4 of 5 people could not find the total'],['3 человека вернулись к корзине','3 people returned to the cart'],['Кажется, всем нравится минимализм','We think everyone likes minimalism']],answer:[0,1],fix:['Проверить видимость суммы на следующем прототипе','Test total visibility in the next prototype'],bad:['Считать мнение руководителя результатом исследования','Treat the manager’s opinion as research'],category:'interface'},
 {id:'analysis-contract',title:['Что значит «повторить оплату»?','What does “retry payment” mean?'],brief:['Выбери правила договора между системами: один ключ — один результат; ошибки имеют понятные статусы.','Select the system contract rules: one key, one result; errors have clear states.'],type:'dependency-map',items:[['Ключ запроса → сохранённый результат','Request key → stored result'],['Ошибка банка → явный статус отказа','Bank error → explicit decline state'],['Повтор → всегда новый заказ','Retry → always a new order']],answer:[0,1],fix:['Описать примеры повторов и ошибок','Document retry and error examples'],bad:['Оставить решение на усмотрение каждой команды','Let each team interpret it independently'],category:'payment'},
 {id:'analysis-dependencies',title:['Кто от кого ждёт ответа','Who is waiting for whom'],brief:['Выбери реальные зависимости оплаты. Аналитика не должна блокировать завершение заказа.','Select real payment dependencies. Analytics must not block order completion.'],type:'dependency-map',items:[['Заказ → платёжный сервис','Order → payment service'],['Платёж → банк','Payment → bank'],['Платёж → рекламный отчёт','Payment → advertising report']],answer:[0,1],fix:['Вынести рекламный отчёт в отдельное событие','Move the advertising report to an asynchronous event'],bad:['Связать все системы синхронно','Connect all systems synchronously'],category:'delivery'},
 {id:'business-process',title:['Возврат без семи писем','Refunds without seven emails'],brief:['Собери процесс возврата: подтвердить покупку, проверить условия, вернуть деньги, уведомить.','Order the refund process: verify purchase, check policy, refund, notify.'],type:'planning',items:[['Найти покупку','Find the purchase'],['Проверить условия возврата','Check refund eligibility'],['Провести возврат','Issue the refund'],['Уведомить покупателя','Notify the buyer']],answer:[0,1,2,3],fix:['Зафиксировать владельца каждого шага','Assign an owner to each step'],bad:['Пусть пользователь сам найдёт ответственного','Make the user find the owner'],category:'payment'},
 {id:'business-criteria',title:['Когда работа действительно готова','What does done really mean'],brief:['Выбери проверяемые критерии приёмки. «Удобно» без примера нельзя проверить.','Select measurable acceptance criteria. “Convenient” without examples is not testable.'],type:'release-check',items:[['Повтор оплаты не создаёт второй заказ','Retrying payment does not create a second order'],['Отказ банка показывается понятным сообщением','Bank declines display a clear message'],['Чтобы всем нравилось','Everybody should like it']],answer:[0,1],fix:['Согласовать примеры до начала разработки','Agree on examples before development'],bad:['Уточнить критерии после релиза','Clarify criteria after release'],category:'delivery'},
 {id:'product-metrics',series:[[1000,1100],[800,440],[2,31]],title:['Заказов меньше. Почему?','Fewer orders. Why?'],brief:['Выбери признаки проблемы checkout, а не роста посещаемости.','Select signals of a checkout problem rather than traffic growth.'],type:'metric-analysis',items:[['Начали оплату: 1000 → 1100','Payment starts: 1000 → 1100'],['Завершили оплату: 800 → 440','Payment completions: 800 → 440'],['Ошибки оплаты: 2% → 31%','Payment errors: 2% → 31%']],answer:[1,2],fix:['Сначала исправить оплату, затем новые баннеры','Fix payments before adding banners'],bad:['Закупить больше трафика','Buy more traffic'],category:'payment'},
 {id:'product-priority',title:['У нас всё срочно','Everything is urgent'],brief:['Есть 6 человеко-дней. Платёжный баг требует 4, проверка результата — 2. Баннер подождёт.','There are 6 person-days: payment fix needs 4, validation needs 2. The banner can wait.'],type:'resource-allocation',items:[['Платёжный баг','Payment bug'],['Проверка результата','Validation'],['Новый баннер','New banner']],answer:{'item-0':4,'item-1':2,'item-2':0},budget:6,fix:['Объяснить приоритет потерянными заказами','Explain the priority using lost orders'],bad:['Пообещать все три задачи на завтра','Promise all three by tomorrow'],category:'delivery'},
 {id:'project-plan',title:['План, который можно выполнить','A plan that can happen'],brief:['API нужен до интеграции, интеграция — до QA, QA — до релиза.','API precedes integration, integration precedes QA, and QA precedes release.'],type:'planning',items:[['Контракт API','API contract'],['Интеграция','Integration'],['QA','QA'],['Релиз','Release']],answer:[0,1,2,3],fix:['Согласовать зависимые даты с владельцами','Agree on dependency dates with their owners'],bad:['Поставить всё на одну дату','Give every task the same deadline'],category:'delivery'},
 {id:'project-resources',title:['Один человек — не три команды','One person is not three teams'],brief:['Есть 5 дней: исправление занимает 3, тестирование 2. На вторую фичу времени нет.','Five days are available: fixing takes 3 and testing 2. There is no room for another feature.'],type:'resource-allocation',items:[['Исправление','Fix'],['Тестирование','Testing'],['Вторая фича','Second feature']],answer:{'item-0':3,'item-1':2,'item-2':0},budget:5,fix:['Снять вторую фичу с этого релиза','Move the second feature out of this release'],bad:['Попросить всех просто ускориться','Ask everyone to just work faster'],category:'delivery'},
 {id:'delivery-release',title:['Релиз и его блокеры','A release and its blockers'],brief:['Отметь обязательные условия релиза: критический баг закрыт, откат проверен. Новая иллюстрация не блокирует.','Select release requirements: critical bug fixed, rollback tested. A new illustration is not a blocker.'],type:'release-check',items:[['Критический баг закрыт','Critical bug fixed'],['План отката проверен','Rollback tested'],['Новая иллюстрация готова','New illustration ready']],answer:[0,1],fix:['Выпустить согласованный объём','Release the agreed scope'],bad:['Дождаться всех необязательных пожеланий','Wait for every optional request'],category:'delivery'},
 {id:'delivery-capacity',title:['Резерв — это часть плана','Contingency is part of the plan'],brief:['Из 10 дней выдели 6 на работу, 2 на проверку, 2 на риски.','Allocate 10 days: 6 for work, 2 for validation and 2 for contingency.'],type:'resource-allocation',items:[['Работа','Work'],['Проверка','Validation'],['Риски','Contingency']],answer:{'item-0':6,'item-1':2,'item-2':2},budget:10,fix:['Сделать резерв видимым в плане','Make contingency visible in the plan'],bad:['Скрыть риски, чтобы план выглядел лучше','Hide risks to make the plan look better'],category:'delivery'},
 {id:'devops-deploy',title:['Релиз без прыжка в темноту','A release without a leap into darkness'],brief:['Сначала проверка сборки, потом малая доля трафика, метрики и полный rollout.','Check the build, send a small traffic slice, inspect metrics, then roll out fully.'],type:'planning',items:[['Проверить сборку','Check build'],['Включить для 5% трафика','Enable for 5% of traffic'],['Проверить метрики ошибок','Check error metrics'],['Расширить rollout','Expand rollout']],answer:[0,1,2,3],fix:['Остановить расширение при росте ошибок','Stop expansion if errors rise'],bad:['Сразу выкатить всем и уйти','Deploy to everyone and leave'],category:'performance'},
 {id:'devops-alerts',title:['Сирена на каждый чих','An alert for every sneeze'],brief:['Найди сигналы, требующие реакции: высокий процент ошибок и недоступный сервис.','Select actionable signals: high error rate and an unavailable service.'],type:'log-analysis',items:[['5xx: 22% в течение 10 минут','5xx: 22% for 10 minutes'],['Health check: failed','Health check: failed'],['CPU: 18% один раз','CPU: 18% once']],answer:[0,1],fix:['Связать алерт с инструкцией и владельцем','Attach an owner and runbook to the alert'],bad:['Выключить все уведомления','Disable all notifications'],category:'performance'},
 {id:'sre-incident',title:['Сначала остановить пожар','First, stop the fire'],brief:['При росте ошибок: стабилизация, проверка восстановления, расследование, профилактика.','When errors spike: stabilize, verify recovery, investigate, prevent recurrence.'],type:'incident-response',items:[['Откатить проблемный релиз','Roll back the bad release'],['Проверить восстановление','Verify recovery'],['Найти причину','Find the cause'],['Добавить защиту','Add prevention']],answer:[0,1,2,3],fix:['Зафиксировать разбор без поиска виноватого','Write a blameless incident review'],bad:['Искать виноватого до восстановления','Find someone to blame before restoring service'],category:'performance'},
 {id:'sre-budget',title:['Надёжность тоже имеет бюджет','Reliability has a budget too'],brief:['Найди признаки, что рискованный релиз стоит отложить.','Find evidence that a risky release should wait.'],type:'metric-analysis',items:[['Бюджет ошибок исчерпан на 98%','Error budget is 98% consumed'],['Три инцидента за неделю','Three incidents this week'],['Новый цвет логотипа согласован','New logo color approved']],answer:[0,1],fix:['Выделить время на стабильность','Invest time in stability'],bad:['Ускорить релизы, чтобы перекрыть проблемы','Release faster to outrun the problems'],category:'performance'},
 {id:'sysadmin-access',title:['Доступ на всякий случай','Just-in-case access'],brief:['Отметь лишние права: стажёр не администратор, старый сотрудник уже ушёл.','Select excessive permissions: the intern is not an admin and the former employee has left.'],type:'security-review',items:[['Стажёр: domain admin','Intern: domain admin'],['Бывший сотрудник: активный VPN','Former employee: active VPN'],['Бухгалтер: доступ к отчётам','Accountant: report access']],answer:[0,1],fix:['Оставить только нужные права и владельца заявки','Keep only required rights and a request owner'],bad:['Выдать всем admin, чтобы меньше писали','Give everyone admin so they stop asking'],category:'access'},
 {id:'sysadmin-backup',title:['Резервная копия — не обещание','A backup is not a promise'],brief:['Сначала изолированное восстановление, потом проверка данных и документация результата.','Restore in isolation, validate the data, then document the result.'],type:'planning',items:[['Восстановить в тестовую среду','Restore to a test environment'],['Проверить данные','Validate data'],['Измерить время восстановления','Measure recovery time'],['Записать результат','Record the result']],answer:[0,1,2,3],fix:['Регулярно проверять восстановление','Test recovery regularly'],bad:['Считать наличие файла достаточной проверкой','Treat the backup file’s existence as sufficient proof'],category:'performance'},
 {id:'security-permissions',title:['Ключ от всех дверей','A key to every door'],brief:['Отметь опасные разрешения сервисного аккаунта. Для отчётов достаточно чтения.','Select dangerous permissions on the reporting service account. Reports need read-only access.'],type:'security-review',items:[['DELETE production database','DELETE production database'],['CREATE admin users','CREATE admin users'],['SELECT reporting views','SELECT reporting views']],answer:[0,1],fix:['Ограничить аккаунт чтением нужных представлений','Restrict the account to reading required views'],bad:['Переименовать аккаунт в safe-user','Rename the account to safe-user'],category:'access'},
 {id:'security-incident',title:['Вход из двух мест сразу','Logged in from two places'],brief:['Сначала ограничь скомпрометированный доступ, сохрани следы, замени ключи и проверь последствия.','Contain compromised access, preserve evidence, rotate keys, assess impact.'],type:'incident-response',items:[['Ограничить сессию','Contain the session'],['Сохранить журнал событий','Preserve event logs'],['Заменить скомпрометированные ключи','Rotate compromised keys'],['Проверить затронутые данные','Assess affected data']],answer:[0,1,2,3],fix:['Уведомить владельца и задокументировать инцидент','Notify the owner and document the incident'],bad:['Удалить логи, чтобы не пугать команду','Delete logs to avoid alarming the team'],category:'access'},
 {id:'data-funnel',series:[[10000,10000],[800,400],[1,25]],title:['Где исчезли покупатели','Where did the buyers go'],brief:['Найди просадку: посещения стабильны, оплата резко упала, ошибки выросли.','Find the drop: visits are stable, payments fell sharply, errors increased.'],type:'metric-analysis',items:[['Посещения: 10k → 10k','Visits: 10k → 10k'],['Оплаты: 800 → 400','Payments: 800 → 400'],['Ошибки: 1% → 25%','Errors: 1% → 25%']],answer:[1,2],fix:['Проверить изменение по времени релиза','Compare the change with release timing'],bad:['Сложить посещения и оплаты в одну метрику','Add visits and payments into one metric'],category:'payment'},
 {id:'data-cohorts',series:[[70,35],[65,31],[80,81]],title:['Среднее скрыло проблему','The average hid the problem'],brief:['Выбери сегменты с ухудшением: новые пользователи и мобильные устройства.','Select deteriorating segments: new users and mobile devices.'],type:'metric-analysis',items:[['Новые: 70% → 35%','New users: 70% → 35%'],['Mobile: 65% → 31%','Mobile: 65% → 31%'],['Desktop: 80% → 81%','Desktop: 80% → 81%']],answer:[0,1],fix:['Исследовать пересечение сегментов','Investigate the overlap between segments'],bad:['Смотреть только на общую среднюю','Only look at the overall average'],category:'interface'},
 {id:'data-pipeline',title:['Ночные данные опоздали','The overnight data is late'],brief:['Найди две причины: источник задержался и повтор создал дубли.','Find two causes: a delayed source and duplicates from a retry.'],type:'log-analysis',items:[['source arrival: +90m','source arrival: +90m'],['retry inserted same batch twice','retry inserted same batch twice'],['dashboard color: green','dashboard color: green']],answer:[0,1],fix:['Добавить контроль свежести и идемпотентную загрузку','Add freshness checks and idempotent ingestion'],bad:['Обновлять дашборд чаще','Refresh the dashboard more often'],category:'performance'},
 {id:'data-quality',title:['Числа сошлись слишком хорошо','The numbers match suspiciously well'],brief:['Отметь нарушения качества: дубли ключей и отсутствующие даты.','Select data-quality violations: duplicate keys and missing dates.'],type:'query-analysis',code:'SELECT id, COUNT(*) FROM events GROUP BY id HAVING COUNT(*) > 1;',items:[['17 дубликатов event_id','17 duplicate event_id values'],['42 пустых timestamp','42 null timestamps'],['Есть описание схемы','Schema is documented']],answer:[0,1],fix:['Остановить плохой batch и сохранить его для разбора','Quarantine the bad batch for investigation'],bad:['Заменить все пропуски нулями','Replace every missing value with zero'],category:'payment'},
 {id:'dba-query',title:['База читает весь шкаф','The database reads the whole cabinet'],brief:['Отметь дорогие части плана запроса.','Select the expensive parts of the query plan.'],type:'query-analysis',code:'Seq Scan on orders: 2400000 rows\nSort: external merge, Disk: 820MB',items:[['Seq Scan: 2,4 млн строк','Seq Scan: 2.4 million rows'],['Сортировка на диске: 820 MB','Disk sort: 820 MB'],['LIMIT 20 после фильтра','LIMIT 20 after filter']],answer:[0,1],fix:['Подобрать индекс под фильтр и порядок','Choose an index matching the filter and sort'],bad:['Создать индекс на каждом столбце без анализа','Index every column without analysis'],category:'performance'},
 {id:'dba-migration',title:['Изменить схему, не остановив продукт','Change the schema without stopping the product'],brief:['Добавь новое поле совместимо, перенеси данные, переключи чтение, затем убери старое.','Add a compatible field, backfill, switch reads, then remove the old field.'],type:'planning',items:[['Добавить новое поле','Add the new field'],['Перенести данные','Backfill data'],['Переключить чтение','Switch reads'],['Убрать старое после проверки','Remove the old field after validation']],answer:[0,1,2,3],fix:['Сохранить возможность отката на каждом этапе','Keep a rollback path at each stage'],bad:['Удалить старое поле первым действием','Delete the old field first'],category:'delivery'},
 {id:'solution-boundaries',title:['Заказ знает слишком много','The order knows too much'],brief:['Оставь критические зависимости. Отчёты и рассылки не должны блокировать оплату.','Keep critical dependencies. Reports and email must not block payment.'],type:'architecture-diagram',items:[['Checkout → Payment','Checkout → Payment'],['Payment → Bank','Payment → Bank'],['Payment → Newsletter','Payment → Newsletter']],answer:[0,1],fix:['Публиковать событие для некритичных потребителей','Publish an event for noncritical consumers'],bad:['Добавить ещё один общий синхронный сервис','Add another shared synchronous service'],category:'payment'},
 {id:'solution-migration',title:['Переезд без большого взрыва','A migration without a big bang'],brief:['Сначала контракт, затем параллельная проверка, малый трафик и расширение.','Agree the contract, validate in parallel, route a small traffic slice, then expand.'],type:'planning',items:[['Контракт','Contract'],['Параллельная проверка','Parallel validation'],['5% трафика','5% traffic'],['Постепенное расширение','Gradual expansion']],answer:[0,1,2,3],fix:['Измерять ошибки и держать обратный маршрут','Measure errors and keep the reverse route'],bad:['Одним вечером переписать всё','Rewrite everything in one evening'],category:'delivery'},
 {id:'architecture-map',title:['Границы вместо большого комка','Boundaries instead of one big knot'],brief:['Выбери связи, которые действительно нужны для оплаты.','Select dependencies genuinely required for payment.'],type:'architecture-diagram',items:[['Orders → Payment API','Orders → Payment API'],['Payment → Bank adapter','Payment → Bank adapter'],['Orders → прямой доступ к таблицам банка','Orders → direct access to bank tables']],answer:[0,1],fix:['Скрыть внутренние данные за явным контрактом','Hide internal data behind an explicit contract'],bad:['Раздать общий доступ ко всем таблицам','Give everything access to every table'],category:'payment'},
 {id:'architecture-migration',title:['Старый сервис должен пережить новый','The old service must survive the new one'],brief:['Сначала совместимый интерфейс, потом перенос части нагрузки, наблюдение и завершение.','Start with a compatible interface, move some load, observe, then finish.'],type:'planning',items:[['Совместимый интерфейс','Compatible interface'],['Часть нагрузки','A portion of load'],['Наблюдение за ошибками','Observe errors'],['Завершение миграции','Complete migration']],answer:[0,1,2,3],fix:['Зафиксировать границы и стоимость решения','Document boundaries and trade-offs'],bad:['Выбрать технологию только по моде','Choose a technology only because it is fashionable'],category:'delivery'},
 {id:'support-diagnosis',title:['У клиента «ничего не работает»','The customer says “nothing works”'],brief:['Выбери данные, с которыми можно расследовать: время, requestId и шаги. Пароль не нужен.','Select useful investigation data: time, requestId and steps. A password is not needed.'],type:'log-analysis',items:[['Время и requestId','Time and requestId'],['Шаги и сообщение об ошибке','Steps and error message'],['Пароль пользователя','User password']],answer:[0,1],fix:['Дать безопасный обход и передать диагностику владельцу','Provide a safe workaround and send diagnostics to the owner'],bad:['Попросить пароль для проверки','Ask for the password to test it'],category:'payment'},
 {id:'support-escalation',title:['Передать обращение, а не головную боль','Escalate a ticket, not a headache'],brief:['Сначала факты, затем влияние, владелец и обратная связь клиенту.','Collect facts, assess impact, find the owner, then update the customer.'],type:'planning',items:[['Собрать факты','Collect facts'],['Оценить влияние','Assess impact'],['Назначить владельца','Assign an owner'],['Сообщить клиенту план','Tell the customer the plan']],answer:[0,1,2,3],fix:['Вернуться к клиенту после исправления','Follow up with the customer after the fix'],bad:['Закрыть обращение после пересылки','Close the ticket as soon as it is forwarded'],category:'delivery'},
 {id:'lead-review',title:['Теперь изменения проверяешь ты','Now you review the changes'],brief:['Junior поправил симптом, но оставил риск. Отметь полезные замечания к работе.','A junior fixed the symptom but left a risk. Select useful review comments.'],type:'release-check',items:[['Добавить проверку повторного действия','Add a repeated-action test'],['Объяснить причину и предложить помощь','Explain the reason and offer help'],['Написать «переделай всё» без объяснения','Write “redo everything” without explanation']],answer:[0,1],fix:['Обсудить правку и дать коллеге закончить самому','Discuss the fix and let the colleague finish it'],bad:['Молча переписать всё за коллегу','Silently rewrite everything for them'],category:'delivery'},
 {id:'lead-plan',title:['Команда — не бесконечный ресурс','The team is not an infinite resource'],brief:['Из 8 дней: 4 на критичную работу, 2 на поддержку junior, 2 на резерв.','Allocate 8 days: 4 for critical work, 2 for mentoring and 2 for contingency.'],type:'resource-allocation',items:[['Критичная работа','Critical work'],['Помощь junior','Mentoring'],['Резерв','Contingency']],answer:{'item-0':4,'item-1':2,'item-2':2},budget:8,fix:['Согласовать приоритеты и защитить время команды','Agree priorities and protect team time'],bad:['Обещать всё и предложить поработать ночью','Promise everything and suggest working overnight'],category:'delivery'},
];
// Alternative approaches retain existing IDs so in-progress saves remain valid.
const alternatives:Record<string,Pair>={
 'qa-regression':['Сначала проверить основной путь и выпустить ограниченной группе','Check the main path first and release to a limited group'],
 'automation-suite':['Сначала прогнать визуальные проверки для сегодняшней демонстрации','Run visual checks first for today’s demo'],
 'research-interviews':['Начать с короткого опроса, чтобы быстрее собрать широкий отклик','Start with a short survey to gather broader feedback quickly'],
 'analysis-dependencies':['Передать согласование связей владельцам сервисов','Delegate dependency coordination to service owners'],
 'business-process':['Сохранить ручной процесс и выделить дежурного по возвратам','Keep the manual process with an on-call refund owner'],
 'business-criteria':['Проверить критерии на пилоте и уточнить перед расширением','Validate criteria in a pilot before expanding'],
 'product-metrics':['Поддержать поток заказов кампанией, пока команда исследует оплату','Support order volume with a campaign while the team investigates payments'],
 'product-priority':['Согласовать сокращённый объём всех трёх задач','Agree a reduced scope for all three tasks'],
 'project-plan':['Вести подготовку параллельно, согласуя зависимости по ходу','Prepare in parallel and coordinate dependencies as work progresses'],
 'project-resources':['Разделить людей между исправлением и пробной версией фичи','Split the team between the fix and a feature pilot'],
 'delivery-release':['Объединить изменения в более поздний, но полный релиз','Bundle changes into a later, more complete release'],
 'delivery-capacity':['Оставить резерв внутри оценок отдельных задач','Keep contingency inside individual task estimates'],
 'devops-deploy':['Выпустить в согласованное окно с дежурной командой','Release in an agreed window with the on-call team'],
 'sre-incident':['Сначала ограничить проблемный трафик, сохранив часть сервиса','Limit affected traffic first, keeping part of the service available'],
 'sre-budget':['Продолжить небольшими релизами под усиленным наблюдением','Continue small releases with increased monitoring'],
 'sysadmin-backup':['Сначала проверить восстановление самых критичных данных','Test restoration of the most critical data first'],
 'security-incident':['Сначала ограничить доступ и собрать сведения о воздействии','Restrict access first and gather impact evidence'],
 'dba-migration':['Провести перенос в отдельное окно обслуживания','Migrate during a dedicated maintenance window'],
 'solution-boundaries':['Оставить общий модуль до появления второго потребителя','Keep a shared module until a second consumer appears'],
 'solution-migration':['Выделить отдельное окно на переключение всей нагрузки','Reserve a window to switch all traffic'],
 'architecture-map':['Сохранить общую модель данных на время пилота','Keep a shared data model during the pilot'],
 'architecture-migration':['Сначала проверить новую платформу отдельным пилотом','Validate the new platform with a separate pilot first'],
 'support-escalation':['Передать владельцу и вернуться к другим обращениям','Hand over to the owner and return to other tickets'],
 'lead-review':['Самому внести правку, чтобы быстрее разблокировать коллегу','Make the change yourself to unblock the colleague sooner'],
 'lead-plan':['На этот цикл сосредоточить команду на поставке','Focus the team on delivery for this cycle']
};
export function scenarioTemplate(c:Scenario):TaskTemplate{
 const consequential=!['backend-api','backend-query','mobile-offline','mobile-layout','qa-repeat','automation-flaky','design-checkout','design-accessibility','research-evidence','data-funnel','data-cohorts','data-pipeline','data-quality','dba-query','support-diagnosis','devops-alerts','sysadmin-access','security-permissions','analysis-contract'].includes(c.id);
 const k=`scenario.${c.id}`,ordered=['planning','incident-response'].includes(c.type),allocation=c.type==='resource-allocation';
 const options:Option[]=[{id:'durable',labelKey:text(`${k}.fix`,...c.fix),responseKey:text(`${k}.ok`,'Решение закрывает причину, а не только симптом.','The solution addresses the cause, not just the symptom.'),correct:true},{id:'bad',labelKey:text(`${k}.bad`,...(alternatives[c.id]??c.bad)),responseKey:text(`${k}.retry`,'Это не решает описанную проблему. Вернись к наблюдениям из первого шага.','This does not solve the problem. Return to the evidence from the first step.'),correct:false}];
 if(consequential){for(const o of options){o.correct=undefined;o.responseKey='decision.committed';const speed=(o.id==='bad')!==['delivery-release','dba-migration','architecture-migration'].includes(c.id);o.decisionStyle=speed?'speed':'quality';o.effects=speed?[{target:'stress',value:-1},{target:'techDebt',value:2}]:[{target:'stress',value:1},{target:'techDebt',value:-2}];}}
 const app:AppId=['query-analysis','log-analysis','incident-response'].includes(c.type)?'console':['planning','resource-allocation','release-check'].includes(c.type)?'chat':'browser';
 const mechanicalEvidence=['metric-analysis','log-analysis','query-analysis','visual-compare'].includes(c.type);
 const solution=Array.isArray(c.answer)?c.answer.map(i=>`item-${i}`):c.answer;
 const first:Step={resolution:consequential&&!mechanicalEvidence?'consequential':'mechanical',id:'investigate',type:c.type,app,titleKey:text(`${k}.inspect`,'Разобраться в ситуации','Understand the situation'),bodyKey:text(`${k}.brief`,...c.brief),code:c.code,preview:c.preview,minutes:ordered?30:allocation?25:20,wrongMinutes:5,wrongEffects:[{target:'stress',value:1}],effects:[{target:'debugging',value:1},{target:'xp',value:10},{target:'energy',value:-2}],items:c.items.map(([ru,en],i)=>({id:`item-${i}`,labelKey:text(`${k}.item.${i}`,ru,en),before:c.series?.[i]?.[0],after:c.series?.[i]?.[1]})),solution,budget:c.budget,terms:c.category==='payment'?['api']:c.type==='metric-analysis'?['metric']:c.type==='incident-response'?['rollback']:['bug']};
 return {id:c.id,titleKey:text(`${k}.title`,...c.title),descriptionKey:first.bodyKey,author:['design','research'].some(s=>c.id.startsWith(s))?'anya':c.id.startsWith('qa')?'max':app==='chat'?'oleg':'sergey',estimate:30,category:c.category,contribution:c.id.startsWith('qa')||c.id.startsWith('automation')?'validation':c.id.startsWith('research')||c.id.startsWith('data-')?'discovery':'repair',rewards:[{target:'money',value:1400},{target:'xp',value:60},{target:'reputation',value:5},{target:'craft',value:1},...(c.id.startsWith('lead')?[{target:'leadership' as const,value:1}]:[])],steps:[first,{resolution:consequential?'consequential':'mechanical',id:'resolve',type:'choice',app,titleKey:text(`${k}.action`,'Что делаем с причиной?','What do we do about the cause?'),bodyKey:text(`${k}.actionBody`,'Используй факты из проверки. Коллеги ждут понятного решения.','Use the evidence you gathered. Your colleagues need a clear decision.'),options,minutes:35,wrongMinutes:7,wrongEffects:[{target:'stress',value:1}],effects:[{target:'craft',value:1},{target:'xp',value:10},{target:'energy',value:-3}]},{id:'review',type:'review',app:'chat',titleKey:'ui.sendReview',bodyKey:'ui.reviewApproved',minutes:25,wrongMinutes:0,wrongEffects:[],effects:[{target:'communication',value:1}],terms:['review','mr']} ]};
}
export const templates:TaskTemplate[]=[...frontendTasks,...scenarios.map(scenarioTemplate),...priorityTasks];
export const templateById=Object.fromEntries(templates.map(t=>[t.id,t]));

