import { startPwa } from './pwa';
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './app/App';
import './app/styles.css';
import './app/desktop.css';
import './play/game.css';
import './play/premium.css';
startPwa();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
