import {beforeEach,it,expect,vi} from 'vitest';
const save=vi.hoisted(()=>vi.fn(()=>true));
vi.mock('./world/store',()=>({saveBeforeUpdate:save}));
let target:EventTarget,worker:{postMessage:ReturnType<typeof vi.fn>},registration:EventTarget&{waiting:unknown;update:ReturnType<typeof vi.fn>},reload:ReturnType<typeof vi.fn>;
beforeEach(()=>{vi.resetModules();save.mockReset().mockReturnValue(true);vi.stubEnv('PROD',true);target=new EventTarget();worker={postMessage:vi.fn()};registration=Object.assign(new EventTarget(),{waiting:worker,update:vi.fn(async()=>{})});reload=vi.fn();vi.stubGlobal('location',{reload});vi.stubGlobal('document',Object.assign(new EventTarget(),{visibilityState:'visible'}));vi.stubGlobal('matchMedia',()=>Object.assign(new EventTarget(),{matches:false}));vi.stubGlobal('window',Object.assign(new EventTarget(),{isSecureContext:true}));vi.stubGlobal('navigator',{serviceWorker:Object.assign(target,{controller:{},register:vi.fn(async()=>registration),ready:Promise.resolve()})});vi.stubGlobal('MessageChannel',class{port1={close:vi.fn(),onmessage:null};port2={};});});
it('checks on request without activation or reload, then saves once before activation',async()=>{const pwa=await import('./pwa');pwa.startPwa();await pwa.checkForUpdate();expect(registration.update).toHaveBeenCalledOnce();expect(reload).not.toHaveBeenCalled();expect(worker.postMessage).toHaveBeenCalledWith({type:'GET_VERSION'},expect.any(Array));worker.postMessage.mockImplementation((message)=>{if(message.type==='ACTIVATE_UPDATE')expect(save).toHaveBeenCalledOnce();});pwa.applyUpdate();pwa.applyUpdate();expect(worker.postMessage.mock.calls.filter(([m])=>m.type==='ACTIVATE_UPDATE')).toHaveLength(1);target.dispatchEvent(new Event('controllerchange'));target.dispatchEvent(new Event('controllerchange'));expect(reload).toHaveBeenCalledOnce();});
it('never activates when saving fails; a subsequent retry can succeed',async()=>{const pwa=await import('./pwa');pwa.startPwa();await pwa.checkForUpdate();save.mockReturnValue(false);pwa.applyUpdate();expect(worker.postMessage.mock.calls.some(([m])=>m.type==='ACTIVATE_UPDATE')).toBe(false);expect(reload).not.toHaveBeenCalled();save.mockReturnValue(true);pwa.applyUpdate();expect(worker.postMessage.mock.calls.some(([m])=>m.type==='ACTIVATE_UPDATE')).toBe(true);});
it('can apply a downloaded update while the update check is offline',async()=>{const pwa=await import('./pwa');pwa.startPwa();await pwa.checkForUpdate();registration.update.mockRejectedValue(new Error('offline'));await pwa.checkForUpdate();pwa.applyUpdate();expect(worker.postMessage.mock.calls.some(([m])=>m.type==='ACTIVATE_UPDATE')).toBe(true);});

it('checks even when version is clicked before startup registration finishes',async()=>{const pwa=await import('./pwa');await pwa.checkForUpdate();expect(navigator.serviceWorker.register).toHaveBeenCalledOnce();expect(registration.update).toHaveBeenCalledOnce();pwa.applyUpdate();expect(save).toHaveBeenCalledOnce();});
